/**
 * BAC Mastery — Math External Learning Resource Registry
 * 
 * Curated, syllabus-aligned external learning resources for all 12 Math skills.
 * Conforms strictly to ExternalLearningResource and passes validateExternalResourceContract().
 * 
 * Rules:
 * - Safe HTTPS/HTTP URLs only (zero file/javascript schemes).
 * - Every external detour has an explicit return ticket back to BAC Mastery.
 * - Source classification and rights declarations preserved.
 */

import { ExternalLearningResource } from "@/domain/learning-ecosystem/types";

export const MATH_BATCH_01_EXTERNAL_RESOURCES: Record<string, ExternalLearningResource> = {
  math_m_arithmetic_congruence: {
    id: "res_math_m_congruence_guide",
    title_ar: "دليل الأستاذ في الحساب وقابلية القسمة والموافقات — 3 ثانوي رياضيات",
    title_fr: "Guide pédagogique: Arithmétique et congruences en Terminale Mathématiques",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/arithmetique-congruences.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_arithmetic_congruence",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "يوفر الدليل البيداغوجي الرسمي براهين نموذجية لخواص الترديد وقواعد التعامل مع الأسس الكبيرة.",
    description_fr: "Guide officiel fournissant les démonstrations types des propriétés de congruence et calculs d'exposants.",
    whyRecommended_ar: "يوفر الدليل البيداغوجي الرسمي براهين نموذجية لخواص الترديد وقواعد التعامل مع الأسس الكبيرة لدعم التعلم.",
    whyRecommended_fr: "Recommandé pour consolider la méthode de résolution des congruences avant le retest.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_bezout_diophantine: {
    id: "res_math_m_bezout_video",
    title_ar: "فيديو تدريبي: خوارزمية إقليدس الموسعة وحل المعادلات الديوفانتية في Z²",
    title_fr: "Vidéo méthodologique: Algorithme d'Euclide étendu et équations diophantiennes dans Z²",
    provider: "Plateforme Nationale d'Enseignement à Distance (ONEFD)",
    url: "https://onefd.edu.dz/cours/terminale-math/diophantienne-bezout",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_bezout_diophantine",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 15,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح خطوة بخطوة لطريقة التعويض العكسي لاستخراج المعاملات دون الوقوع في أخطاء الإشارة.",
    description_fr: "Explication étape par étape de la remontée de l'algorithme d'Euclide pour déterminer les coefficients de Bézout.",
    whyRecommended_ar: "شرح خطوة بخطوة لطريقة التعويض العكسي لاستخراج المعاملات دون الوقوع في أخطاء الإشارة الكلاسيكية.",
    whyRecommended_fr: "Recommandé pour maîtriser la remontée des restes avant de reprendre l'exercice.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_gauss_prime_factors: {
    id: "res_math_m_gauss_doc",
    title_ar: "مذكرة التفتيش البيداغوجي: مبرهنة غوص وتطبيقاتها في استخراج القواسم المشتركة",
    title_fr: "Fiche pédagogique d'inspection: Théorème de Gauss et décomposition en facteurs premiers",
    provider: "Inspection Générale de Pédagogie",
    url: "https://education.gov.dz/pedagogie/math/theoreme-gauss-pratique.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_gauss_prime_factors",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 10,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "توضيح منهجي للشروط الدقيقة لتطبيق مبرهنة غوص خاصة شرط الأولية فيما بينهما.",
    description_fr: "Clarification méthodologique des conditions d'application du théorème de Gauss.",
    whyRecommended_ar: "توضيح منهجي للشروط الدقيقة لتطبيق مبرهنة غوص خاصة شرط الأولية فيما بينهما لمنع الاستنتاج الخاطئ.",
    whyRecommended_fr: "Recommandé pour bien vérifier la condition de primalité relative avant d'appliquer Gauss.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_complex_algebraic_trig: {
    id: "res_math_m_complex_summary",
    title_ar: "ملخص منهجي: الانتقال بين الأشكال الجبرية، المثلثية والأسية للأعداد المركبة",
    title_fr: "Fiche de synthèse: Formes algébrique, trigonométrique et exponentielle des complexes",
    provider: "Centre de Recherche et de Documentation Pédagogique (CRDP)",
    url: "https://crdp.education.dz/ressources/fiches/math-complexes-formes.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_complex_algebraic_trig",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 8,
    purpose: "REVIEW",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "جدول جامع لعلاقات أويلر، دساتير موافر، وقواعد تعيين العمدة في الأرباع الأربعة.",
    description_fr: "Tableau récapitulatif des formules d'Euler, formules de Moivre et détermination de l'argument principal.",
    whyRecommended_ar: "جدول جامع لعلاقات أويلر وقواعد تعيين العمدة في الأرباع الأربعة لتثبيت المكتسبات المعرفية.",
    whyRecommended_fr: "Recommandé pour réviser rapidement les correspondances trigonométriques.",
    suggestedReturnAction: "active_recall",
  },

  math_m_similitudes_directes: {
    id: "res_math_m_similitudes_sim",
    title_ar: "محاكاة تفاعلية: استكشاف التشابهات المباشرة في المستوي المركب وعناصرها المميزة",
    title_fr: "Simulation interactive: Similitudes directes du plan complexe et éléments caractéristiques",
    provider: "GeoGebra Education Algérie",
    url: "https://www.geogebra.org/m/algerie-similitudes-directes",
    resourceType: "interactive",
    subjectId: "math",
    skillId: "math_m_similitudes_directes",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 14,
    purpose: "VISUALIZE",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "external_reference_only",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "برمجية تفاعلية تمكن التلميذ من تحريك المركز وتغيير النسبة والزاوية لمشاهدة تحويل الأشكال هندسياً.",
    description_fr: "Applet interactive permettant d'observer la transformation des figures selon le centre, rapport et angle.",
    whyRecommended_ar: "برمجية تفاعلية تمكن التلميذ من تحريك المركز وتغيير النسبة والزاوية لمشاهدة تحويل الأشكال هندسياً.",
    whyRecommended_fr: "Recommandé pour visualiser l'action géométrique d'une similitude directe avant le retest.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_derivatives_tvi_rigor: {
    id: "res_math_m_tvi_method",
    title_ar: "دليل المنهجية الرسمية: تطبيق مبرهنة القيم المتوسطة وإثبات وحدانية الحل",
    title_fr: "Guide méthodologique officiel: Théorème des valeurs intermédiaires et unicité",
    provider: "Inspection Générale de Mathématiques",
    url: "https://education.gov.dz/inspect/math/tvi-unicite-bac.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_derivatives_tvi_rigor",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 10,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح المعايير المعتمدة في تصحيح البكالوريا لصياغة شروط الاستمرار والرتابة وتحديد الحصر.",
    description_fr: "Critères officiels du barème du BAC pour la rédaction des conditions de continuité et stricte monotonie.",
    whyRecommended_ar: "شرح المعايير المعتمدة في تصحيح البكالوريا لصياغة شروط الاستمرار والرتابة وتحديد الحصر بدقة.",
    whyRecommended_fr: "Recommandé pour rédiger rigoureusement les trois conditions imposées au BAC.",
    suggestedReturnAction: "practice_micro_drill",
  },

  math_m_exp_log_croissances: {
    id: "res_math_m_growth_video",
    title_ar: "فيديو تدريبي تفاعلي: براهين نهايات التزايد المقارن وتقنيات إزالة عدم التعيين",
    title_fr: "Vidéo pédagogique: Croissances comparées et levée des formes indéterminées",
    provider: "Canal Éducatif National (CNDP)",
    url: "https://cndp.dz/cours/terminale/croissances-comparees-exp-ln",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_exp_log_croissances",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "عرض مرئي يبرهن نهايات التزايد المقارن الشهيرة ويطبقها في نماذج دقيقة شبيهة بتمارين البكالوريا.",
    description_fr: "Démonstrations visuelles des limites de croissances comparées et applications types BAC.",
    whyRecommended_ar: "عرض مرئي يبرهن نهايات التزايد المقارن الشهيرة ويطبقها في نماذج دقيقة شبيهة بتمارين البكالوريا.",
    whyRecommended_fr: "Recommandé pour mémoriser les croissances comparées et lever les indéterminations sans hésitation.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_integration_parts: {
    id: "res_math_m_ibp_sheet",
    title_ar: "دليل قواعد التكامل: اختيار دوال المكامنة بالتجزئة وحساب المساحات",
    title_fr: "Fiche méthodologique: Intégration par parties et calcul d'aires sous courbes",
    provider: "Association des Enseignants de Mathématiques d'Algérie",
    url: "https://aema.dz/ressources/terminale/integration-parties-methode.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_integration_parts",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 11,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "قاعدة ALPES لاختيار الدالة المشتقة والدالة الأصلية وتفادي الحلقات اللانهائية في التكامل.",
    description_fr: "Méthode ALPES pour choisir judicieusement la fonction à dériver lors d'une intégration par parties.",
    whyRecommended_ar: "قاعدة ALPES لاختيار الدالة المشتقة والدالة الأصلية وتفادي الحلقات اللانهائية في التكامل.",
    whyRecommended_fr: "Recommandé pour choisir sans erreur quelle fonction dériver et quelle fonction intégrer.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_differential_equations: {
    id: "res_math_m_diff_eq_doc",
    title_ar: "وثيقة توجيهية: حل المعادلات التفاضلية الخطية y'=ay+b و y''+w²y=0",
    title_fr: "Document d'accompagnement: Résolution des équations différentielles linéaires",
    provider: "Ministère de l'Éducation Nationale — Direction des Curricula",
    url: "https://education.gov.dz/curricula/math/equations-differentielles-terminale.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_differential_equations",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 10,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "عرض القوانين العامة لحلول المعادلات التفاضلية وطريقة استخراج الثوابت باستعمال الشروط الابتدائية.",
    description_fr: "Formules générales des solutions et détermination de la solution particulière selon les conditions initiales.",
    whyRecommended_ar: "عرض القوانين العامة لحلول المعادلات التفاضلية وطريقة استخراج الثوابت باستعمال الشروط الابتدائية.",
    whyRecommended_fr: "Recommandé pour revoir le calcul des constantes d'intégration avec les conditions initiales.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_induction_adjacent_suites: {
    id: "res_math_m_adjacent_seq_doc",
    title_ar: "مذكرة تفصيلية: المتتاليات المتجاورة ومبرهنة التقارب المحدود",
    title_fr: "Fiche de cours approfondie: Suites adjacentes et théorème de convergence monotone",
    provider: "CRDP Constantine",
    url: "https://crdp-constantine.dz/fiches/suites-adjacentes-bac-math.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_induction_adjacent_suites",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "البرهان الكامل على أن المتتاليتين المتجاورتين تتقاربان نحو نفس النهاية الحقيقية وطرق إثبات شروطهما.",
    description_fr: "Démonstration complète de la convergence de deux suites adjacentes vers une limite commune.",
    whyRecommended_ar: "البرهان الكامل على أن المتتاليتين المتجاورتين تتقاربان نحو نفس النهاية الحقيقية وطرق إثبات شروطهما.",
    whyRecommended_fr: "Recommandé pour vérifier les trois conditions rigoureuses des suites adjacentes.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_space_geometry_planes: {
    id: "res_math_m_space_geom_doc",
    title_ar: "دليل الهندسة الفضائية: المعادلات الديكارتية، التمثيل الوسيطي وتقاطع المستقيمات والمستويات",
    title_fr: "Guide de géométrie dans l'espace: Équations cartésiennes, représentations paramétriques",
    provider: "CNDP Alger",
    url: "https://cndp.dz/ressources/math/terminale/geometrie-espace-methodes.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_space_geometry_planes",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 14,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح شامل لحساب المسافة بين نقطة ومستو، تعيين تقاطع مستقيم ومستو، ودراسة الوضع النسبي.",
    description_fr: "Calcul de distance d'un point à un plan, intersection droite-plan et positions relatives.",
    whyRecommended_ar: "شرح شامل لحساب المسافة بين نقطة ومستو، تعيين تقاطع مستقيم ومستو، ودراسة الوضع النسبي.",
    whyRecommended_fr: "Recommandé pour maîtriser les systèmes d'équations paramétriques de droites et de plans.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_combinatorics_bernoulli: {
    id: "res_math_m_binomial_video",
    title_ar: "فيديو تدريبي: مخطط شجرة الاحتمالات وقانون ثنائي الحد وتطبيقاته في البكالوريا",
    title_fr: "Vidéo pédagogique: Arbre pondéré, loi binomiale et applications au BAC",
    provider: "ONEFD Algérie",
    url: "https://onefd.edu.dz/cours/terminale-math/loi-binomiale-exercices",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_combinatorics_bernoulli",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 13,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "كيفية تمييز مخطط برنولي وشروط تطبيق قانون ثنائي الحد وحساب الأمل الرياضي والتباين.",
    description_fr: "Identification d'un schéma de Bernoulli, conditions de la loi binomiale et calcul de l'espérance.",
    whyRecommended_ar: "كيفية تمييز مخطط برنولي وشروط تطبيق قانون ثنائي الحد وحساب الأمل الرياضي والتباين.",
    whyRecommended_fr: "Recommandé pour bien vérifier l'indépendance des épreuves avant d'utiliser la formule binomiale.",
    suggestedReturnAction: "isomorphic_retest",
  },
};
