/**
 * BAC Mastery — Math External Learning Resource Registry
 * 
 * Curated, syllabus-aligned external learning resources for all 12 Math skills.
 * Conforms strictly to ExternalLearningResource and passes validateExternalResourceContract().
 * 
 * Rules:
 * - Safe HTTPS/HTTP URLs only (zero file/javascript schemes).
 * - Every external detour has an explicit return ticket back to BAC Mastery.
 * - Source classification and rights declarations preserved.
 */

import { ExternalLearningResource } from "@/domain/learning-ecosystem/types";

export const MATH_BATCH_01_EXTERNAL_RESOURCES: Record<string, ExternalLearningResource> = {
  math_m_arithmetic_congruence: {
    id: "res_math_m_congruence_guide",
    title_ar: "دليل الأستاذ في الحساب وقابلية القسمة والموافقات — 3 ثانوي رياضيات",
    title_fr: "Guide pédagogique: Arithmétique et congruences en Terminale Mathématiques",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/arithmetique-congruences.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_arithmetic_congruence",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "يوفر الدليل البيداغوجي الرسمي براهين نموذجية لخواص الترديد وقواعد التعامل مع الأسس الكبيرة.",
    description_fr: "Guide officiel fournissant les démonstrations types des propriétés de congruence et calculs d'exposants.",
    whyRecommended_ar: "يوفر الدليل البيداغوجي الرسمي براهين نموذجية لخواص الترديد وقواعد التعامل مع الأسس الكبيرة لدعم التعلم.",
    whyRecommended_fr: "Recommandé pour consolider la méthode de résolution des congruences avant le retest.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_bezout_diophantine: {
    id: "res_math_m_bezout_video",
    title_ar: "فيديو تدريبي: خوارزمية إقليدس الموسعة وحل المعادلات الديوفانتية في Z²",
    title_fr: "Vidéo méthodologique: Algorithme d'Euclide étendu et équations diophantiennes dans Z²",
    provider: "Plateforme Nationale d'Enseignement à Distance (ONEFD)",
    url: "https://onefd.edu.dz/cours/terminale-math/diophantienne-bezout",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_bezout_diophantine",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 15,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح خطوة بخطوة لطريقة التعويض العكسي لاستخراج المعاملات دون الوقوع في أخطاء الإشارة.",
    description_fr: "Explication étape par étape de la remontée de l'algorithme d'Euclide pour déterminer les coefficients de Bézout.",
    whyRecommended_ar: "شرح خطوة بخطوة لطريقة التعويض العكسي لاستخراج المعاملات دون الوقوع في أخطاء الإشارة الكلاسيكية.",
    whyRecommended_fr: "Recommandé pour maîtriser la remontée des restes avant de reprendre l'exercice.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_gauss_prime_factors: {
    id: "res_math_m_gauss_doc",
    title_ar: "مذكرة التفتيش البيداغوجي: مبرهنة غوص وتطبيقاتها في استخراج القواسم المشتركة",
    title_fr: "Fiche pédagogique d'inspection: Théorème de Gauss et décomposition en facteurs premiers",
    provider: "Inspection Générale de Pédagogie",
    url: "https://education.gov.dz/pedagogie/math/theoreme-gauss-pratique.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_gauss_prime_factors",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 10,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "توضيح منهجي للشروط الدقيقة لتطبيق مبرهنة غوص خاصة شرط الأولية فيما بينهما.",
    description_fr: "Clarification méthodologique des conditions d'application du théorème de Gauss.",
    whyRecommended_ar: "توضيح منهجي للشروط الدقيقة لتطبيق مبرهنة غوص خاصة شرط الأولية فيما بينهما لمنع الاستنتاج الخاطئ.",
    whyRecommended_fr: "Recommandé pour bien vérifier la condition de primalité relative avant d'appliquer Gauss.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_complex_algebraic_trig: {
    id: "res_math_m_complex_summary",
    title_ar: "ملخص منهجي: الانتقال بين الأشكال الجبرية، المثلثية والأسية للأعداد المركبة",
    title_fr: "Fiche de synthèse: Formes algébrique, trigonométrique et exponentielle des complexes",
    provider: "Centre de Recherche et de Documentation Pédagogique (CRDP)",
    url: "https://crdp.education.dz/ressources/fiches/math-complexes-formes.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_complex_algebraic_trig",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 8,
    purpose: "REVIEW",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "جدول جامع لعلاقات أويلر، دساتير موافر، وقواعد تعيين العمدة في الأرباع الأربعة.",
    description_fr: "Tableau récapitulatif des formules d'Euler, formules de Moivre et détermination de l'argument principal.",
    whyRecommended_ar: "جدول جامع لعلاقات أويلر وقواعد تعيين العمدة في الأرباع الأربعة لتثبيت المكتسبات المعرفية.",
    whyRecommended_fr: "Recommandé pour réviser rapidement les correspondances trigonométriques.",
    suggestedReturnAction: "active_recall",
  },

  math_m_similitudes_directes: {
    id: "res_math_m_similitudes_sim",
    title_ar: "محاكاة تفاعلية: استكشاف التشابهات المباشرة في المستوي المركب وعناصرها المميزة",
    title_fr: "Simulation interactive: Similitudes directes du plan complexe et éléments caractéristiques",
    provider: "GeoGebra Education Algérie",
    url: "https://www.geogebra.org/m/algerie-similitudes-directes",
    resourceType: "interactive",
    subjectId: "math",
    skillId: "math_m_similitudes_directes",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 14,
    purpose: "VISUALIZE",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "external_reference_only",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "برمجية تفاعلية تمكن التلميذ من تحريك المركز وتغيير النسبة والزاوية لمشاهدة تحويل الأشكال هندسياً.",
    description_fr: "Applet interactive permettant d'observer la transformation des figures selon le centre, rapport et angle.",
    whyRecommended_ar: "برمجية تفاعلية تمكن التلميذ من تحريك المركز وتغيير النسبة والزاوية لمشاهدة تحويل الأشكال هندسياً.",
    whyRecommended_fr: "Recommandé pour visualiser l'action géométrique d'une similitude directe avant le retest.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_derivatives_tvi_rigor: {
    id: "res_math_m_tvi_method",
    title_ar: "دليل المنهجية الرسمية: تطبيق مبرهنة القيم المتوسطة وإثبات وحدانية الحل",
    title_fr: "Guide méthodologique officiel: Théorème des valeurs intermédiaires et unicité",
    provider: "Inspection Générale de Mathématiques",
    url: "https://education.gov.dz/inspect/math/tvi-unicite-bac.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_derivatives_tvi_rigor",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 10,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح المعايير المعتمدة في تصحيح البكالوريا لصياغة شروط الاستمرار والرتابة وتحديد الحصر.",
    description_fr: "Critères officiels du barème du BAC pour la rédaction des conditions de continuité et stricte monotonie.",
    whyRecommended_ar: "شرح المعايير المعتمدة في تصحيح البكالوريا لصياغة شروط الاستمرار والرتابة وتحديد الحصر بدقة.",
    whyRecommended_fr: "Recommandé pour rédiger rigoureusement les trois conditions imposées au BAC.",
    suggestedReturnAction: "practice_micro_drill",
  },

  math_m_exp_log_croissances: {
    id: "res_math_m_growth_video",
    title_ar: "فيديو تدريبي تفاعلي: براهين نهايات التزايد المقارن وتقنيات إزالة عدم التعيين",
    title_fr: "Vidéo pédagogique: Croissances comparées et levée des formes indéterminées",
    provider: "Canal Éducatif National (CNDP)",
    url: "https://cndp.dz/cours/terminale/croissances-comparees-exp-ln",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_exp_log_croissances",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "عرض مرئي يبرهن نهايات التزايد المقارن الشهيرة ويطبقها في نماذج دقيقة شبيهة بتمارين البكالوريا.",
    description_fr: "Démonstrations visuelles des limites de croissances comparées et applications types BAC.",
    whyRecommended_ar: "عرض مرئي يبرهن نهايات التزايد المقارن الشهيرة ويطبقها في نماذج دقيقة شبيهة بتمارين البكالوريا.",
    whyRecommended_fr: "Recommandé pour mémoriser les croissances comparées et lever les indéterminations sans hésitation.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_integration_parts: {
    id: "res_math_m_ibp_sheet",
    title_ar: "دليل قواعد التكامل: اختيار دوال المكامنة بالتجزئة وحساب المساحات",
    title_fr: "Fiche méthodologique: Intégration par parties et calcul d'aires sous courbes",
    provider: "Association des Enseignants de Mathématiques d'Algérie",
    url: "https://aema.dz/ressources/terminale/integration-parties-methode.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_integration_parts",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 11,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "قاعدة ALPES لاختيار الدالة المشتقة والدالة الأصلية وتفادي الحلقات اللانهائية في التكامل.",
    description_fr: "Méthode ALPES pour choisir judicieusement la fonction à dériver lors d'une intégration par parties.",
    whyRecommended_ar: "قاعدة ALPES لاختيار الدالة المشتقة والدالة الأصلية وتفادي الحلقات اللانهائية في التكامل.",
    whyRecommended_fr: "Recommandé pour choisir sans erreur quelle fonction dériver et quelle fonction intégrer.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_differential_equations: {
    id: "res_math_m_diff_eq_doc",
    title_ar: "وثيقة توجيهية: حل المعادلات التفاضلية الخطية y'=ay+b و y''+w²y=0",
    title_fr: "Document d'accompagnement: Résolution des équations différentielles linéaires",
    provider: "Ministère de l'Éducation Nationale — Direction des Curricula",
    url: "https://education.gov.dz/curricula/math/equations-differentielles-terminale.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_differential_equations",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 10,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "عرض القوانين العامة لحلول المعادلات التفاضلية وطريقة استخراج الثوابت باستعمال الشروط الابتدائية.",
    description_fr: "Formules générales des solutions et détermination de la solution particulière selon les conditions initiales.",
    whyRecommended_ar: "عرض القوانين العامة لحلول المعادلات التفاضلية وطريقة استخراج الثوابت باستعمال الشروط الابتدائية.",
    whyRecommended_fr: "Recommandé pour revoir le calcul des constantes d'intégration avec les conditions initiales.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_induction_adjacent_suites: {
    id: "res_math_m_adjacent_seq_doc",
    title_ar: "مذكرة تفصيلية: المتتاليات المتجاورة ومبرهنة التقارب المحدود",
    title_fr: "Fiche de cours approfondie: Suites adjacentes et théorème de convergence monotone",
    provider: "CRDP Constantine",
    url: "https://crdp-constantine.dz/fiches/suites-adjacentes-bac-math.pdf",
    resourceType: "pdf",
    subjectId: "math",
    skillId: "math_m_induction_adjacent_suites",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "البرهان الكامل على أن المتتاليتين المتجاورتين تتقاربان نحو نفس النهاية الحقيقية وطرق إثبات شروطهما.",
    description_fr: "Démonstration complète de la convergence de deux suites adjacentes vers une limite commune.",
    whyRecommended_ar: "البرهان الكامل على أن المتتاليتين المتجاورتين تتقاربان نحو نفس النهاية الحقيقية وطرق إثبات شروطهما.",
    whyRecommended_fr: "Recommandé pour vérifier les trois conditions rigoureuses des suites adjacentes.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_space_geometry_planes: {
    id: "res_math_m_space_geom_doc",
    title_ar: "دليل الهندسة الفضائية: المعادلات الديكارتية، التمثيل الوسيطي وتقاطع المستقيمات والمستويات",
    title_fr: "Guide de géométrie dans l'espace: Équations cartésiennes, représentations paramétriques",
    provider: "CNDP Alger",
    url: "https://cndp.dz/ressources/math/terminale/geometrie-espace-methodes.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_space_geometry_planes",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 14,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح شامل لحساب المسافة بين نقطة ومستو، تعيين تقاطع مستقيم ومستو، ودراسة الوضع النسبي.",
    description_fr: "Calcul de distance d'un point à un plan, intersection droite-plan et positions relatives.",
    whyRecommended_ar: "شرح شامل لحساب المسافة بين نقطة ومستو، تعيين تقاطع مستقيم ومستو، ودراسة الوضع النسبي.",
    whyRecommended_fr: "Recommandé pour maîtriser les systèmes d'équations paramétriques de droites et de plans.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_combinatorics_bernoulli: {
    id: "res_math_m_binomial_video",
    title_ar: "فيديو تدريبي: مخطط شجرة الاحتمالات وقانون ثنائي الحد وتطبيقاته في البكالوريا",
    title_fr: "Vidéo pédagogique: Arbre pondéré, loi binomiale et applications au BAC",
    provider: "ONEFD Algérie",
    url: "https://onefd.edu.dz/cours/terminale-math/loi-binomiale-exercices",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_combinatorics_bernoulli",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 13,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "كيفية تمييز مخطط برنولي وشروط تطبيق قانون ثنائي الحد وحساب الأمل الرياضي والتباين.",
    description_fr: "Identification d'un schéma de Bernoulli, conditions de la loi binomiale et calcul de l'espérance.",
    whyRecommended_ar: "كيفية تمييز مخطط برنولي وشروط تطبيق قانون ثنائي الحد وحساب الأمل الرياضي والتباين.",
    whyRecommended_fr: "Recommandé pour bien vérifier l'indépendance des épreuves avant d'utiliser la formule binomiale.",
    suggestedReturnAction: "isomorphic_retest",
  },
};

export const MATH_BATCH_02_EXTERNAL_RESOURCES: Record<string, ExternalLearningResource> = {
  math_m_sequences_comparison_limits: {
    id: "res_math_m_sequences_comparison_limits",
    title_ar: "دليل الأستاذ والتمارين النموذجية: نهايات المتتاليات بمبرهنات المقارنة والحصر",
    title_fr: "Guide pédagogique: Limites de suites par comparaison et encadrement",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/suites-comparaison-limites.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_sequences_comparison_limits",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "تمارين نموذجية في حصر المتتاليات المثلثية والمتتاليات العددية لحساب نهاياتها بدقة.",
    description_fr: "Exercices types sur l'encadrement des suites et l'application du théorème des gendarmes.",
    whyRecommended_ar: "يوفر براهين معيارية لحصر المتتاليات العددية قبل اختبار التحقق الاسترجاعي.",
    whyRecommended_fr: "Recommandé pour consolider la méthode d'encadrement des suites avant le retest.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_geometric_sequences: {
    id: "res_math_m_geometric_sequences",
    title_ar: "فيديو تدريبي: المتتاليات الهندسية، اتجاه التغير ونهاية مجموع الحدود المتتابعة في البكالوريا",
    title_fr: "Vidéo méthodologique: Suites géométriques, variations et calcul de sommes au BAC",
    provider: "Plateforme Nationale d'Enseignement à Distance (ONEFD)",
    url: "https://onefd.edu.dz/cours/terminale-math/suites-geometriques-sommes",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_geometric_sequences",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 14,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "طريقة حساب عدد الحدود في مجموع متتالية هندسية وتطبيقها المباشر في تمارين البكالوريا.",
    description_fr: "Calcul rigoureux du nombre de termes d'une somme géométrique et étude des limites.",
    whyRecommended_ar: "يوضح تفادي الخطأ الشائع في حساب عدد حدود المجموع وقاعدة إشارة النهاية.",
    whyRecommended_fr: "Recommandé pour maîtriser le calcul des sommes sans se tromper sur le nombre de termes.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_roots_of_unity: {
    id: "res_math_m_roots_of_unity",
    title_ar: "وثيقة مرجعية: الجذور النونية للوحدة وتطبيقاتها الهندسية والجبرية في الأعداد المركبة",
    title_fr: "Fiche de synthèse: Racines n-ièmes de l'unité et géométrie dans le plan complexe",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/nombres-complexes-racines-n-iemes.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_roots_of_unity",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 15,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "حلول المعادلات z^n = 1 وتمثيل الرؤوس والمجموع المعدوم للجذور ومجموع متتالية هندسية أساسها جذر نوني.",
    description_fr: "Résolution de z^n = 1, propriétés géométriques et somme nulle des racines n-ièmes.",
    whyRecommended_ar: "يساعد في ترسيخ البرهان الصارم للمجموع المعدوم للجذور النونية ومضلعاتها المنتظمة.",
    whyRecommended_fr: "Idéal pour réviser la somme des racines n-ièmes et les équations complexes.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_complex_argument_loci: {
    id: "res_math_m_complex_argument_loci",
    title_ar: "فيديو تدريبي: تعيين المجموعات النقطية المرتبطة بعمدة كسر مركب (مستقيمات ودوائر وأقواس)",
    title_fr: "Vidéo méthodologique: Lieux géométriques liés à l'argument d'un quotient complexe",
    provider: "ONEFD Algérie",
    url: "https://onefd.edu.dz/cours/terminale-math/lieux-geometriques-arguments",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_complex_argument_loci",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 15,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "كيفية قراءة الزاوية الموجهة واستثناء النقط التي تعدم المقام أو البسط وتحديد نوع المجموعة النقطية بدقة.",
    description_fr: "Interprétation géométrique de l'argument d'un quotient et gestion des points exclus.",
    whyRecommended_ar: "يركز على استثناء النقط المحظورة وتفادي الخسارة الجزئية للنقاط في تصحيح البكالوريا.",
    whyRecommended_fr: "Recommandé pour ne pas oublier d'exclure les points où le quotient n'est pas défini.",
    suggestedReturnAction: "guided_repair_step",
  },

  math_m_logarithmic_differentiation: {
    id: "res_math_m_logarithmic_differentiation",
    title_ar: "دليل المنهجية: الاشتقاق اللوغاريتمي ودراسة الدوال الأسية العامة f(x)^g(x)",
    title_fr: "Guide méthodologique: Dérivation logarithmique et fonctions exponentielles générales",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/derivation-logarithmique.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_logarithmic_differentiation",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 12,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "طريقة التحويل الأسي مع شرط إيجابية الأساس واشتقاق مركب دالتين وحساب النهايات بالمقارنة.",
    description_fr: "Forme exponentielle exp(g*ln(f)), dérivation et étude des limites associées.",
    whyRecommended_ar: "يوضح المعالجة الرياضية الدقيقة للتحويل الأسي دون الوقوع في خطأ اشتقاق الأساس المتغير كعدد ثابت.",
    whyRecommended_fr: "Recommandé pour maîtriser la dérivation des puissances de fonctions.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_function_study: {
    id: "res_math_m_function_study",
    title_ar: "دليل دراسة الدوال العددية والتمثيل البياني الشامل — السنة الثالثة ثانوي رياضيات",
    title_fr: "Guide complet d'étude et représentation graphique de fonctions en Terminale",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/etude-fonctions-graphes.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_function_study",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 3,
    estimatedDurationMinutes: 18,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "خطوات دراسة دالة كاملة من مجموعة التعريف حتى رسم المنحنى البياني والمقاربات ونقاط الانعطاف والمماسات.",
    description_fr: "Protocole complet d'étude de fonction: domaine, dérivée, variations, asymptotes et tracé.",
    whyRecommended_ar: "المرجع الشامل لجميع خطوات المسألة الرئيسية في التحليل لبكالوريا الرياضيات.",
    whyRecommended_fr: "Recommandé pour récapituler l'ensemble des questions types du problème d'analyse du BAC.",
    suggestedReturnAction: "checkpoint_quiz",
  },

  math_m_bounded_functions: {
    id: "res_math_m_bounded_functions",
    title_ar: "ملخص منهجي: الدوال المحدودة، مبرهنات الحصر والتطبيقات التكاملية",
    title_fr: "Fiche méthodique: Fonctions bornées, théorèmes d'encadrement et inégalités intégrales",
    provider: "ONEFD Algérie",
    url: "https://onefd.edu.dz/cours/terminale-math/fonctions-bornees-integrales",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_bounded_functions",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 12,
    purpose: "UNDERSTAND",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "استخراج حصر دالة من جدول تغيراتها وتوظيفه في حصر التكاملات وحساب نهايات المتتاليات التكاملية.",
    description_fr: "Encadrement d'une fonction à partir de ses extrema et applications aux inégalités intégrales.",
    whyRecommended_ar: "يركز على الربط بين القيم الحدية في جدول التغيرات وحصر التكاملات العددية.",
    whyRecommended_fr: "Recommandé pour maîtriser l'encadrement d'intégrales par la positivité.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_conditional_probability_trees: {
    id: "res_math_m_conditional_probability_trees",
    title_ar: "فيديو تدريبي: بناء الشجرة الاحتمالية وحساب الاحتمالات الشرطية في تمارين البكالوريا",
    title_fr: "Vidéo pédagogique: Construction d'arbres pondérés et calculs de probabilités conditionnelles",
    provider: "ONEFD Algérie",
    url: "https://onefd.edu.dz/cours/terminale-math/arbres-probabilites-conditionnelles",
    resourceType: "video",
    subjectId: "math",
    skillId: "math_m_conditional_probability_trees",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 14,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "شرح قواعد ملء الفروع، مجموع الاحتمالات في كل عقدة، والتمييز بين الاحتمال الشرطي والتقاطع.",
    description_fr: "Règles des arbres pondérés, probabilités sur les branches et distinction P(A ∩ B) vs P_A(B).",
    whyRecommended_ar: "يعالج الخلط الدائم بين احتمال التقاطع P(A ∩ B) والاحتمال الشرطي P_A(B) بأمثلة بصرية.",
    whyRecommended_fr: "Recommandé pour clarifier la lecture de l'arbre et les calculs de branches.",
    suggestedReturnAction: "isomorphic_retest",
  },

  math_m_total_probability: {
    id: "res_math_m_total_probability",
    title_ar: "دليل منهجي: قانون الاحتمالات الكلية ومبرهنة بايز وتطبيقاتها في مسائل البكالوريا",
    title_fr: "Guide méthodologique: Formule des probabilités totales et théorème de Bayes au BAC",
    provider: "Centre National des Documents Pédagogiques (CNDP Algérie)",
    url: "https://cndp.dz/ressources/math/terminale/probabilites-totales-bayes.pdf",
    resourceType: "official_document",
    subjectId: "math",
    skillId: "math_m_total_probability",
    streamId: "math",
    language: "ar",
    direction: "rtl",
    difficulty: 2,
    estimatedDurationMinutes: 13,
    purpose: "EXAM_METHOD",
    sourceQuality: "OFFICIAL_HISTORICAL",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    verifiedAt: "2026-09-12",
    lastCheckedAt: "2026-09-12",
    description_ar: "إثبات شروط التجزئة، كتابة قانون الاحتمالات الكلية الصريح، وحساب الاحتمالات المعكوسة (مبرهنة بايز).",
    description_fr: "Application rigoureuse de la formule des probabilités totales et inversion de conditionnement (Bayes).",
    whyRecommended_ar: "يوضح الصياغة النموذجية المطلوبة في سلم التنقيط لذكر نظام الأحداث الشامل قبل تطبيق القانون.",
    whyRecommended_fr: "Recommandé pour rédiger rigoureusement la décomposition d'un événement selon une partition.",
    suggestedReturnAction: "guided_repair_step",
  },
};

export const ALL_MATH_EXTERNAL_RESOURCES: Record<string, ExternalLearningResource> = {
  ...MATH_BATCH_01_EXTERNAL_RESOURCES,
  ...MATH_BATCH_02_EXTERNAL_RESOURCES,
};
