/**
 * BAC Mastery — Expert Guidance Catalog
 * Prompt 12: Evidence-based principles from recognized cognitive scientists
 * 
 * Invariant: Content Purity (ZERO user_id).
 */

import { ExpertGuidance } from "./types";

export const PROMPT12_EXPERT_GUIDANCE: ExpertGuidance[] = [
  {
    id: "eg_01_roediger_retrieval",
    expertName: "Henry L. Roediger III & Jeffrey D. Karpicke",
    expertField: "Cognitive Psychology (Memory & Testing Effect)",
    institutionOrAffiliation: "Washington University in St. Louis & Purdue University",
    primaryPublication: "Roediger & Karpicke (2006), 'Test-Enhanced Learning: Taking Memory Tests Improves Long-Term Retention', Psychological Science",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "ممارسة الاسترجاع من الذاكرة (Retrieval Practice) تبني مسارات عصبية متينة وتضمن بقاء المعلومات أطول بكثير من مجرد إعادة القراءة السلبية.",
    bacMasteryInterpretation_ar: "إعادة قراءة الملخص 5 مرات تعطي إحساساً زائفاً بالفهم، لكنها تتبخر بعد أيام. عندما تغلق الدرس وتحاول تذكر القوانين بنفسك على ورقة بيضاء، فإن الجهد الذهني الذي تبذله هو بالضبط ما يبني ذاكرة قوية تدوم حتى يوم البكالوريا.",
    actionForStudent_ar: "قبل أن تبدأ بحل أي تمرين، خذ دقيقتين لكتابة القوانين الثلاثة الأساسية للمحور على ورقة بيضاء دون النظر إلى الملخص.",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_02_dunlosky_effective_techniques",
    expertName: "John Dunlosky et al.",
    expertField: "Educational Psychology & Cognitive Science",
    institutionOrAffiliation: "Kent State University",
    primaryPublication: "Dunlosky et al. (2013), 'Improving Students' Learning With Effective Learning Techniques', Psychological Science in the Public Interest",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "استراتيجيات حل الاختبارات والممارسة الموزعة على فترات زمنية هي الأعلى فاعلية تجريبياً، بينما التظليل وإعادة القراءة منخفضة المردود.",
    bacMasteryInterpretation_ar: "أكثر الطرق التي يضيع فيها تلاميذ البكالوريا أوقاتهم هي تظليل الكراريس بالألوان وإعادة كتابة الملخصات للمرة الثالثة. الأبحاث أثبتت أن حل التمارين المتنوعة وتوزيع المراجعة على أسابيع يعطي نتائج مضاعفة بأقل مجهود ضائع.",
    actionForStudent_ar: "استبدل جلسة قراءة الملخصات الليلة بجلسة حل 4 أسئلة سريعة مختارة من تمارين البكالوريا السابقة.",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_03_rohrer_interleaving",
    expertName: "Doug Rohrer & Kelli Taylor",
    expertField: "Cognitive Sciences & Mathematics Education",
    institutionOrAffiliation: "University of South Florida",
    primaryPublication: "Rohrer & Taylor (2007), 'The Shuffling of Mathematics Problems Improves Learning', Instructional Science",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "الخلط بين أنواع المسائل الرياضية المختلفة (Interleaving) يدرب الدماغ على التمييز بين المسائل ومعرفة متى يطبق كل قانون.",
    bacMasteryInterpretation_ar: "عندما تحل 15 نهاية متتالية بنفس الطريقة، عقلك لا يتعلم كيف يختار الطريقة، بل يكرر حركة آلية فقط. في موضوع البكالوريا، لا يوجد عنوان يقول 'استعمل مبرهنة التزايد المقارن هنا'. الخلط بين التمارين هو الذي يعلمك تمييز السؤال في الامتحان الحقيقي.",
    actionForStudent_ar: "عند مراجعة الرياضيات، لا تحل 10 مسائل نهايات متتالية؛ بل حل مسألة نهايات، ثم مسألة مماس، ثم مسألة متتاليات بالتناوب.",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_04_metcalfe_errors",
    expertName: "Janet Metcalfe",
    expertField: "Metacognition and Memory Laboratory",
    institutionOrAffiliation: "Columbia University",
    primaryPublication: "Metcalfe (2017), 'Learning from Errors', Annual Review of Psychology",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "الخطأ المرتكب بثقة عالية يولد قفزة انتباه فائقة عند التصحيح الفوري، مما يجعل التعلم من الخطأ أقوى بكثير من عدم الوقوع فيه.",
    bacMasteryInterpretation_ar: "الخطأ الذي ترتكبه وأنت واثق من إجابتك هو أعظم فرصة تعليمية لك طوال العام. الدماغ ينتبه بقوة مضاعفة عندما يكتشف المفارقة بين ثقته والواقع. لا تتضايق من الخطأ في تمرين تجريبي؛ افرح بأنك اكتشفته قبل أن ترتكبه في البكالوريا.",
    actionForStudent_ar: "عندما تخطئ في تمرين، لا تشطب الإجابة فقط؛ اكتب بجانبها بلون مختلف: 'السبب في خطأي هو كذا، والصواب هو كذا لأن...'",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_05_sweller_cognitive_load",
    expertName: "John Sweller",
    expertField: "Cognitive Load Theory & Instructional Design",
    institutionOrAffiliation: "University of New South Wales",
    primaryPublication: "Sweller (1988), 'Cognitive Load During Problem Solving', Cognitive Science",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "دراسة الأمثلة المحلولة بعناية تحمي الذاكرة العاملة من الإرهاق وتساعد على بناء نماذج ذهنية واضحة قبل حل المسائل المعقدة.",
    bacMasteryInterpretation_ar: "إذا بدأت مباشرة بمسألة بكالوريا معقدة وأنت ما زلت تائهاً في الأساسيات، ستصاب بالإحباط لأن ذاكرتك قصيرة المدى تختنق بالمعلومات. ابدأ بمثال محلول بعناية يريك كيف يفكر الأستاذ خطوة بخطوة، ثم جرب بنفسك في مسألة مماثلة.",
    actionForStudent_ar: "اقرأ المثال المحلول في درس BAC Mastery وركز على قسم 'كيف نفكر في السؤال' قبل أن تلمس القلم لحل التمرين التطبيقي.",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_06_willingham_memory",
    expertName: "Daniel T. Willingham",
    expertField: "Cognitive Psychology & Educational Neuroscience",
    institutionOrAffiliation: "University of Virginia",
    primaryPublication: "Willingham (2009), 'Why Don't Students Like School? A Cognitive Scientist Answers Questions', Jossey-Bass",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "الذاكرة هي أثر التفكير: لن تتذكر ما تراه أو تسمعه، بل ستتذكر ما فكرت فيه بعمق وعالجت معناه في عقلك.",
    bacMasteryInterpretation_ar: "لن تتذكر ما سمعته في القسم، ولن تتذكر ما شاهده عينك في الفيديو؛ ستتذكر فقط ما فكرت فيه بعمق وبحثت عن معناه. إذا أردت حفظ تجربة في العلوم الطبيعية، اشرح لنفسك لماذا استخدم المجرب تلك المادة المحددة وما الذي كان سيحدث لو لم يستخدمها.",
    actionForStudent_ar: "في أي تجربة علوم أو فيزياء، اسأل نفسك دائماً: 'ما هو دور الشاهد التجريبي؟ وماذا تثبت هذه النتيجة تحديداً؟'",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "eg_07_ericsson_deliberate_practice",
    expertName: "K. Anders Ericsson",
    expertField: "Psychology of Human Performance and Expertise",
    institutionOrAffiliation: "Florida State University",
    primaryPublication: "Ericsson, Krampe, & Tesch-Römer (1993), 'The Role of Deliberate Practice in the Acquisition of Expert Performance', Psychological Review",
    evidenceLevel: "Tier 1 (High)",
    principle_ar: "التكرار العشوائي لا يصنع التفوق؛ التطور الحقيقي يحدث بالممارسة المتعمدة التي تستهدف الثغرات الدقيقة مع تصحيح فوري مستمر.",
    bacMasteryInterpretation_ar: "حل 50 تمرين بكالوريا في الجزء الذي تفهمه بالفعل لن يرفع علامتك من 12 إلى 17. الرفع الحقيقي للعلامة يحدث عندما تعزل الجزئية التي تهرب منها دائماً (مثلاً: حساب النهايات بالتزايد المقارن أو إيجاد ثابت الزمن بيانياً) وتقضي فيها 20 دقيقة تدريب موجه.",
    actionForStudent_ar: "اختر المهارة التي تشعر بأكبر قدر من التردد عند مواجهتها، واجعلها مهمتك الأولى اليوم في BAC Mastery.",
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "trusted_educational_source",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
