/**
 * BAC Mastery — Mini Exams Catalog
 * Prompt 12: Calibrated evaluation vehicles (Skill Quiz, Topic Test, Weekly Checkpoint)
 * 
 * Invariant: Content Purity (ZERO user_id).
 */

import { MiniExam } from "./types";

export const PROMPT12_MINI_EXAMS: MiniExam[] = [
  {
    id: "mini_exam_math_functions_quiz",
    type: "skill_quiz",
    title_ar: "اختبار مهارة الاشتقاق وقاعدة السلسلة",
    title_fr: "Mini-Quiz : Dérivation composée et règle de chaîne",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: ["math_derivatives_chain_rule"],
    questionIds: ["pq-math-chain-01"],
    timeTargetMinutes: 10,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_rc_quiz",
    type: "skill_quiz",
    title_ar: "اختبار مهارة ثابت الزمن tau لدارة RC",
    title_fr: "Mini-Quiz : Constante de temps tau du dipôle RC",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: ["physics_rc_time_constant"],
    questionIds: ["pq-phys-rc-01"],
    timeTargetMinutes: 10,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_math_topic_functions",
    type: "topic_test",
    title_ar: "اختبار محور الدوال العددية والاشتقاقية",
    title_fr: "Test de chapitre : Fonctions numériques et dérivabilité",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: [
      "math_derivatives_chain_rule",
      "math_intermediate_value_method",
      "math_asymptotes_limits",
      "math_tangent_convexity",
    ],
    questionIds: ["pq-math-chain-01", "pq-math-asymptotes-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_topic_rc_rl",
    type: "topic_test",
    title_ar: "اختبار محور الظواهر الكهربائية (RC و RL)",
    title_fr: "Test de chapitre : Phénomènes électriques (RC et RL)",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: [
      "physics_rc_time_constant",
      "physics_rc_differential_equation",
      "physics_rl_circuit_response",
    ],
    questionIds: ["pq-phys-rc-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_snv_topic_synthesis",
    type: "topic_test",
    title_ar: "اختبار محور آليات تركيب البروتين",
    title_fr: "Test de chapitre : Mécanismes de la biosynthèse protéique",
    subjectId: "natural_sciences",
    topicId: "snv_topic_protein_synthesis",
    skillIds: [
      "snv_protein_synthesis",
      "snv_genetic_code_translation",
      "snv_protein_structure_ionization",
    ],
    questionIds: ["pq-snv-protein-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_sciences_checkpoint_01",
    type: "weekly_checkpoint",
    title_ar: "المحطة الأسبوعية التراكمية الأولى — مدمجة",
    title_fr: "Checkpoint hebdomadaire 01 : Évaluation entrelacée",
    subjectId: "math",
    skillIds: [
      "math_derivatives_chain_rule",
      "physics_rc_time_constant",
      "snv_protein_synthesis",
    ],
    questionIds: ["pq-math-chain-01", "pq-phys-rc-01", "pq-snv-protein-01"],
    timeTargetMinutes: 45,
    difficultyProfile: { foundation: 1, standard: 2, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
