/**
 * BAC Mastery — Mini Exams Catalog
 * Prompt 13: Calibrated evaluation vehicles covering all 31 Curriculum Skills
 * 
 * Invariant: Content Purity (ZERO user_id).
 */

import { MiniExam } from "./types";

export const PROMPT12_MINI_EXAMS: MiniExam[] = [
  // ==========================================================================
  // TOPIC TESTS — MATHEMATICS (4 Topics, 10 Skills)
  // ==========================================================================
  {
    id: "mini_exam_math_topic_functions",
    type: "topic_test",
    title_ar: "اختبار محور الدوال العددية والاشتقاقية",
    title_fr: "Test de chapitre : Fonctions numériques et dérivabilité",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: [
      "math_derivatives_chain_rule",
      "math_intermediate_value_method",
      "math_asymptotes_limits",
      "math_tangent_convexity",
    ],
    questionIds: ["pq-math-chain-01", "pq-math-asymptotes-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_math_topic_exp_ln",
    type: "topic_test",
    title_ar: "اختبار محور الدوال الأسية واللوغاريتمية",
    title_fr: "Test de chapitre : Fonctions exponentielles et logarithmiques",
    subjectId: "math",
    topicId: "math_topic_exp_ln",
    skillIds: [
      "math_exponential_properties_equations",
      "math_logarithm_domain_limits",
    ],
    questionIds: ["pq-math-exp-eq-01", "pq-math-log-limits-01"],
    timeTargetMinutes: 25,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_math_topic_sequences",
    type: "topic_test",
    title_ar: "اختبار محور المتتاليات العددية",
    title_fr: "Test de chapitre : Suites numériques",
    subjectId: "math",
    topicId: "math_topic_sequences",
    skillIds: [
      "math_induction_reasoning",
      "math_sequence_reasoning",
      "math_arithmetic_geometric_auxiliary",
    ],
    questionIds: ["pq-math-induction-01", "pq-math-geom-aux-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_math_topic_probability",
    type: "topic_test",
    title_ar: "اختبار محور الاحتمالات والمتغيرات العشوائية",
    title_fr: "Test de chapitre : Probabilités et variables aléatoires",
    subjectId: "math",
    topicId: "math_topic_probability",
    skillIds: [
      "math_conditional_probability_tree",
    ],
    questionIds: ["pq-math-prob-tree-01"],
    timeTargetMinutes: 20,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // TOPIC TESTS — PHYSIQUE-CHIMIE (5 Topics, 11 Skills)
  // ==========================================================================
  {
    id: "mini_exam_physics_topic_kinetics",
    type: "topic_test",
    title_ar: "اختبار محور المتابعة الزمنية لتحول كيميائي",
    title_fr: "Test de chapitre : Suivi temporel d'une transformation chimique",
    subjectId: "physics",
    topicId: "physics_topic_kinetics",
    skillIds: [
      "physics_reaction_rate_monitoring",
      "physics_redox_titration",
    ],
    questionIds: ["pq-phys-kinetics-01", "pq-phys-titration-01"],
    timeTargetMinutes: 25,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_topic_rc_rl",
    type: "topic_test",
    title_ar: "اختبار محور الظواهر الكهربائية (RC و RL)",
    title_fr: "Test de chapitre : Phénomènes électriques (RC et RL)",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: [
      "physics_rc_time_constant",
      "physics_rc_differential_equation",
      "physics_rl_circuit_response",
    ],
    questionIds: ["pq-phys-rc-01", "pq-phys-rc-diff-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 0, standard: 2, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_topic_nuclear",
    type: "topic_test",
    title_ar: "اختبار محور التحولات النووية",
    title_fr: "Test de chapitre : Transformations nucléaires",
    subjectId: "physics",
    topicId: "physics_topic_nuclear",
    skillIds: [
      "physics_nuclear_decay_law",
      "physics_mass_defect_binding_energy",
    ],
    questionIds: ["pq-phys-decay-01", "pq-phys-mass-defect-01"],
    timeTargetMinutes: 25,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_topic_mechanics",
    type: "topic_test",
    title_ar: "اختبار محور تطور جملة ميكانيكية",
    title_fr: "Test de chapitre : Évolution d'un système mécanique",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    skillIds: [
      "physics_newton_second_law",
      "physics_satellite_kepler",
    ],
    questionIds: ["pq-phys-newton-01", "pq-phys-kepler-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_physics_topic_acid_base_ester",
    type: "topic_test",
    title_ar: "اختبار محور تطور جملة كيميائية نحو التوازن (أحماض وأسس وأسترة)",
    title_fr: "Test de chapitre : Évolution vers l'état d'équilibre (Acides/Bases et Estérification)",
    subjectId: "physics",
    topicId: "physics_topic_acid_base",
    skillIds: [
      "physics_acid_base_ph_ka",
      "physics_esterification_equilibrium",
    ],
    questionIds: ["pq-phys-ph-ka-01", "pq-phys-ester-01"],
    timeTargetMinutes: 25,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // TOPIC TESTS — SCIENCES DE LA NATURE ET DE LA VIE (5 Topics, 10 Skills)
  // ==========================================================================
  {
    id: "mini_exam_snv_topic_synthesis",
    type: "topic_test",
    title_ar: "اختبار محور آليات تركيب البروتين وبنيته الفراغية",
    title_fr: "Test de chapitre : Mécanismes de la biosynthèse protéique et structure",
    subjectId: "natural_sciences",
    topicId: "snv_topic_protein_synthesis",
    skillIds: [
      "snv_protein_synthesis",
      "snv_genetic_code_translation",
      "snv_protein_structure_ionization",
    ],
    questionIds: ["pq-snv-protein-01", "pq-snv-translation-steps-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_snv_topic_enzymology",
    type: "topic_test",
    title_ar: "اختبار محور النشاط الإنزيمي والتخصص الوظيفي",
    title_fr: "Test de chapitre : Activité enzymatique et spécialisation fonctionnelle",
    subjectId: "natural_sciences",
    topicId: "snv_topic_enzymology",
    skillIds: [
      "snv_enzyme_kinetics_active_site",
    ],
    questionIds: ["pq-snv-enzyme-site-01"],
    timeTargetMinutes: 20,
    difficultyProfile: { foundation: 0, standard: 1, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_snv_topic_immunology",
    type: "topic_test",
    title_ar: "اختبار محور التخصص الوظيفي للبروتينات في الدفاع عن الذات (المناعة)",
    title_fr: "Test de chapitre : Immunologie et défense du soi",
    subjectId: "natural_sciences",
    topicId: "snv_topic_immunology",
    skillIds: [
      "snv_immunity_reasoning",
      "snv_cellular_immunity_ltc",
      "snv_hiv_immune_deficiency",
    ],
    questionIds: ["pq-snv-immunity-01", "pq-snv-ltc-cytotoxicity-01"],
    timeTargetMinutes: 35,
    difficultyProfile: { foundation: 1, standard: 2, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_snv_topic_neurophysiology",
    type: "topic_test",
    title_ar: "اختبار محور الاتصال العصبي والمسعى العلمي",
    title_fr: "Test de chapitre : Communication nerveuse et démarche scientifique",
    subjectId: "natural_sciences",
    topicId: "snv_topic_neurophysiology",
    skillIds: [
      "snv_synaptic_transmission",
      "snv_action_potential_ionic_basis",
      "snv_scientific_analysis_method",
    ],
    questionIds: ["pq-snv-synapse-ach-01", "pq-snv-action-potential-01"],
    timeTargetMinutes: 30,
    difficultyProfile: { foundation: 1, standard: 1, advanced: 0 },
    passingScorePercent: 75,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // MULTI-SUBJECT WEEKLY CHECKPOINTS
  // ==========================================================================
  {
    id: "mini_exam_sciences_checkpoint_01",
    type: "weekly_checkpoint",
    title_ar: "المحطة الأسبوعية التراكمية الأولى — مدمجة",
    title_fr: "Checkpoint hebdomadaire 01 : Évaluation entrelacée",
    subjectId: "math",
    skillIds: [
      "math_derivatives_chain_rule",
      "physics_rc_time_constant",
      "snv_protein_synthesis",
    ],
    questionIds: ["pq-math-chain-01", "pq-phys-rc-01", "pq-snv-protein-01"],
    timeTargetMinutes: 45,
    difficultyProfile: { foundation: 1, standard: 2, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "mini_exam_sciences_checkpoint_02",
    type: "weekly_checkpoint",
    title_ar: "المحطة الأسبوعية التراكمية الثانية — الميكانيك والمتتاليات والمناعة",
    title_fr: "Checkpoint hebdomadaire 02 : Suites, Mécanique et Immunité",
    subjectId: "physics",
    skillIds: [
      "math_induction_reasoning",
      "physics_newton_second_law",
      "snv_cellular_immunity_ltc",
    ],
    questionIds: ["pq-math-induction-01", "pq-phys-newton-01", "pq-snv-ltc-cytotoxicity-01"],
    timeTargetMinutes: 45,
    difficultyProfile: { foundation: 1, standard: 2, advanced: 0 },
    passingScorePercent: 70,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
