/**
 * BAC Mastery — Official Past BAC Exam References (Sciences Expérimentales 3AS)
 * Prompt 13: Metadata-only citations for all 31 supported skills (ONEC official archives)
 * 
 * Invariant: Content Purity (ZERO user_id). Fair use metadata citation without verbatim reproduction.
 */

import { PastBacExamReference } from "./types";

export const PROMPT11_PAST_BAC_REFERENCES: PastBacExamReference[] = [
  // ==========================================================================
  // MATHEMATICS (10 Skills)
  // ==========================================================================
  {
    id: "bac_ref_math_chain_rule",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: ["math_derivatives_chain_rule"],
    exerciseNumber: 2,
    subQuestionRef: "Partie B - Question 2.a",
    title_ar: "بكالوريا 2023 — رياضيات — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2023 — Mathématiques — Sujet 1 — Exercice 2",
    description_ar: "دراسة دالة أسية مركبة، حساب الدالة المشتقة باستعمال قاعدة السلسلة وتحديد إشارتها بدقة.",
    description_fr: "Étude d'une fonction exponentielle composée, calcul de dérivée via la règle de chaîne et étude du signe.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "انتبه إلى إشارة المشتقة u'(x) عند اشتقاق e^(-2x) وتجنب خطأ نسيان العامل السالب.",
    guidanceNotes_fr: "Attention au signe de la dérivée intérieure lors de la dérivation de e^(-2x).",
  },
  {
    id: "bac_ref_math_tvi",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: ["math_intermediate_value_method"],
    exerciseNumber: 2,
    subQuestionRef: "Partie A - Question 3",
    title_ar: "بكالوريا 2022 — رياضيات — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2022 — Mathématiques — Sujet 1 — Exercice 2",
    description_ar: "إثبات وجود حل وحيد ألفا للمعادلة g(x) = 0 بمبرهنة القيم المتوسطة وتحديد حصر له بسعة 10^-2.",
    description_fr: "Existence et unicité d'une solution alpha pour g(x)=0 via le TVI et encadrement à 10^-2.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "اذكر صراحة شرط الاستمرار والرتابة التامة على المجال قبل الاستنتاج.",
    guidanceNotes_fr: "Justifiez explicitement la continuité et la stricte monotonie sur l'intervalle.",
  },
  {
    id: "bac_ref_math_asymptotes",
    year: 2021,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: ["math_asymptotes_limits"],
    exerciseNumber: 3,
    subQuestionRef: "Partie B - Question 1",
    title_ar: "بكالوريا 2021 — رياضيات — الموضوع الثاني — التمرين الثالث",
    title_fr: "BAC 2021 — Mathématiques — Sujet 2 — Exercice 3",
    description_ar: "حساب النهايات عند أطراف مجال التعريف واستنتاج معادلات المستقيمات المقاربة الأفقية والمائلة.",
    description_fr: "Calcul des limites aux bornes et détermination des asymptotes horizontales et obliques.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "لا تنس كتابة 'بجوار +مالانهاية أو -مالانهاية' عند ذكر المستقيمات المقاربة.",
    guidanceNotes_fr: "Précisez toujours le voisinage (+∞ ou -∞) pour les asymptotes.",
  },
  {
    id: "bac_ref_math_tangent",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_functions",
    skillIds: ["math_tangent_convexity"],
    exerciseNumber: 3,
    subQuestionRef: "Partie B - Question 3.b",
    title_ar: "بكالوريا 2023 — رياضيات — الموضوع الثاني — التمرين الثالث",
    title_fr: "BAC 2023 — Mathématiques — Sujet 2 — Exercice 3",
    description_ar: "كتابة معادلة المماس عند نقطة الانعطاف ودراسة الوضع النسبي بين المنحنى والمماس.",
    description_fr: "Équation de tangente au point d'inflexion et position relative courbe/tangente.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "انتبه لأقواس الطرح عند حساب الفرق f(x) - y لتفادي خطأ الإشارة في الوضع النسبي.",
    guidanceNotes_fr: "Conservez les parenthèses lors du calcul de la différence f(x) - y.",
  },
  {
    id: "bac_ref_math_exp_eq",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_exp_ln",
    skillIds: ["math_exponential_properties_equations"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء 1",
    title_ar: "بكالوريا 2022 — رياضيات — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2022 — Mathématiques — Sujet 2 — Exercice 2",
    description_ar: "حل معادلة أسية من الدرجة الثانية بتغيير المتغير X = e^x واستبعاد الحلول السالبة.",
    description_fr: "Résolution d'une équation exponentielle par changement de variable X = e^x et rejet des racines négatives.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "اشترط دوماً X > 0 قبل حل المعادلة بالمميز دلتا.",
    guidanceNotes_fr: "Posez rigoureusement la condition X > 0 avant de résoudre.",
  },
  {
    id: "bac_ref_math_log_limits",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_exp_ln",
    skillIds: ["math_logarithm_domain_limits"],
    exerciseNumber: 3,
    subQuestionRef: "Partie A - Question 1",
    title_ar: "بكالوريا 2024 — رياضيات — الموضوع الأول — التمرين الثالث",
    title_fr: "BAC 2024 — Mathématiques — Sujet 1 — Exercice 3",
    description_ar: "تعيين مجموعة تعريف دالة لوغاريتمية مركبة وحساب النهايات باستخدام التزايد المقارن.",
    description_fr: "Domaine de définition d'une fonction logarithmique composée et limites par croissances comparées.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "استخرج العامل المشترك x عند حساب النهاية لإظهار النهاية الشهيرة ln(x)/x.",
    guidanceNotes_fr: "Factorisez par x pour faire apparaître la limite usuelle ln(x)/x.",
  },
  {
    id: "bac_ref_math_induction",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_sequences",
    skillIds: ["math_induction_reasoning"],
    exerciseNumber: 2,
    subQuestionRef: "السؤال 1",
    title_ar: "بكالوريا 2023 — رياضيات — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2023 — Mathématiques — Sujet 2 — Exercice 2",
    description_ar: "البرهان بالتراجع على حصر متتالية عددية تراجعية وفق الصياغة المنهجية الرسمية.",
    description_fr: "Démonstration par récurrence d'un encadrement de suite récurrente.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "احرص على الصياغة الصارمة لمرحلة الوراثة: نفرض صحة P(n) ونبرهن صحة P(n+1).",
    guidanceNotes_fr: "Rédigez rigoureusement : supposons P(n) vraie et démontrons P(n+1).",
  },
  {
    id: "bac_ref_math_sequences",
    year: 2021,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_sequences",
    skillIds: ["math_sequence_reasoning"],
    exerciseNumber: 2,
    subQuestionRef: "السؤال 2",
    title_ar: "بكالوريا 2021 — رياضيات — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2021 — Mathématiques — Sujet 1 — Exercice 2",
    description_ar: "دراسة اتجاه تغير متتالية عبر إشارة الفرق u_(n+1) - u_n واستنتاج تقاربها بالرتابة والمحدودية.",
    description_fr: "Étude du sens de variation par le signe de u_(n+1) - u_n et convergence monotone.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "المتتالية المتزايدة يجب أن تكون محدودة من الأعلى لتتقارب.",
    guidanceNotes_fr: "Une suite croissante doit être majorée pour converger.",
  },
  {
    id: "bac_ref_math_geom_aux",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_sequences",
    skillIds: ["math_arithmetic_geometric_auxiliary"],
    exerciseNumber: 3,
    subQuestionRef: "السؤال 3 و 4",
    title_ar: "بكالوريا 2022 — رياضيات — الموضوع الأول — التمرين الثالث",
    title_fr: "BAC 2022 — Mathématiques — Sujet 1 — Exercice 3",
    description_ar: "إثبات أن متتالية مساعدة هندسية وكتابة حدها العام واستنتاج مجموع حدود متتابعة.",
    description_fr: "Preuve de suite géométrique auxiliaire, terme général et calcul de somme de termes.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "انتبه لعدد الحدود في المجموع: عدد الحدود = دليل النهاية - دليل البداية + 1.",
    guidanceNotes_fr: "Vérifiez le nombre de termes de la somme : (n_fin - n_debut + 1).",
  },
  {
    id: "bac_ref_math_prob_tree",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "math",
    topicId: "math_topic_probability",
    skillIds: ["math_conditional_probability_tree"],
    exerciseNumber: 1,
    subQuestionRef: "الأسئلة 1 إلى 3",
    title_ar: "بكالوريا 2024 — رياضيات — الموضوع الثاني — التمرين الأول",
    title_fr: "BAC 2024 — Mathématiques — Sujet 2 — Exercice 1",
    description_ar: "شجرة احتمالات متوازنة، قانون الاحتمال الكلي وحساب الاحتمال الشرطي العكسي بدستور بايز.",
    description_fr: "Arbre pondéré, formule des probabilités totales et calcul de probabilité conditionnelle inverse.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Math BAC Mastery",
    guidanceNotes_ar: "انتبه لما يلي عبارة 'علماً أن' فهو الشرط الذي يوضع في مقام الكسر.",
    guidanceNotes_fr: "Ce qui suit 'sachant que' constitue la condition et se place au dénominateur.",
  },

  // ==========================================================================
  // PHYSIQUE-CHIMIE (11 Skills)
  // ==========================================================================
  {
    id: "bac_ref_phys_kinetics",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_kinetics",
    skillIds: ["physics_reaction_rate_monitoring"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 4",
    title_ar: "بكالوريا 2023 — فيزياء — الموضوع الثاني — التمرين الأول",
    title_fr: "BAC 2023 — Physique — Sujet 2 — Exercice 1",
    description_ar: "متابعة زمنية لتحول كيميائي بطريقة قياس الحجم، حساب سرعة التفاعل بيانيا وتحديد زمن نصف التفاعل t1/2.",
    description_fr: "Suivi temporel d'une transformation chimique par volumétrie, calcul de vitesse volumique et t1/2.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "لا تنس قسمة ميل المماس على الحجم الكلي للمزيج التفاعلي V_tot عند حساب السرعة الحجمية.",
    guidanceNotes_fr: "N'oubliez pas de diviser la pente de la tangente par le volume total du mélange réactionnel.",
  },
  {
    id: "bac_ref_phys_titration",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_kinetics",
    skillIds: ["physics_redox_titration"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 3",
    title_ar: "بكالوريا 2022 — فيزياء — الموضوع الثاني — التمرين الأول",
    title_fr: "BAC 2022 — Physique — Sujet 2 — Exercice 1",
    description_ar: "معايرة لونية أكسدة-إرجاع لشوارد الحديد الثنائي بالبرمنغنات وتعيين التركيز عند نقطة التكافؤ.",
    description_fr: "Titrage redox des ions fer II par le permanganate et calcul de concentration à l'équivalence.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "احرص على موازنة المعاملات الستوكيومترية في علاقة التكافؤ n1/a = n2/b.",
    guidanceNotes_fr: "Veillez aux coefficients stœchiométriques dans la relation d'équivalence.",
  },
  {
    id: "bac_ref_phys_rc_time",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: ["physics_rc_time_constant"],
    exerciseNumber: 1,
    subQuestionRef: "Partie 1 - Question 3",
    title_ar: "بكالوريا 2022 — فيزياء — الموضوع الأول — التمرين الأول",
    title_fr: "BAC 2022 — Physique — Sujet 1 — Exercice 1",
    description_ar: "استثمار المنحنى البياني لتطور التوتر بين طرفي المكثفة واستنتاج سعة المكثفة C من قيمة ثابت الزمن tau.",
    description_fr: "Exploitation graphique de la tension aux bornes du condensateur et déduction de la capacité C.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "تأكد من تحويل المقاومة إلى الأوم (Ohm) وثابت الزمن إلى الثانية (s) للحصول على السعة بالفاراد (F).",
    guidanceNotes_fr: "Veillez à convertir la résistance en Ohms et tau en secondes pour obtenir C en Farads.",
  },
  {
    id: "bac_ref_phys_rc_diff",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: ["physics_rc_differential_equation"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 2",
    title_ar: "بكالوريا 2023 — فيزياء — الموضوع الأول — التمرين الأول",
    title_fr: "BAC 2023 — Physique — Sujet 1 — Exercice 1",
    description_ar: "تأسيس المعادلة التفاضلية لتوتر المكثفة u_C أثناء الشحن والتفريغ والتحقق من حلها الأسي.",
    description_fr: "Établissement de l'équation différentielle en tension u_C en charge/décharge et vérification de la solution.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "في التفريغ لا يوجد مولد في الدارة، إذن الطرف الثاني للمعادلة يساوي صفراً.",
    guidanceNotes_fr: "En décharge, le second membre de l'équation différentielle est nul.",
  },
  {
    id: "bac_ref_phys_rl",
    year: 2021,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    skillIds: ["physics_rl_circuit_response"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 3",
    title_ar: "بكالوريا 2021 — فيزياء — الموضوع الأول — التمرين الأول",
    title_fr: "BAC 2021 — Physique — Sujet 1 — Exercice 1",
    description_ar: "دراسة استجابة ثنائي القطب RL لتدرج توتر واستخراج ذاتية الوشيعة ومقاومتها الداخلية.",
    description_fr: "Réponse d'un dipôle RL à un échelon de tension, constante de temps et résistance interne.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "المقاومة الكلية للدارة هي مجموع مقاومة الناقل الأومي ومقاومة الوشيعة: R_tot = R + r.",
    guidanceNotes_fr: "La résistance totale est la somme R_tot = R + r.",
  },
  {
    id: "bac_ref_phys_decay",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_nuclear",
    skillIds: ["physics_nuclear_decay_law"],
    exerciseNumber: 2,
    subQuestionRef: "السؤال 2",
    title_ar: "بكالوريا 2023 — فيزياء — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2023 — Physique — Sujet 1 — Exercice 2",
    description_ar: "قانون التناقص الإشعاعي وحساب النشاط الإشعاعي A وتطبيق ذلك في تأريخ صخرة قديمة.",
    description_fr: "Loi de décroissance radioactive, activité A(t) et datation d'une roche ancienne.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "لحساب النشاط بالبيكريل (Bq) يجب أن يكون ثابت النشاط معبراً عنه بـ s^-1.",
    guidanceNotes_fr: "Pour A en Bq, la constante lambda doit être impérativement en s^-1.",
  },
  {
    id: "bac_ref_phys_mass_defect",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_nuclear",
    skillIds: ["physics_mass_defect_binding_energy"],
    exerciseNumber: 2,
    subQuestionRef: "السؤال 3",
    title_ar: "بكالوريا 2022 — فيزياء — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2022 — Physique — Sujet 1 — Exercice 2",
    description_ar: "حساب النقص الكتلي وطاقة الربط E_l واستغلال منحنى أستون لمقارنة استقرار الأنوية.",
    description_fr: "Calcul de défaut de masse, énergie de liaison et courbe d'Aston pour la stabilité nucléaire.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "النواة الأكثر استقراراً هي التي تملك أكبر طاقة ربط لكل نوية E_l / A.",
    guidanceNotes_fr: "Le critère de stabilité est l'énergie de liaison par nucléon E_l / A maximale.",
  },
  {
    id: "bac_ref_phys_newton",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    skillIds: ["physics_newton_second_law"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء 1 - السؤال 2",
    title_ar: "بكالوريا 2024 — فيزياء — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2024 — Physique — Sujet 1 — Exercice 2",
    description_ar: "تطبيق القانون الثاني لنيوتن على حركة جسم فوق مستوٍ مائل بزاوية alpha وحساب قوة الاحتكاك.",
    description_fr: "Application de la 2e loi de Newton sur plan incliné et détermination des frottements.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "مركبة الثقل الموازية للمستوي المائل تأخذ sin(alpha) لأنها المقابل للزاوية في مثلث القوى.",
    guidanceNotes_fr: "La composante du poids le long du plan incliné est P·sin(alpha).",
  },
  {
    id: "bac_ref_phys_kepler",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    skillIds: ["physics_satellite_kepler"],
    exerciseNumber: 2,
    subQuestionRef: "الأسئلة 1 إلى 3",
    title_ar: "بكالوريا 2023 — فيزياء — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2023 — Physique — Sujet 2 — Exercice 2",
    description_ar: "حركة قمر اصطناعي في مدار دائري في المرجع الجيومركزي، حساب السرعة والدور وإثبات كبلر 3.",
    description_fr: "Mouvement circulaire d'un satellite en repère géocentrique, vitesse orbitale et 3e loi de Kepler.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "انتبه لنصف قطر المدار r = R_T + h مع تحويل الكيلومتر إلى أمتار.",
    guidanceNotes_fr: "Le rayon orbital est r = R_T + h à convertir impérativement en mètres.",
  },
  {
    id: "bac_ref_phys_ph_ka",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_acid_base",
    skillIds: ["physics_acid_base_ph_ka"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء 2",
    title_ar: "بكالوريا 2024 — فيزياء — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2024 — Physique — Sujet 2 — Exercice 2",
    description_ar: "دراسة حمض كربوكسيلي ضعيف، حساب نسبة التقدم النهائي tau_f وثابت الحموضة Ka ومخطط الصفة الغالبة.",
    description_fr: "Étude d'un acide faible, taux d'avancement final tau_f, constante Ka et prédominance.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "الماء مذيب كيميائي يؤخذ تركيزه اصطلاحاً مساوياً لـ 1 في عبارة كسر التوازن ولا يكتب.",
    guidanceNotes_fr: "L'eau étant solvant, son activité est conventionnellement égale à 1 dans Ka.",
  },
  {
    id: "bac_ref_phys_ester",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "physics",
    topicId: "physics_topic_esterification",
    skillIds: ["physics_esterification_equilibrium"],
    exerciseNumber: 2,
    subQuestionRef: "الأسئلة 1 إلى 4",
    title_ar: "بكالوريا 2022 — فيزياء — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2022 — Physique — Sujet 2 — Exercice 2",
    description_ar: "تفاعل أسترة مزيج متساوي المولات، حساب المردود r وتحديد صنف الكحول وحساب ثابت التوازن K.",
    description_fr: "Estérification d'un mélange équimolaire, rendement r, classe d'alcool et constante K.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité Physique BAC Mastery",
    guidanceNotes_ar: "في تفاعل الأسترة يدخل الماء حتماً في بسط عبارة ثابت التوازن K ولا يعتبر مذيباً بوفـرة.",
    guidanceNotes_fr: "Dans l'estérification, l'eau figure obligatoirement au numérateur de la constante K.",
  },

  // ==========================================================================
  // SCIENCES DE LA NATURE ET DE LA VIE (10 Skills)
  // ==========================================================================
  {
    id: "bac_ref_snv_transcription",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_protein_synthesis",
    skillIds: ["snv_protein_synthesis"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء الأول - السؤال 1",
    title_ar: "بكالوريا 2023 — علوم طبيعية — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2023 — SVT — Sujet 1 — Exercice 2",
    description_ar: "تحليل تجربة تثبيط إنزيم ARN بوليميراز بمادة الألفا-أمانيتين وتفسير تأثيرها على تركيب البروتين.",
    description_fr: "Analyse de l'inhibition de l'ARN polymérase par l'alpha-amanitine et son impact sur la biosynthèse.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "وظف المنهجية المبنية على التحليل المقارن (معطيات السند + الدلالة) ثم الخروج باستنتاج واضح.",
    guidanceNotes_fr: "Appliquez la démarche scientifique : analyse des données puis déduction ciblée.",
  },
  {
    id: "bac_ref_snv_translation",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_protein_synthesis",
    skillIds: ["snv_genetic_code_translation"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 1 و 2",
    title_ar: "بكالوريا 2024 — علوم طبيعية — الموضوع الأول — التمرين الأول",
    title_fr: "BAC 2024 — SVT — Sujet 1 — Exercice 1",
    description_ar: "مراحل الترجمة في الهيولى، رسم تخطيطي وظيفي لمعقد الانطلاق ودور الرامزات.",
    description_fr: "Étapes de la traduction, schéma fonctionnel du complexe d'initiation et rôle des codons.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "رامزات التوقف الثلاث لا تشفر لأي حمض أميني وتؤدي لتفكك معقد الترجمة فقط.",
    guidanceNotes_fr: "Les codons stop ne codent pour aucun acide aminé et déclenchent la dissociation.",
  },
  {
    id: "bac_ref_snv_amino_structure",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_protein_structure",
    skillIds: ["snv_protein_structure_ionization"],
    exerciseNumber: 1,
    subQuestionRef: "السؤال 2",
    title_ar: "بكالوريا 2022 — علوم طبيعية — الموضوع الأول — التمرين الأول",
    title_fr: "BAC 2022 — SVT — Sujet 1 — Exercice 1",
    description_ar: "الهجرة الكهربائية للأحماض الأمينية عند درجات pH مختلفة وسلوكها الحمقلي وتأين الجذور.",
    description_fr: "Électrophorèse des acides aminés à différents pH, comportement amphotère et ionisation.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "الشحنة السالبة تنجذب نحو القطب الموجب (المصعد) والموجبة نحو المهبط السالب.",
    guidanceNotes_fr: "Les charges négatives migrent vers l'anode positive et les positives vers la cathode négative.",
  },
  {
    id: "bac_ref_snv_enzymes",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_enzymology",
    skillIds: ["snv_enzyme_kinetics_active_site"],
    exerciseNumber: 1,
    subQuestionRef: "الأسئلة 1 إلى 3",
    title_ar: "بكالوريا 2023 — علوم طبيعية — الموضوع الثاني — التمرين الأول",
    title_fr: "BAC 2023 — SVT — Sujet 2 — Exercice 1",
    description_ar: "دراسة تأثير درجة الحرارة على الموقع الفعال وتشبع الإنزيم بالركيزة والتكامل المحفز.",
    description_fr: "Influence de la température sur le site actif, saturation du substrat et ajustement induit.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "ميز بين التثبيط العكوس بالبرودة والتخريب غير العكوس بالحرارة المرتفعة.",
    guidanceNotes_fr: "Distinguez l'inactivation réversible par le froid de la dénaturation thermique irréversible.",
  },
  {
    id: "bac_ref_snv_immunity_humoral",
    year: 2021,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_immunology",
    skillIds: ["snv_immunity_reasoning"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء 2",
    title_ar: "بكالوريا 2021 — علوم طبيعية — الموضوع الثاني — التمرين الثاني",
    title_fr: "BAC 2021 — SVT — Sujet 2 — Exercice 2",
    description_ar: "الاستجابة المناعية الخلطية، تشكل المعقدات المناعية وتسهيل بلعمتها بواسطة البالعات الكبيرة.",
    description_fr: "Immunité humorale, formation des complexes immuns et facilitation de la phagocytose.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "الأجسام المضادة تبطل مفعول المستضد فقط ولا تهضمه؛ البلعمة تتكفل بالإقصاء النهائي.",
    guidanceNotes_fr: "Les anticorps neutralisent l'antigène mais c'est la phagocytose qui assure la destruction.",
  },
  {
    id: "bac_ref_snv_cellular_ltc",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_immunology",
    skillIds: ["snv_cellular_immunity_ltc"],
    exerciseNumber: 3,
    subQuestionRef: "الجزء الثاني",
    title_ar: "بكالوريا 2022 — علوم طبيعية — الموضوع الثاني — التمرين الثالث",
    title_fr: "BAC 2022 — SVT — Sujet 2 — Exercice 3",
    description_ar: "استدلال علمي متكامل حول الاستجابة المناعية النوعية الخلوية وآلية إفراز البيرفورين والغرانزيم من طرف LTc.",
    description_fr: "Démarche scientifique sur la réponse immunitaire cellulaire et le mécanisme de cytotoxicité des LTc.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "استغل وثائق التجارب بدقة (تحليل + استنتاج) ثم ركب الإجابة في نص علمي مهيكل وواضح.",
    guidanceNotes_fr: "Exploitez rigoureusement les documents (analyse + déduction) puis synthétisez.",
  },
  {
    id: "bac_ref_snv_hiv",
    year: 2023,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_immunology",
    skillIds: ["snv_hiv_immune_deficiency"],
    exerciseNumber: 3,
    subQuestionRef: "الجزء 2",
    title_ar: "بكالوريا 2023 — علوم طبيعية — الموضوع الأول — التمرين الثالث",
    title_fr: "BAC 2023 — SVT — Sujet 1 — Exercice 3",
    description_ar: "دورة حياة فيروس السيدا وتأثير تراجع اللمفاويات LT4 على انقطاع إنترلوكين 2 والعجز المناعي الشامل.",
    description_fr: "Cycle du VIH, déplétion des LT4, interruption de l'interleukine 2 et effondrement immunitaire.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "تناقص الأجسام المضادة في السيدا سببه انقطاع تحفيز IL-2 من LT4 وليس إصابة مباشرة لـ LB.",
    guidanceNotes_fr: "La chute des anticorps résulte du manque d'IL-2 issu des LT4 et non d'une infection directe des LB.",
  },
  {
    id: "bac_ref_snv_synapse",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_neurophysiology",
    skillIds: ["snv_synaptic_transmission"],
    exerciseNumber: 3,
    subQuestionRef: "الجزء 1 و 2",
    title_ar: "بكالوريا 2024 — علوم طبيعية — الموضوع الثاني — التمرين الثالث",
    title_fr: "BAC 2024 — SVT — Sujet 2 — Exercice 3",
    description_ar: "النقل المشبكي الكيميائي وتأثير سم عصبي يثبت على مستقبلات الأستيل كولين بعد المشبكية.",
    description_fr: "Transmission synaptique chimique et action d'une neurotoxine bloquant les récepteurs nicotiniques.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "قنوات الغشاء بعد المشبكي كيميائية تفتح بالمبلغ الكيميائي فقط، وليست قنوات فولطية.",
    guidanceNotes_fr: "Les récepteurs postsynaptiques sont chimiodépendants et non voltagedépendants.",
  },
  {
    id: "bac_ref_snv_action_potential",
    year: 2022,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_neurophysiology",
    skillIds: ["snv_action_potential_ionic_basis"],
    exerciseNumber: 2,
    subQuestionRef: "السؤال 2",
    title_ar: "بكالوريا 2022 — علوم طبيعية — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2022 — SVT — Sujet 1 — Exercice 2",
    description_ar: "الأساس الأيوني لكمون الراحة (-70 mV) وكمون العمل وتدخل مضخة Na+/K+ والقنوات الفولطية.",
    description_fr: "Bases ioniques du potentiel de repos (-70 mV) et d'action : canaux de fuite, pompe Na+/K+ et canaux voltage-dépendants.",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "فرط الاستقطاب ناتج عن تأخر انغلاق قنوات K+ المرتبطة بالفولطية.",
    guidanceNotes_fr: "L'hyperpolarisation est due au retard de fermeture des canaux K+ voltage-dépendants.",
  },
  {
    id: "bac_ref_snv_method",
    year: 2024,
    session: "principal",
    streamId: "sciences_exp",
    subjectId: "natural_sciences",
    topicId: "snv_topic_neurophysiology",
    skillIds: ["snv_scientific_analysis_method"],
    exerciseNumber: 2,
    subQuestionRef: "الجزء 1 و 2",
    title_ar: "بكالوريا 2024 — علوم طبيعية — الموضوع الأول — التمرين الثاني",
    title_fr: "BAC 2024 — SVT — Sujet 1 — Exercice 2",
    description_ar: "استغلال سندات تجريبية وفق منهجية المسعى العلمي (تقديم، تحليل دقيق، استنتاج وتركيب).",
    description_fr: "Exploitation de documents expérimentaux selon la démarche scientifique (analyse, déduction, synthèse).",
    sourceId: "src-onec-past-exams-archive",
    sourceType: "official_exam",
    officialExamSourceId: "src-onec-past-exams-archive",
    rightsStatus: "official_reference",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    verifiedAt: "2024-09-01T10:00:00Z",
    verifiedBy: "Comité SVT BAC Mastery",
    guidanceNotes_ar: "احرص على ألا تخلو أي خطوة استغلال وثيقة من استنتاج مستقل يجيب عن مشكل السند.",
    guidanceNotes_fr: "Chaque document analysé doit déboucher sur une conclusion indépendante explicite.",
  },
];
