/**
 * BAC Mastery — Study Methods Catalog
 * Prompt 12: Actionable practical study execution guides for BAC candidates
 * 
 * Invariant: Content Purity (ZERO user_id).
 */

import { StudyMethod } from "./types";

export const PROMPT12_STUDY_METHODS: StudyMethod[] = [
  {
    id: "sm_01_reading_lesson",
    title_ar: "بروتوكول قراءة درس جديد في المواد العلمية",
    title_fr: "Protocole de lecture active d'un nouveau cours",
    category: "reading",
    problemAddressed_ar: "القراءة السلبية للملخصات وتظليل الصفحات دون فهم حقيقي أو قدرة على حل التمارين.",
    practicalSteps_ar: [
      "تصفح العناوين والنتائج الرئيسية لمدة دقيقتين فقط لتحديد الإطار العام.",
      "تحديد المشكلة العلمية التي يحاول الدرس حلها.",
      "قراءة الفكرة المحورية وإغلاق الكراس فوراً وشرحها بكلماتك البسيطة بدون نظر.",
      "دراسة المثال المحلول لفهم منطق الخطوات وليس لحفظ الأرقام.",
      "الانتقال المباشر لحل تمرين تطبيقي مصغر دون إعادة قراءة النص.",
    ],
    exampleScenario_ar: "تلميذ يقرأ درس الاشتقاقية؛ بدلاً من قراءة 10 صفحات، يقرأ قاعدة السلسلة ويغلق الدفتر ويشتق دالة أسية فوراً.",
    commonTrap_ar: "إعادة قراءة الدرس 4 مرات وتظليله بأقلام ملونة للاطمئنان الوهمي.",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_02_memorization",
    title_ar: "بروتوكول حفظ القوانين والتعاريف بالاسترجاع الفعال",
    title_fr: "Mémorisation active des formules et définitions par rappel libre",
    category: "memorization",
    problemAddressed_ar: "نسيان القوانين والوحدات والشروط التجريبية أثناء حل التمارين في الامتحان.",
    practicalSteps_ar: [
      "فهم دلالة كل رمز في القانون ووحدته في النظام الدولي (مثل C بالفاراد و U بالفولت).",
      "كتابة القانون على ورقة بيضاء فارغة تماماً دون أي مساعدة.",
      "مقارنة ما كتبته بالمرجع وتصحيح أي نقص أو إشارة فوراً.",
      "إعادة استرجاع القانون بعد 4 ساعات، ثم في اليوم الموالي، ثم بعد 3 أيام (الاسترجاع المتباعد).",
      "طرح السؤال التطبيقي: متى ينعدم هذا المقدار ومتى يبلغ قيمته العظمى؟",
    ],
    exampleScenario_ar: "حفظ قانون التناقص الإشعاعي N(t) = N0 * e^(-lambda * t) مع كتابة وحدة ثابت النشاط s^-1.",
    commonTrap_ar: "ترديد القانون شفهياً 30 مرة دون كتابته على ورقة بيضاء.",
    estimatedMinutes: 10,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_03_revision",
    title_ar: "بروتوكول المراجعة الذكية عبر التفريغ الذهني",
    title_fr: "Révision ciblée par vidage cérébral et comblement de lacunes",
    category: "revision",
    problemAddressed_ar: "البدء دائماً من الصفحة الأولى وتكرار ما هو معروف وإضاعة وقت المراجعة.",
    practicalSteps_ar: [
      "أخذ ورقة بيضاء وكتابة كل ما تتذكره عن المحور خلال 7 دقائق (Brain Dump).",
      "مقارنة المكتوب بفهرس المحور الرسمي وتسطير النقاط المنسية فقط.",
      "مراجعة النقطة المنسية فقط لمدة 10 دقائق مركزة.",
      "حل تمرين فوري يستهدف تلك النقطة المحددة.",
    ],
    exampleScenario_ar: "مراجعة المتتاليات: كتابة قوانين الحسابية والهندسية، اكتشاف نسيان مجموع الهندسية، مراجعته وحل مجموع واحد فوراً.",
    commonTrap_ar: "إعادة قراءة كراس الفصل الأول كاملاً للشعور بالراحة النفسية.",
    estimatedMinutes: 20,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_04_problem_solving",
    title_ar: "بروتوكول حل تمرين البكالوريا خطوة بخطوة",
    title_fr: "Résolution méthodique d'un exercice type Baccalauréat",
    category: "problem_solving",
    problemAddressed_ar: "التسرع والقفز للحل دون استيعاب الشروط الابتدائية وضياع نقاط المنهجية.",
    practicalSteps_ar: [
      "قراءة تحليلية لنص التمرين لـ 3 دقائق مع التسطير على المعطيات والشروط الابتدائية.",
      "تحويل جميع الوحدات فوراً إلى الوحدات الدولية الأساسية.",
      "رسم تخطيطي توضيحي (قوى، دارة كهربائية، أو تغيرات).",
      "ذكر اسم القانون أو المبرهنة المعتمدة وتبرير شروط تطبيقها قبل الحساب.",
      "كتابة العبارة الحرفية أولاً، ثم التطبيق العددي، ثم تأطير النتيجة مع الوحدة.",
      "التحقق من المعقولية الفيزيائية أو الرياضية للنتيجة.",
    ],
    exampleScenario_ar: "حل مسألة سقوط شاقولي: تحديد المرجع الغاليلي، تمثيل الثقل والاحتكاك، تطبيق القانون الثاني لنيوتن، واستخراج المعادلة التفاضلية.",
    commonTrap_ar: "الضغط على أزرار الآلة الحاسبة قبل كتابة القانون الحرفي المبرر على ورقة الإجابة.",
    estimatedMinutes: 25,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_05_comprehension_check",
    title_ar: "بروتوكول التحقق من الفهم الحقيقي (تقنية فاينمان)",
    title_fr: "Validation de la compréhension profonde (Technique de Feynman)",
    category: "problem_solving",
    problemAddressed_ar: "الوهم المعرفي (Illusion of competence) والاعتقاد بفهم الدرس بعد مشاهدة فيديو شرح.",
    practicalSteps_ar: [
      "شرح الفكرة العلمية لشخص مبتدئ أو لجدار الغرفة بلغة بسيطة دون فتح الدفتر.",
      "الامتناع الصارم عن استخدام الكلمات التقنية المعقدة دون تفسيرها.",
      "التوقف عند أول نقطة تجد نفسك فيها تقول 'هكذا هي القاعدة' لأنها نقطة الضعف.",
      "حل مسألة غير مألوفة تم فيها تغيير المجهول لاختبار الفهم الحقيقي.",
    ],
    exampleScenario_ar: "شرح سبب كون توتر المكثفة مستمراً بينما شدة التيار تنقطع فجأة بالاعتماد على حركة الشحنات وتراكمها.",
    commonTrap_ar: "الاكتفاء بقول 'نعم هذا واضح وسهل' أثناء مشاهدة حل الأستاذ في اليوتيوب.",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_06_managing_hard_problems",
    title_ar: "بروتوكول التعامل مع التمارين الصعبة والمستعصية",
    title_fr: "Gestion des blocages et résolution de problèmes complexes",
    category: "problem_solving",
    problemAddressed_ar: "الإحباط السريع والاستسلام أو إضاعة 3 ساعات أمام سؤال واحد دون تقدم.",
    practicalSteps_ar: [
      "المقاومة الذهنية المركزة لمدة 7 دقائق على ورقة مسودة مع إعادة قراءة الأسئلة السابقة.",
      "تفكيك السؤال إلى: ما المعطيات؟ ما المطلوب بدقة؟ ما العلاقة الرياضية الجامعة؟",
      "إذا استعصى السؤال تماماً، إلقاء نظرة واحدة على الخطوة الأولى فقط في الحل، ثم إغلاقه وإكمال الحل ذاتياً.",
      "تدوين سبب التوقف المحدد في كراس الأخطاء لتفاديه مستقبلاً.",
    ],
    exampleScenario_ar: "التوقف أمام إيجاد نقطة انعطاف لمنحنى؛ مراجعة أن المشتقة الثانية تنعدم وتغير إشارتها، ثم إكمال الحساب.",
    commonTrap_ar: "فتح الحل الكامل بعد دقيقة واحدة من التفكير، أو الاستمرار في التحديق في الورقة لساعات.",
    estimatedMinutes: 20,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_07_error_repair",
    title_ar: "بروتوكول تصحيح الخطأ وترسيخ الفهم المنهجي",
    title_fr: "Protocole de remédiation d'erreur et capitalisation d'apprentissage",
    category: "error_repair",
    problemAddressed_ar: "تكرار نفس الأخطاء الحسابية والمنهجية في كل اختبار رسمي.",
    practicalSteps_ar: [
      "إيقاف لوم النفس والتعامل مع الخطأ كمعلومة تقنية ثمينة.",
      "تشخيص نوع الخطأ بدقة من تصنيف Error Lab (نسيان، سوء فهم، خطأ حسابي، سوء قراءة).",
      "إعادة حل السؤال بالكامل على ورقة بيضاء نظيفة من البداية.",
      "كتابة قاعدة منع شخصية في جملة واحدة في كراس الأخطاء.",
      "إجراء اختبار توأم Retest بعد 48 ساعة للتأكد من زوال الخطأ.",
    ],
    exampleScenario_ar: "الخطأ في إشارة المشتقة؛ كتابة قاعدة 'سأضع مشتقة الأس بين قوسين أولاً'، وإعادة حل المسألة بعد يومين بنجاح.",
    commonTrap_ar: "وضع علامة خطأ بالقلم الأحمر والمرور إلى التمرين التالي دون إعادة الحل من الصفر.",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_08_weekly_checkpoint",
    title_ar: "بروتوكول المراجعة الأسبوعية والمحطة الدورية",
    title_fr: "Checkpoint hebdomadaire et consolidation entrelacée",
    category: "weekly_review",
    problemAddressed_ar: "تبخر دروس الأسابيع الماضية بسبب التركيز الحصري على دروس الأسبوع الجاري.",
    practicalSteps_ar: [
      "تخصيص جلسة ثابتة صبيحة يوم السبت (90 دقيقة).",
      "حل اختبار مختلط (Interleaved) يشمل 6 أسئلة من أسابيع مختلفة.",
      "إعادة حل المسائل الثلاث الأكثر صعوبة في كراس الأخطاء لهذا الأسبوع.",
      "تحديث حالة المهارات في لوحة التحكم وتحديد أولويات الأسبوع القادم.",
    ],
    exampleScenario_ar: "جلسة السبت: حل سؤال نهايات من الأسبوع 1، وسؤال دارة RC من الأسبوع 2، وسؤال ترجمة وراثية من الأسبوع 3.",
    commonTrap_ar: "قضاء نهاية الأسبوع كاملة في مراجعة الدروس الجديدة فقط وإهمال الدروس السابقة.",
    estimatedMinutes: 90,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_09_catchup_backlog",
    title_ar: "بروتوكول استدراك التراكم (Le Retard) بدون انهيار نفسي",
    title_fr: "Protocole de rattrapage stratégique du retard sans surcharge",
    category: "revision",
    problemAddressed_ar: "الشلل الذهني واليأس بسبب تراكم الدروس القديمة وإهمال الدروس الحالية.",
    practicalSteps_ar: [
      "مواصلة دروس القسم الحالية فوراً لمنع تراكم إضافي.",
      "فرز الدروس المتراكمة إلى حرجة (A)، مهمة ومستقلة (B)، وثانوية تؤجل للعطل (C).",
      "إضافة 30 دقيقة يومياً فقط مخصصة لاستدراك المتأخرات الحرجة.",
      "التركيز على حل التمارين النموذجية البسيطة أولاً لاستعادة الثقة وسرعة الإنجاز.",
    ],
    exampleScenario_ar: "طالب متأخر في الفصل الأول؛ يواكب درس الكهرباء الحالي ويخصص نصف ساعة يومياً لإنهاء اشتقاق الدوال فقط.",
    commonTrap_ar: "الانعزال عن الثانوية لأسبوع لمحاولة إنهاء كل المتراكمات دفعة واحدة والانهيار بعد 48 ساعة.",
    estimatedMinutes: 30,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_10_time_management",
    title_ar: "بروتوكول إدارة الوقت بنظام الكتل الواقعية",
    title_fr: "Gestion du temps par blocs d'énergie et batailles quotidiennes",
    category: "time_management",
    problemAddressed_ar: "فشل الجداول الزمنية الصارمة والشعور المستمر بالذنب وضياع اليوم في المشتتات.",
    practicalSteps_ar: [
      "إلغاء الجداول بالساعات والدقائق واستبدالها بنظام كتل الطاقة (صباحية، مسائية، ليلية).",
      "تخصيص كتلة التركيز العالي للمواد العلمية الأكثر تطلباً ذهنياً.",
      "تحديد معركتين يوميتين فقط (Must-Win Battles) لا تنام حتى تنجزهما مهما حدث.",
      "تطبيق قاعدة 50 دقيقة تركيز تليها 10 دقائق راحة بعيداً عن شاشة الهاتف.",
    ],
    exampleScenario_ar: "كتلة الصباح: حل مسألة ميكانيك؛ كتلة المساء: تمرين علوم؛ كتلة الليل: مراجعة بطاقات الأخطاء لمدة 15 دقيقة.",
    commonTrap_ar: "كتابة جدول يحتوي على 14 ساعة دراسة يومياً والتوقف عن الدراسة كلياً بعد 3 أيام.",
    estimatedMinutes: 60,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_11_pre_exam_sprint",
    title_ar: "بروتوكول الأيام الثلاثة قبل الامتحان الفصلي أو التجريبي",
    title_fr: "Sprint des 72 heures pré-examen : consolidation et calme mental",
    category: "exam_prep",
    problemAddressed_ar: "القلق المفرط، السهر حتى الفجر، وتشتيت الذهن بمسائل تعجيزية ليلة الاختبار.",
    practicalSteps_ar: [
      "إيقاف حل التمارين التعجيزية الجديدة والتركيز على تثبيت المكتسبات.",
      "مراجعة كراس الأخطاء الشخصية وبطاقات القوانين المركزة.",
      "حل موضوع بكالوريا واحد بتوقيت زمني محدد لضبط وتيرة الإنجاز.",
      "النوم 8 ساعات كاملة ليلة الاختبار لضمان كفاءة القشرة المخية وسرعة البديهة.",
    ],
    exampleScenario_ar: "اليوم السابق للبكالوريا التجريبية: مراجعة بطاقات القوانين، حل تمرين استرجاعي، والنوم عند الساعة 22:30 تماماً.",
    commonTrap_ar: "السهر إلى 4 صباحاً لحل موضوع مسرب أو تمرين معقد والذهاب للامتحان بذهن منهك مشوش.",
    estimatedMinutes: 60,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_12_exam_simulation",
    title_ar: "بروتوكول إدارة الامتحان التجريبي الذاتي في المنزل",
    title_fr: "Simulation d'examen en conditions réelles du Baccalauréat",
    category: "exam_prep",
    problemAddressed_ar: "الارتباك وسوء تقدير الوقت عند مواجهة ورقة الامتحان الرسمية لأول مرة.",
    practicalSteps_ar: [
      "محاكاة الظروف الرسمية: إغلاق الهاتف، طاولة فارغة، مسودة، ومؤقت زمني صارم.",
      "تخصيص أول 15 دقيقة إجبارية لاختيار الموضوع بهدوء دون كتابة أي حل.",
      "توزيع الوقت على التمارين حسب عدد النقاط والالتزام بالخطة.",
      "تخصيص آخر 15 دقيقة للمراجعة والتدقيق في الوحدات وتأطير النتائج.",
    ],
    exampleScenario_ar: "جلسة الأحد: امتحان رياضيات 3.5 ساعات؛ 15 دقيقة اختيار، 45 دقيقة تمرين 1، 45 دقيقة تمرين 2، 90 دقيقة مسألة، 15 دقيقة مراجعة.",
    commonTrap_ar: "إلقاء نظرة على الحل بعد مرور ساعة واحدة بحجة 'أردت التأكد من النتيجة فقط'.",
    estimatedMinutes: 210,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
  {
    id: "sm_13_post_exam_audit",
    title_ar: "بروتوكول التحليل التشريحي لنتائج الامتحان التجريبي",
    title_fr: "Audit post-examen : attribution diagnostique des points perdus",
    category: "exam_prep",
    problemAddressed_ar: "الاكتفاء برؤية العلامة الإجمالية (مثلاً 12/20) دون معرفة مكان ضياع النقاط بدقة.",
    practicalSteps_ar: [
      "تصنيف النقاط الضائعة في جدول: معرفية (درس منسي)، منهجية (قانون غير مبرر)، أم إنجاز (حساب، إشارة، تسرع).",
      "حساب النسبة المئوية لكل صنف من الأخطاء لمعرفة نقطة الاختناق الحقيقية.",
      "صياغة خطة العمل المباشرة: إذا كانت الأخطاء حسابية، فالحل هو التدرب تحت ضغط الوقت مع مراجعة الحسابات.",
      "تحديث قائمة الأولويات في خريطة التعلم في BAC Mastery.",
    ],
    exampleScenario_ar: "تحليل نتائج الاختبار التجريبي: رصد الأخطاء المعرفية والمنهجية والحسابية؛ وتوجيه التركيز القادم نحو دقة الحساب وضبط الوحدات.",
    commonTrap_ar: "القول بأن 'الامتحان كان صعباً والأسئلة تعجيزية' دون تفكيك سلم التصحيح نقطة بنقطة.",
    estimatedMinutes: 30,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
