/**
 * BAC Mastery V1 — Machine-Readable Content Coverage Matrix
 * Prompt 20: Comprehensive Curriculum Coverage & Lifecycle Accounting
 * 
 * Strict Audit Rules:
 * 1. Only genuinely verified and published skills (the 31 canonical Sciences Exp skills)
 *    are marked as PUBLISHED.
 * 2. New streams and subjects are faithfully classified as MAPPED or PLANNED.
 * 3. Never claim "100% complete" for unverified or planned content.
 */

import { StreamId, SubjectId, TechniqueMathSpecialty } from "@/types/education";
import { ALL_CURRICULUM_SKILLS } from "@/data/curriculum/skills";
import { CoverageSkillItem, CoverageStatus, ContentLifecycleState } from "./types";

// 1. Build the active 31 canonical Sciences Expérimentales entries
const CANONICAL_SCIENCES_EXP_ITEMS: CoverageSkillItem[] = Object.values(ALL_CURRICULUM_SKILLS).map((skill) => ({
  skillId: skill.id,
  subjectId: skill.subjectId,
  streamId: "sciences_exp",
  topicId: skill.topicId,
  title_ar: skill.title_ar,
  title_fr: skill.title_fr,
  objective_ar: skill.description_ar,
  objective_fr: skill.description_fr,
  bloomLevel: skill.cognitiveDimensions.includes("application") ? "apply" : "understand",
  status: "PUBLISHED" as CoverageStatus,
  lifecycleState: "PUBLISHED" as ContentLifecycleState,
  hasLesson: true,
  hasExample: true,
  hasActiveRecall: true,
  hasPractice: true,
  hasRetest: true,
  hasRepair: true,
  hasExamTransfer: true,
  contentLanguage: "ar",
  verificationStatus: "OFFICIAL_HISTORICAL",
  verificationDimensions: {
    structuralVerification: true,
    factualVerification: true,
    pedagogicalVerification: true,
    provenanceVerification: true,
    languageVerification: true,
  },
  productionPriorityScore: 100, // already completed reference implementation
}));

// 2. Multi-Stream Planned Foundations (Math, Technique Math, Gestion-Éco, Lettres-Philo, Langues)
const PLANNED_MULTI_STREAM_ITEMS: CoverageSkillItem[] = [
  // ===========================================================================
  // STREAM: MATHÉMATIQUES (12 PRODUCTION BATCH 01 PUBLISHED SKILLS)
  // ===========================================================================
  {
    skillId: "math_m_arithmetic_congruence",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_divisibility_congruences",
    title_ar: "القسمة الإقليدية والموافقات ودورية قوى الأعداد",
    title_fr: "Divisibilité, congruences dans Z et périodicité des puissances",
    objective_ar: "حساب بواقي قسمة قوى عدد طبيعي على عدد معطى بدراسة دورية البواقي وتوظيف خواص الموافقات في إثبات قابلية القسمة.",
    objective_fr: "Déterminer la périodicité des restes des puissances d'un entier modulo n et appliquer les congruences.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 98,
  },
  {
    skillId: "math_m_bezout_diophantine",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_arithmetic_theorems",
    title_ar: "مبرهنة بيزو وحل المعادلات الديوفانتية في Z²",
    title_fr: "Théorème de Bézout et équations diophantiennes dans Z²",
    objective_ar: "تطبيق مبرهنة بيزو واستعمال خوارزمية إقليدس لإيجاد الحل الخاص وحل المعادلات الديوفانتية ax + by = c في Z².",
    objective_fr: "Appliquer le théorème de Bézout et résoudre les équations diophantiennes dans Z².",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 96,
  },
  {
    skillId: "math_m_gauss_prime_factors",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_arithmetic_theorems",
    title_ar: "مبرهنة غوص والتحليل إلى جداء عوامل أولية",
    title_fr: "Théorème de Gauss et décomposition en facteurs premiers",
    objective_ar: "توظيف مبرهنة غوص والتحليل إلى جداء عوامل أولية في إثبات قابلية القسمة وتعيين القواسم المشتركة وحل جمل المعادلات بالأعداد الطبيعية.",
    objective_fr: "Exploiter le théorème de Gauss et la décomposition en facteurs premiers pour la divisibilité.",
    bloomLevel: "analyze",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 94,
  },
  {
    skillId: "math_m_complex_algebraic_trig",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_complex_algebra",
    title_ar: "الأعداد المركبة والأشكال المثلثية والأسية ودستور دو موافر",
    title_fr: "Nombres complexes : forme exponentielle et formule de Moivre",
    objective_ar: "الانتقال بدقة بين الأشكال الجبرية والمثلثية والأسية للأعداد المركبة وتطبيق خواص العمدة ودستور دو موافر وحل المعادلات في C.",
    objective_fr: "Maîtriser les formes algébrique, trigonométrique et exponentielle et la formule de Moivre.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 95,
  },
  {
    skillId: "math_m_similitudes_directes",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_similitudes_directes",
    title_ar: "التحويلات النقطية: التشابه المباشر وعناصره المميزة",
    title_fr: "Similitudes planes directes : écriture complexe, centre, rapport, angle",
    objective_ar: "تعيين الطبيعة الهندسية والعناصر المميزة للتشابه المباشر (المركز، النسبة، والزاوية) انطلاقاً من الكتابة المركبة z' = az + b والعكس.",
    objective_fr: "Caractériser géométriquement une similitude plane directe à partir de son écriture complexe.",
    bloomLevel: "analyze",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 95,
  },
  {
    skillId: "math_m_derivatives_tvi_rigor",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_continuity_derivatives",
    title_ar: "الاستمرارية، مبرهنة القيم المتوسطة، والتقعر ونقاط الانعطاف",
    title_fr: "Continuité, dérivabilité, TVI rigoureux et convexité",
    objective_ar: "تطبيق مبرهنة القيم المتوسطة بالبرهان الاستدلالي الصارم للوجود والوحدانية وحصر الحلول وتوظيف المشتقة الثانية في دراسة التحدب ونقاط الانعطاف.",
    objective_fr: "Démontrer l'existence et l'unicité des solutions par le TVI et étudier la convexité.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 97,
  },
  {
    skillId: "math_m_exp_log_croissances",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_exp_log_croissances",
    title_ar: "الدوال الأسية واللوغاريتمية والتزايد المقارن والمستقيمات المقاربة",
    title_fr: "Exponentielle, logarithme, croissances comparées et asymptotes",
    objective_ar: "إزالة حالات عدم التعيين المعقدة بتوظيف نهايات التزايد المقارن وتفسير المستقيمات المقاربة الأفقية والعمودية والمائلة.",
    objective_fr: "Lever les indéterminations complexes par les croissances comparées et interpréter les asymptotes.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 96,
  },
  {
    skillId: "math_m_integration_parts",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_integration_primitives",
    title_ar: "الحساب التكاملي: المكاملة بالتجزئة وحساب المساحات",
    title_fr: "Intégration par parties, calcul d'intégrales et calcul d'aires",
    objective_ar: "حساب التكاملات باستعمال تقنية المكاملة بالتجزئة وتوظيفها في حساب مساحات الحيز المستوي وحصر المتتاليات التكاملية.",
    objective_fr: "Calculer des intégrales par parties et déterminer des aires planes.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 93,
  },
  {
    skillId: "math_m_differential_equations",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_differential_equations",
    title_ar: "المعادلات التفاضلية الخطية من الرتبة الأولى والثانية",
    title_fr: "Équations différentielles linéaires y' = ay + b et y'' + w²y = 0",
    objective_ar: "حل المعادلات التفاضلية الخطية من الرتبة الأولى y' = ay + b والرتبة الثانية y'' + w²y = 0 وتعيين الحلول الخاصة المستوفية للشروط الابتدائية.",
    objective_fr: "Résoudre les équations différentielles linéaires des premier et second ordres.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 91,
  },
  {
    skillId: "math_m_induction_adjacent_suites",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_sequences_convergence",
    title_ar: "المتتاليات العددية: الاستدلال بالتراجع والمتتاليات المتجاورة",
    title_fr: "Raisonnement par récurrence, convergence et suites adjacentes",
    objective_ar: "صياغة البرهان بالتراجع بدقة منهجية تامة وإثبات تجاور متتاليتين عدديتين وتحديد نهايتهما المشتركة.",
    objective_fr: "Rédiger le raisonnement par récurrence et démontrer l'adjacence de deux suites.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 95,
  },
  {
    skillId: "math_m_space_geometry_planes",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_space_geometry",
    title_ar: "الهندسة في الفضاء: الجداء السلمي، معادلات المستويات، والمسافات",
    title_fr: "Géométrie dans l'espace : équations cartésiennes, produit scalaire et distances",
    objective_ar: "كتابة المعادلة الديكارتية لمستو والتمثيل الوسيطي لمستقيم وحساب المسافة بين نقطة ومستو وتعيين نقط التقاطع في الفضاء.",
    objective_fr: "Déterminer l'équation cartésienne d'un plan, la représentation d'une droite et calculer des distances.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 92,
  },
  {
    skillId: "math_m_combinatorics_bernoulli",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_combinatorics_bernoulli",
    title_ar: "التحليل التوفيقي، مخطط برنولي، وقانون ثنائي الحد",
    title_fr: "Analyse combinatoire, schéma de Bernoulli et loi binomiale",
    objective_ar: "توظيف قوانين التحليل التوفيقي وحساب احتمالات مخطط برنولي وتعيين قانون الاحتمال والأمل الرياضي والتباين لمتغير عشوائي.",
    objective_fr: "Calculer les probabilités combinatoires, la loi binomiale et les paramètres d'une variable aléatoire.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 91,
  },

  // ===========================================================================
  
  // ===========================================================================
  // STREAM: MATHÉMATIQUES — PRODUCTION BATCH 02 (9 PUBLISHED SKILLS)
  // ===========================================================================
  {
    skillId: "math_m_sequences_comparison_limits",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_sequences_convergence",
    title_ar: "نهايات المتتاليات بمبرهنات المقارنة والحصر ومبرهنة الدرك",
    title_fr: "Limites de suites par comparaison et encadrement",
    objective_ar: "حساب نهايات المتتاليات العددية بتطبيق مبرهنات المقارنة والحصر (مبرهنة الساندويتش/الدرك) وإثبات التباعد نحو اللانهاية بتعليل استدلالي سليم.",
    objective_fr: "Déterminer la limite d'une suite par comparaison et encadrement (théorème des gendarmes) et justifier la divergence.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 97,
  },
  {
    skillId: "math_m_geometric_sequences",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_sequences_convergence",
    title_ar: "المتتاليات الهندسية ومجموع الحدود المتتابعة وتطبيقاتها في البكالوريا",
    title_fr: "Suites géométriques, somme de termes et applications BAC",
    objective_ar: "إثبات أن متتالية هندسية وتعيين عناصرها المميزة وحساب مجموع حدود متتابعة منها ودراسة تقاربها.",
    objective_fr: "Caractériser une suite géométrique, calculer la somme de termes consécutifs et étudier la convergence.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 97,
  },
  {
    skillId: "math_m_roots_of_unity",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_complex_algebra",
    title_ar: "الجذور النونية للوحدة والهندسة المنتظمة في المستوي المركب",
    title_fr: "Racines n-ièmes de l'unité et polygones réguliers dans C",
    objective_ar: "تعيين الجذور النونية للوحدة في مجموعة الأعداد المركبة وتمثيل صورها هندسياً واستغلال انعدام مجموعها في حساب المجاميع المثلثية.",
    objective_fr: "Déterminer les racines n-ièmes de l'unité, interpréter géométriquement et exploiter la nullité de leur somme.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 96,
  },
  {
    skillId: "math_m_complex_argument_loci",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_complex_algebra",
    title_ar: "المجموعات النقطية للزوايا الموجهة وعمدة كسر مركب",
    title_fr: "Lieux géométriques associés à l'argument d'un quotient complexe",
    objective_ar: "تعيين وإنشاء مجموعات النقط M في المستوي المركب المعرفة بشروط على عمدة كسر من الشكل arg((z-a)/(z-b)) مع الاستثناءات الدقيقة.",
    objective_fr: "Déterminer et représenter les lieux géométriques définis par l'argument d'un quotient complexe.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 96,
  },
  {
    skillId: "math_m_logarithmic_differentiation",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_exp_log_croissances",
    title_ar: "الاشتقاق اللوغاريتمي والدوال الأسية العامة f(x)^g(x)",
    title_fr: "Dérivation logarithmique et puissances de fonctions f(x)^g(x)",
    objective_ar: "اشتقاق الدوال من الشكل [f(x)]^[g(x)] عبر التحويل الأسي الصريح مع التحقق من شرط إيجابية الأساس ومجال التعريف.",
    objective_fr: "Dériver rigoureusement les fonctions de la forme f(x)^g(x) par passage à l'exponentielle.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 94,
  },
  {
    skillId: "math_m_function_study",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_continuity_derivatives",
    title_ar: "الدراسة الشاملة للدوال العددية ورسم المنحنى البياني والمستقيمات المقاربة",
    title_fr: "Étude complète et représentation graphique de fonctions",
    objective_ar: "إنجاز دراسة بيانية شاملة لدالة عددية انطلاقاً من النهايات واتجاه التغير والمقاربات إلى الرسم البياني الدقيق للمنحنى والمماسات.",
    objective_fr: "Mener une étude complète de fonction et construire rigoureusement sa courbe avec asymptotes et tangentes.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 98,
  },
  {
    skillId: "math_m_bounded_functions",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_continuity_derivatives",
    title_ar: "الدوال المحدودة والحصر البياني والمقارنات التكاملية",
    title_fr: "Fonctions bornées, encadrement et inégalités intégrales",
    objective_ar: "إثبات محدودية دالة عددية واستنتاج حصر دقيق لها على مجال محدد وتوظيفه في حصر التكاملات وحساب نهايات المتتاليات.",
    objective_fr: "Démontrer qu'une fonction est bornée et appliquer l'encadrement au calcul intégral et aux suites.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 95,
  },
  {
    skillId: "math_m_conditional_probability_trees",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_combinatorics_bernoulli",
    title_ar: "الأشجار الاحتمالية الموزونة وحساب الاحتمال الشرطي والتقاطع",
    title_fr: "Arbres pondérés, probabilités conditionnelles et intersections",
    objective_ar: "نمذجة التجارب العشوائية المركبة بشجرة احتمالات متوازنة وحساب الاحتمالات الشرطية واحتمالات التقاطع بدقة.",
    objective_fr: "Modéliser une expérience aléatoire par un arbre pondéré et calculer probabilités conditionnelles et intersections.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 97,
  },
  {
    skillId: "math_m_total_probability",
    subjectId: "math",
    streamId: "math",
    topicId: "math_topic_combinatorics_bernoulli",
    title_ar: "قانون الاحتمالات الكلية وتجزئة فضاء العينة ومبرهنة بايز",
    title_fr: "Formule des probabilités totales, partition et théorème de Bayes",
    objective_ar: "تطبيق قانون الاحتمالات الكلية على تجزئة معتمدة للفضاء العيني وحساب الاحتمالات البعدية بدستور بايز.",
    objective_fr: "Appliquer la formule des probabilités totales sur une partition de l'univers et utiliser le théorème de Bayes.",
    bloomLevel: "apply",
    status: "PUBLISHED",
    lifecycleState: "PUBLISHED",
    hasLesson: true,
    hasExample: true,
    hasActiveRecall: true,
    hasPractice: true,
    hasRetest: true,
    hasRepair: true,
    hasExamTransfer: true,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: true,
      factualVerification: true,
      pedagogicalVerification: true,
      provenanceVerification: true,
      languageVerification: true,
    },
    productionPriorityScore: 97,
  },
  // STREAM: TECHNIQUE MATHÉMATIQUES (4 ISOLATED SPECIALTIES)
  // ===========================================================================
  // Specialty: Génie Civil
  {
    skillId: "tm_gc_structural_statics",
    subjectId: "civil_eng",
    streamId: "technique_math",
    specialtyId: "civil_eng",
    topicId: "gc_topic_statics",
    title_ar: "علم السكون وتوازن الأنظمة المثلثية وحساب ردود الأفعال",
    title_fr: "Statique des systèmes réticulés et calcul des réactions d'appuis",
    objective_ar: "تطبيق مبدأ السكون الأساسي لعزل العقد والرافعات وحساب الجهود الداخلية.",
    objective_fr: "Application du principe fondamental de la statique aux treillis plans.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 90,
  },
  // Specialty: Génie Mécanique
  {
    skillId: "tm_gm_kinematic_mechanisms",
    subjectId: "mechanical_eng",
    streamId: "technique_math",
    specialtyId: "mechanical_eng",
    topicId: "gm_topic_kinematics",
    title_ar: "السينماتيك ومخطط السرعات والتسارع في الآليات الميكانيكية",
    title_fr: "Cinématique graphique et champs des vitesses des mécanismes",
    objective_ar: "تحديد مركز الدوران اللحظي ومضلع السرعات لنقاط منظومة ميكانيكية متصلة.",
    objective_fr: "Détermination du CIR et tracé de l'épure des vitesses pour mécanismes plans.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 90,
  },
  // Specialty: Génie Électrique
  {
    skillId: "tm_ge_combinational_logic",
    subjectId: "electrical_eng",
    streamId: "technique_math",
    specialtyId: "electrical_eng",
    topicId: "ge_topic_logic",
    title_ar: "الأنظمة التوافقية ومخططات كارنو والتجسيد بالبوابات المنطقية",
    title_fr: "Logique combinatoire, tableaux de Karnaugh et réalisation par portes",
    objective_ar: "تبسيط الدوال المنطقية ورسم المخطط المنطقي والمحاكاة التقنية للدارات.",
    objective_fr: "Simplification algébrique et par tableaux de Karnaugh de fonctions logiques.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 90,
  },
  // Specialty: Génie des Procédés
  {
    skillId: "tm_gp_chemical_reactors",
    subjectId: "process_eng",
    streamId: "technique_math",
    specialtyId: "process_eng",
    topicId: "gp_topic_reactors",
    title_ar: "المفاعلات الكيميائية وموازين المادة والطاقة في العمليات الموحدة",
    title_fr: "Réacteurs chimiques et bilans de matière et d'énergie des opérations unitaires",
    objective_ar: "حساب حجم المفاعل وزمن الإقامة وتحليل مردود التحول الكيميائي الصناعي.",
    objective_fr: "Calcul de dimensionnement de réacteurs discontinus et continus idéaux.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 90,
  },

  // ===========================================================================
  // STREAM: GESTION ET ÉCONOMIE
  // ===========================================================================
  {
    skillId: "ge_acc_financial_analysis",
    subjectId: "accounting_finance",
    streamId: "gestion_eco",
    topicId: "acc_topic_financial_analysis",
    title_ar: "الميزانية الوظيفية وتحليل مؤشرات التوازن المالي (FRNG, BFR, TN)",
    title_fr: "Bilan fonctionnel et analyse des équilibres financiers (FRNG, BFR, TN)",
    objective_ar: "إعداد الميزانية الوظيفية واستخراج رأس المال العامل وصافي الخزينة وتفسيرها اقتصادياً.",
    objective_fr: "Établissement du bilan fonctionnel et calcul des indicateurs de trésorerie.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 91,
  },
  {
    skillId: "ge_eco_monetary_policy",
    subjectId: "economics_management",
    streamId: "gestion_eco",
    topicId: "eco_topic_monetary",
    title_ar: "السياسة النقدية والكتلة النقدية وأدوات التدخل للبنك المركزي",
    title_fr: "Politique monétaire, masse monétaire et instruments de la banque centrale",
    objective_ar: "تحليل أدوات السياسة النقدية المباشرة وغير المباشرة لمعالجة التضخم والركود.",
    objective_fr: "Analyse des instruments de régulation monétaire face à l'inflation.",
    bloomLevel: "understand",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 84,
  },
  {
    skillId: "ge_law_work_contracts",
    subjectId: "law",
    streamId: "gestion_eco",
    topicId: "law_topic_labor",
    title_ar: "علاقات العمل الفردية وشروط صحة عقد العمل وآثار إنهائه",
    title_fr: "Relations individuelles de travail, contrat de travail et rupture",
    objective_ar: "التمييز القانوني بين عقود العمل المحددة وغير المحددة المدة وحالات التسريح التأديبي.",
    objective_fr: "Régime juridique des contrats de travail et procédures légales de résiliation.",
    bloomLevel: "understand",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 82,
  },

  // ===========================================================================
  // STREAM: LETTRES ET PHILOSOPHIE
  // ===========================================================================
  {
    skillId: "lp_phil_epistemology_science",
    subjectId: "philosophy",
    streamId: "lettres_philo",
    topicId: "phil_topic_knowledge",
    title_ar: "المقالة الفلسفية المقارنة بين المعرفة الفلسفية والبحث العلمي",
    title_fr: "Dissertation comparée : pensée philosophique vs démarche scientifique",
    objective_ar: "بناء مقالة فلسفية بطريقة المقارنة مع ضبط أوجه التشابه والاختلاف والتدخل.",
    objective_fr: "Méthodologie de la dissertation comparative en épistémologie.",
    bloomLevel: "evaluate",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 93,
  },
  {
    skillId: "lp_ar_classical_poetry_analysis",
    subjectId: "arabic",
    streamId: "lettres_philo",
    topicId: "ar_topic_poetry",
    title_ar: "تحليل النص الشعري في عصر الانحطاط والنزعة العقلية",
    title_fr: "Analyse textuelle et stylistique de la poésie classique arabe",
    objective_ar: "تحليل الخصائص البلاغية والأسلوبية والعروضية للنص الشعري وفق منهجية البكالوريا.",
    objective_fr: "Analyse rhétorique, stylistique et prosodique selon les normes du BAC.",
    bloomLevel: "analyze",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "ar",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 89,
  },

  // ===========================================================================
  // STREAM: LANGUES ÉTRANGÈRES
  // ===========================================================================
  {
    skillId: "le_fr_argumentative_text_analysis",
    subjectId: "french",
    streamId: "langues_etrangeres",
    topicId: "fr_topic_argumentation",
    title_ar: "تحليل النص الحجاجي والتقنيات البيانية لصياغة التقرير الموضوعي",
    title_fr: "Analyse du texte argumentatif et techniques du compte rendu objectif",
    objective_ar: "استخراج الأطروحة والحجج والمؤشرات اللغوية وإعداد ملخص موضوعي دقيق بالفرنسية.",
    objective_fr: "Identification de la visée argumentative et rédaction du compte rendu objectif.",
    bloomLevel: "analyze",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "fr",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 92,
  },
  {
    skillId: "le_en_historical_text_critique",
    subjectId: "english",
    streamId: "langues_etrangeres",
    topicId: "en_topic_ancient_civilizations",
    title_ar: "قراءة نقدية للنصوص التاريخية حول الحضارات القديمة والكتابة التحريرية",
    title_fr: "Analyse textuelle et expression écrite : civilisations antiques et éthique",
    objective_ar: "قراءة النص وفهم المغزى وبناء فقرة تعبيرية منسجمة باللغة الإنجليزية.",
    objective_fr: "Compréhension écrite approfondie et expression écrite structurée en anglais.",
    bloomLevel: "apply",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "en",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 90,
  },
  {
    skillId: "le_es_hispanic_culture_dialogue",
    subjectId: "third_language",
    streamId: "langues_etrangeres",
    topicId: "es_topic_culture",
    title_ar: "فهم المقروء والتعبير المكتوب في اللغة الإسبانية لشهادة البكالوريا",
    title_fr: "Compréhension écrite et expression guidée en langue espagnole (BAC)",
    objective_ar: "فهم الأفكار الأساسية للنص الإسباني وتصريف الأفعال في الأزمنة المبرمجة بدقة.",
    objective_fr: "Compréhension globale et conjugaison en contexte selon le programme du BAC.",
    bloomLevel: "understand",
    status: "MAPPED",
    lifecycleState: "DRAFT",
    hasLesson: false,
    hasExample: false,
    hasActiveRecall: false,
    hasPractice: false,
    hasRetest: false,
    hasRepair: false,
    hasExamTransfer: false,
    contentLanguage: "es",
    verificationStatus: "OFFICIAL_HISTORICAL",
    verificationDimensions: {
      structuralVerification: false,
      factualVerification: true,
      pedagogicalVerification: false,
      provenanceVerification: true,
      languageVerification: false,
    },
    productionPriorityScore: 85,
  },
];

// Unified Master Matrix Array
export const FULL_COVERAGE_MATRIX: CoverageSkillItem[] = [
  ...CANONICAL_SCIENCES_EXP_ITEMS,
  ...PLANNED_MULTI_STREAM_ITEMS,
];

// ============================================================================
// HELPER QUERY FUNCTIONS
// ============================================================================

export function getCoverageMatrix(): CoverageSkillItem[] {
  return FULL_COVERAGE_MATRIX;
}

export function getStreamCoverage(
  streamId: StreamId,
  specialtyId?: TechniqueMathSpecialty
): CoverageSkillItem[] {
  return FULL_COVERAGE_MATRIX.filter((item) => {
    if (item.streamId !== streamId) return false;
    if (streamId === "technique_math") {
      if (!item.specialtyId) return true; // common TM skills
      if (!specialtyId) return false;     // unknown specialty does not leak branch skills
      return item.specialtyId === specialtyId;
    }
    return true;
  });
}

export function getSkillCoverageItem(skillId: string): CoverageSkillItem | undefined {
  return FULL_COVERAGE_MATRIX.find((item) => item.skillId === skillId);
}

export function getCoverageStats() {
  const total = FULL_COVERAGE_MATRIX.length;
  const published = FULL_COVERAGE_MATRIX.filter((i) => i.status === "PUBLISHED").length;
  const mapped = FULL_COVERAGE_MATRIX.filter((i) => i.status === "MAPPED").length;
  const planned = FULL_COVERAGE_MATRIX.filter((i) => i.status === "PLANNED").length;

  const byStream: Record<StreamId, { total: number; published: number; mapped: number }> = {
    sciences_exp: { total: 0, published: 0, mapped: 0 },
    math: { total: 0, published: 0, mapped: 0 },
    technique_math: { total: 0, published: 0, mapped: 0 },
    gestion_eco: { total: 0, published: 0, mapped: 0 },
    lettres_philo: { total: 0, published: 0, mapped: 0 },
    langues_etrangeres: { total: 0, published: 0, mapped: 0 },
  };

  for (const item of FULL_COVERAGE_MATRIX) {
    if (byStream[item.streamId]) {
      byStream[item.streamId].total++;
      if (item.status === "PUBLISHED") byStream[item.streamId].published++;
      if (item.status === "MAPPED") byStream[item.streamId].mapped++;
    }
  }

  return {
    totalSkillsCount: total,
    publishedSkillsCount: published,
    mappedSkillsCount: mapped,
    plannedSkillsCount: planned,
    byStream,
  };
}
