import fs from 'fs';

const verifiedProgramsContent = `// ==============================================================================
// Official MESRS Programs & Admission Circular Data (Verified Data Layer)
// Source of truth: circulaire.mesrs.dz (Ministère de l'Enseignement Supérieur)
// Grounded in Official Ministerial Circular No. 01 and 2024 Statistical Reports
// ==============================================================================
import { Program } from '@/types/orientation';
import { OFFICIAL_INSTITUTIONS } from './institutions';

const instMap = new Map(OFFICIAL_INSTITUTIONS.map(i => [i.id, i]));
const getInst = (id: string) => {
  const inst = instMap.get(id);
  if (!inst) throw new Error(\`Institution \${id} not found\`);
  return inst;
};

export const OFFICIAL_PROGRAMS: Program[] = [
  // 1. DOCTORAT EN MÉDECINE (طب بشري)
  {
    id: 'prog-med-01',
    programCode: '011',
    fieldId: 'MED',
    nameAr: 'دكتور في الطب (العلوم الطبية)',
    nameFr: 'Doctorat en Médecine',
    specialtyAr: 'طب عام',
    trainingType: 'medicine',
    degreeType: "دكتوراه في الطب (Doctorat d'État)",
    durationYears: 7,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger1'),
        registrationScope: 'regional',
        eligibleWilayas: [16, 9, 35, 42], // Alger, Blida, Boumerdes, Tipaza
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'regional',
        eligibleWilayas: [31, 13, 27, 29, 46, 48], // Oran, Tlemcen, Mostaganem, Mascara, Ain Temouchent, Relizane
      },
      {
        institution: getInst('inst-univ-constantine3'),
        registrationScope: 'regional',
        eligibleWilayas: [25, 4, 18, 43], // Constantine, Oum El Bouaghi, Jijel, Mila
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'regional',
        eligibleWilayas: [19, 6, 28, 34], // Sétif, Béjaïa, M'sila, Bordj Bou Arreridj
      },
      {
        institution: getInst('inst-univ-annaba'),
        registrationScope: 'regional',
        eligibleWilayas: [23, 21, 24, 36, 41], // Annaba, Skikda, Guelma, El Tarf, Souk Ahras
      },
      {
        institution: getInst('inst-univ-batna2'),
        registrationScope: 'regional',
        eligibleWilayas: [5, 7, 12, 40, 51], // Batna, Biskra, Tébessa, Khenchela, Ouled Djellal
      },
      {
        institution: getInst('inst-univ-ouargla'),
        registrationScope: 'regional',
        eligibleWilayas: [30, 39, 47, 55, 57, 58], // Ouargla, El Oued, Ghardaïa, Touggourt, El M'Ghair, El Meniaa
      },
      {
        institution: getInst('inst-univ-bechar'),
        registrationScope: 'regional',
        eligibleWilayas: [8, 1, 32, 37, 45, 49, 50, 52, 53, 54, 56], // Sud-Ouest & Grand Sud
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-med-se',
        programId: 'prog-med-01',
        bacStreamId: 'sciences_exp',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-med-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي وفق الدائرة الجغرافية للولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-med-m',
        programId: 'prog-med-01',
        bacStreamId: 'math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-med-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي وفق الدائرة الجغرافية للولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-med-tm',
        programId: 'prog-med-01',
        bacStreamId: 'technique_math',
        priority: 2,
        rankingBasis: 'general_average', // Official rule: Technique Math is ranked by General Average directly (no natural sciences in TM)
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل جهوي وفق الدائرة الجغرافية للولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-med-2024-alger-se',
        programId: 'prog-med-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'sciences_exp',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 16.20,
        cutoffWeightedAverage: 16.33,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceUrl: 'https://orientation.esi.dz',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'cutoff-med-2024-alger-tm',
        programId: 'prog-med-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'technique_math',
        priority: 2,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 16.82,
        cutoffWeightedAverage: null,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceUrl: 'https://orientation.esi.dz',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'cutoff-med-2024-alger-m',
        programId: 'prog-med-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'math',
        priority: 2,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 16.35,
        cutoffWeightedAverage: 16.45,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceUrl: 'https://orientation.esi.dz',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 2. DOCTORAT EN PHARMACIE (صيدلة)
  {
    id: 'prog-pharm-01',
    programCode: '012',
    fieldId: 'MED',
    nameAr: 'دكتور في الصيدلة',
    nameFr: 'Doctorat en Pharmacie',
    specialtyAr: 'صيدلة',
    trainingType: 'pharmacy',
    degreeType: "دكتوراه في الصيدلة (Doctorat d'État)",
    durationYears: 6,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger1'),
        registrationScope: 'regional',
        eligibleWilayas: [16, 9, 35, 42, 10, 26, 44],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'regional',
        eligibleWilayas: [31, 13, 27, 29, 46, 48, 20, 14],
      },
      {
        institution: getInst('inst-univ-constantine3'),
        registrationScope: 'regional',
        eligibleWilayas: [25, 4, 18, 43, 23, 21, 24, 36, 41],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-pharm-se',
        programId: 'prog-pharm-01',
        bacStreamId: 'sciences_exp',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-pharm-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-pharm-m',
        programId: 'prog-pharm-01',
        bacStreamId: 'math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-pharm-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-pharm-2024-alger-se',
        programId: 'prog-pharm-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'sciences_exp',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 15.90,
        cutoffWeightedAverage: 16.03,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 3. DOCTORAT EN MÉDECINE DENTAIRE (طب أسنان)
  {
    id: 'prog-dent-01',
    programCode: '013',
    fieldId: 'MED',
    nameAr: 'دكتور في طب الأسنان',
    nameFr: 'Doctorat en Médecine Dentaire',
    specialtyAr: 'طب وجراحة الأسنان',
    trainingType: 'dentistry',
    degreeType: "دكتوراه في طب الأسنان (Doctorat d'État)",
    durationYears: 6,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger1'),
        registrationScope: 'regional',
        eligibleWilayas: [16, 9, 35, 42, 10, 26, 44],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'regional',
        eligibleWilayas: [31, 13, 27, 29, 46, 48, 20, 14],
      },
      {
        institution: getInst('inst-univ-constantine3'),
        registrationScope: 'regional',
        eligibleWilayas: [25, 4, 18, 43, 23, 21, 24, 36, 41],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-dent-se',
        programId: 'prog-dent-01',
        bacStreamId: 'sciences_exp',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-dent-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-dent-m',
        programId: 'prog-dent-01',
        bacStreamId: 'math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-dent-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-dent-2024-alger-se',
        programId: 'prog-dent-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'sciences_exp',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 16.65,
        cutoffWeightedAverage: 16.81,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 4. ESI ALGER (071) - مدرسة عليا للإعلام الآلي
  {
    id: 'prog-esi-01',
    programCode: '071',
    fieldId: 'MI',
    nameAr: 'إعلام آلي - تحضيري مدرسة عليا (ESI الجزائر)',
    nameFr: 'Classes Préparatoires Intégrées en Informatique (ESI Alger)',
    specialtyAr: 'إعلام آلي وهندسة البرمجيات',
    trainingType: 'higher_school',
    degreeType: "مهندس دولة + ماستر في الإعلام الآلي (Ingénieur d'État)",
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-esi-alger'),
        registrationScope: 'national',
        eligibleWilayas: undefined, // National: all 58 wilayas
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-esi-m',
        programId: 'prog-esi-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 16.00,
        minimumWeightedAverage: 16.00,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني لجميع ولايات الوطن',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-esi-tm',
        programId: 'prog-esi-01',
        bacStreamId: 'technique_math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 16.50,
        minimumWeightedAverage: 16.50,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-esi-se',
        programId: 'prog-esi-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 16.50,
        minimumWeightedAverage: 16.50,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-esi-2024-m',
        programId: 'prog-esi-01',
        institutionId: 'inst-esi-alger',
        bacStreamId: 'math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 18.00,
        cutoffWeightedAverage: 18.05,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'cutoff-esi-2024-tm',
        programId: 'prog-esi-01',
        institutionId: 'inst-esi-alger',
        bacStreamId: 'technique_math',
        priority: 2,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 18.25,
        cutoffWeightedAverage: 18.35,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'cutoff-esi-2024-se',
        programId: 'prog-esi-01',
        institutionId: 'inst-esi-alger',
        bacStreamId: 'sciences_exp',
        priority: 2,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 18.50,
        cutoffWeightedAverage: 18.65,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 5. ENSIA (072) - ذكاء اصطناعي
  {
    id: 'prog-ensia-01',
    programCode: '072',
    fieldId: 'MI',
    nameAr: 'ذكاء اصطناعي وعلوم البيانات (ENSIA سيدي عبد الله)',
    nameFr: 'Intelligence Artificielle et Science des Données (ENSIA)',
    specialtyAr: 'ذكاء اصطناعي وخوارزميات متقدمة',
    trainingType: 'higher_school',
    degreeType: "مهندس دولة في الذكاء الاصطناعي (Ingénieur d'État)",
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-ensia'),
        registrationScope: 'national',
        eligibleWilayas: undefined,
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-ensia-m',
        programId: 'prog-ensia-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 16.50,
        minimumWeightedAverage: 16.50,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-ensia-tm',
        programId: 'prog-ensia-01',
        bacStreamId: 'technique_math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 17.00,
        minimumWeightedAverage: 17.00,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-ensia-se',
        programId: 'prog-ensia-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 17.00,
        minimumWeightedAverage: 17.00,
        minimumSubjectAverage: null,
        mathematicsMin: 14.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 14.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-ensia-2024-m',
        programId: 'prog-ensia-01',
        institutionId: 'inst-ensia',
        bacStreamId: 'math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 17.80,
        cutoffWeightedAverage: 17.95,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 6. ENP ALGER (081) - مدرسة وطنية متعددة التقنيات
  {
    id: 'prog-enp-01',
    programCode: '081',
    fieldId: 'ST',
    nameAr: 'أقسام تحضيرية في العلوم والتقنيات (المدرسة الوطنية متعددة التقنيات - ENP)',
    nameFr: 'Classes Préparatoires en Sciences et Techniques (ENP Alger)',
    specialtyAr: 'علوم وتكنولوجيا وهندسة صناعية',
    trainingType: 'engineering',
    degreeType: "مهندس دولة (Ingénieur d'État)",
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-enp-alger'),
        registrationScope: 'national',
        eligibleWilayas: undefined,
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-enp-m',
        programId: 'prog-enp-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 14.50,
        minimumWeightedAverage: 14.50,
        minimumSubjectAverage: null,
        mathematicsMin: 12.00,
        physicsMin: 12.00,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-enp-tm',
        programId: 'prog-enp-01',
        bacStreamId: 'technique_math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 14.50,
        minimumWeightedAverage: 14.50,
        minimumSubjectAverage: null,
        mathematicsMin: 12.00,
        physicsMin: 12.00,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-enp-se',
        programId: 'prog-enp-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 15.00,
        minimumWeightedAverage: 15.00,
        minimumSubjectAverage: null,
        mathematicsMin: 12.00,
        physicsMin: 12.00,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-enp-2024-m',
        programId: 'prog-enp-01',
        institutionId: 'inst-enp-alger',
        bacStreamId: 'math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 16.50,
        cutoffWeightedAverage: 16.78,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 7. EPAU ALGER (083) - هندسة معمارية وعمران
  {
    id: 'prog-epau-01',
    programCode: '083',
    fieldId: 'ARCH',
    nameAr: 'هندسة معمارية وعمران (المدرسة الوطنية العليا EPAU)',
    nameFr: 'Architecture et Urbanisme (EPAU Alger)',
    specialtyAr: 'هندسة معمارية وتخطيط حضري',
    trainingType: 'higher_school',
    degreeType: "مهندس معمار دولة (Architecte d'État)",
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-epau-alger'),
        registrationScope: 'national',
        eligibleWilayas: undefined,
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-epau-m',
        programId: 'prog-epau-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 13.00,
        minimumWeightedAverage: 13.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-epau-arch',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات + علامة الفيزياء) / 4',
          expressionFr: '((2 × Bac) + Math + Physique) / 4',
          divisor: 4,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
            { subject: 'physics', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-epau-tm',
        programId: 'prog-epau-01',
        bacStreamId: 'technique_math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 13.00,
        minimumWeightedAverage: 13.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-epau-arch',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات + علامة الفيزياء) / 4',
          expressionFr: '((2 × Bac) + Math + Physique) / 4',
          divisor: 4,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
            { subject: 'physics', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-epau-se',
        programId: 'prog-epau-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 13.50,
        minimumWeightedAverage: 13.50,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-epau-arch',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات + علامة الفيزياء) / 4',
          expressionFr: '((2 × Bac) + Math + Physique) / 4',
          divisor: 4,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
            { subject: 'physics', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-epau-2024-tm',
        programId: 'prog-epau-01',
        institutionId: 'inst-epau-alger',
        bacStreamId: 'technique_math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 15.65,
        cutoffWeightedAverage: 15.95,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 8. MATHÉMATIQUES ET INFORMATIQUE (MI LMD) (041)
  {
    id: 'prog-mi-01',
    programCode: '041',
    fieldId: 'MI',
    nameAr: 'رياضيات وإعلام آلي (ليسانس وماستر LMD)',
    nameFr: 'Mathématiques et Informatique (MI)',
    specialtyAr: 'جذع مشترك رياضيات وإعلام آلي',
    trainingType: 'licence',
    degreeType: 'ليسانس أكاديمي (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-usthb'),
        registrationScope: 'regional',
        eligibleWilayas: [16, 9, 35, 42],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'local',
        eligibleWilayas: [31],
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'local',
        eligibleWilayas: [19],
      },
      {
        institution: getInst('inst-univ-constantine3'),
        registrationScope: 'local',
        eligibleWilayas: [25],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-mi-m',
        programId: 'prog-mi-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 11.00,
        minimumWeightedAverage: 11.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي / محلي حسب الولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-mi-tm',
        programId: 'prog-mi-01',
        bacStreamId: 'technique_math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 11.00,
        minimumWeightedAverage: 11.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي / محلي حسب الولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-mi-se',
        programId: 'prog-mi-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 11.00,
        minimumWeightedAverage: 11.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي / محلي حسب الولاية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-mi-2024-usthb-m',
        programId: 'prog-mi-01',
        institutionId: 'inst-usthb',
        bacStreamId: 'math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 14.15,
        cutoffWeightedAverage: 14.38,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 9. SCIENCES ET TECHNOLOGIES (ST LMD) (051)
  {
    id: 'prog-st-01',
    programCode: '051',
    fieldId: 'ST',
    nameAr: 'علوم وتكنولوجيا (ST - ليسانس وماستر LMD)',
    nameFr: 'Sciences et Technologies (ST)',
    specialtyAr: 'جذع مشترك علوم وتكنولوجيا',
    trainingType: 'licence',
    degreeType: 'ليسانس أكاديمي (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-usthb'),
        registrationScope: 'local',
        eligibleWilayas: [16],
      },
      {
        institution: getInst('inst-univ-blida1'),
        registrationScope: 'local',
        eligibleWilayas: [9],
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'local',
        eligibleWilayas: [19],
      },
      {
        institution: getInst('inst-univ-boumerdes'),
        registrationScope: 'local',
        eligibleWilayas: [35],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-st-tm',
        programId: 'prog-st-01',
        bacStreamId: 'technique_math',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي مخصص لحاملي بكالوريا الولاية المعنية',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-st-m',
        programId: 'prog-st-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-st-se',
        programId: 'prog-st-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-st-2024-usthb-tm',
        programId: 'prog-st-01',
        institutionId: 'inst-usthb',
        bacStreamId: 'technique_math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 12.30,
        cutoffWeightedAverage: null,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 10. SCIENCES DE LA NATURE ET DE LA VIE (SNV LMD) (061)
  {
    id: 'prog-snv-01',
    programCode: '061',
    fieldId: 'SNV',
    nameAr: 'علوم الطبيعة والحياة (SNV - ليسانس وماستر LMD)',
    nameFr: 'Sciences de la Nature et de la Vie (SNV)',
    specialtyAr: 'بيولوجيا وبيئة وجذع مشترك SNV',
    trainingType: 'licence',
    degreeType: 'ليسانس أكاديمي (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-usthb'),
        registrationScope: 'local',
        eligibleWilayas: [16],
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'local',
        eligibleWilayas: [19],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'local',
        eligibleWilayas: [31],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-snv-se',
        programId: 'prog-snv-01',
        bacStreamId: 'sciences_exp',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: 10.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-snv-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-snv-m',
        programId: 'prog-snv-01',
        bacStreamId: 'math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: 10.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: {
          id: 'form-snv-sciences',
          expressionAr: '((2 × معدل البكالوريا) + علوم الطبيعة والحياة) / 3',
          expressionFr: '((2 × Bac) + Sciences) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'natural_sciences', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-snv-2024-usthb-se',
        programId: 'prog-snv-01',
        institutionId: 'inst-usthb',
        bacStreamId: 'sciences_exp',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 11.85,
        cutoffWeightedAverage: 12.10,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 11. SCIENCES ÉCONOMIQUES, GESTION ET COMMERCIALES (SEGC LMD) (031)
  {
    id: 'prog-segc-01',
    programCode: '031',
    fieldId: 'SEGC',
    nameAr: 'علوم اقتصادية، التسيير وعلوم تجارية (SEGC)',
    nameFr: 'Sciences Économiques, de Gestion et Commerciales (SEGC)',
    specialtyAr: 'جذع مشترك علوم اقتصادية وتسيير',
    trainingType: 'licence',
    degreeType: 'ليسانس أكاديمي (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger3'),
        registrationScope: 'local',
        eligibleWilayas: [16],
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'local',
        eligibleWilayas: [19],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'local',
        eligibleWilayas: [31],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-segc-ge',
        programId: 'prog-segc-01',
        bacStreamId: 'gestion_eco',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-segc-m',
        programId: 'prog-segc-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-segc-tm',
        programId: 'prog-segc-01',
        bacStreamId: 'technique_math',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-segc-se',
        programId: 'prog-segc-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-segc-lp',
        programId: 'prog-segc-01',
        bacStreamId: 'lettres_philo',
        priority: 3,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-segc-2024-alger3-ge',
        programId: 'prog-segc-01',
        institutionId: 'inst-univ-alger3',
        bacStreamId: 'gestion_eco',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 10.60,
        cutoffWeightedAverage: null,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 12. ESC KOLÉA (032) - المدرسة العليا للتجارة
  {
    id: 'prog-esc-01',
    programCode: '032',
    fieldId: 'SEGC',
    nameAr: 'أقسام تحضيرية في العلوم التجارية والتسيير (ESC القليعة)',
    nameFr: 'Classes Préparatoires en Sciences Commerciales et Financières (ESC Koléa)',
    specialtyAr: 'علوم مالية وتجارية وإدارة أعمال',
    trainingType: 'higher_school',
    degreeType: 'ماستر مدرسة عليا + ديبلوم المدرسة (Diplôme ESC)',
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-esc-kolea'),
        registrationScope: 'national',
        eligibleWilayas: undefined,
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-esc-ge',
        programId: 'prog-esc-01',
        bacStreamId: 'gestion_eco',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 12.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: 11.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 11.00,
        weightedFormula: null,
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-esc-m',
        programId: 'prog-esc-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 12.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: 11.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 11.00,
        weightedFormula: null,
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-esc-se',
        programId: 'prog-esc-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 12.50,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: 11.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 11.00,
        weightedFormula: null,
        geographicCondition: 'تسجيل وطني',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-esc-2024-ge',
        programId: 'prog-esc-01',
        institutionId: 'inst-esc-kolea',
        bacStreamId: 'gestion_eco',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 13.80,
        cutoffWeightedAverage: null,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 13. DROIT ET SCIENCES JURIDIQUES (021)
  {
    id: 'prog-droit-01',
    programCode: '021',
    fieldId: 'DSP',
    nameAr: 'حقوق وعلوم قانونية وإدارية (ليسانس LMD)',
    nameFr: 'Droit et Sciences Juridiques (LMD)',
    specialtyAr: 'علوم قانونية وإدارية عامة',
    trainingType: 'licence',
    degreeType: 'ليسانس في الحقوق (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger1'),
        registrationScope: 'local',
        eligibleWilayas: [16],
      },
      {
        institution: getInst('inst-univ-setif1'),
        registrationScope: 'local',
        eligibleWilayas: [19],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'local',
        eligibleWilayas: [31],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-droit-lp',
        programId: 'prog-droit-01',
        bacStreamId: 'lettres_philo',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-droit-le',
        programId: 'prog-droit-01',
        bacStreamId: 'langues_etrangeres',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-droit-ge',
        programId: 'prog-droit-01',
        bacStreamId: 'gestion_eco',
        priority: 1,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-droit-se',
        programId: 'prog-droit-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-droit-m',
        programId: 'prog-droit-01',
        bacStreamId: 'math',
        priority: 2,
        rankingBasis: 'general_average',
        minimumGeneralAverage: 10.00,
        minimumWeightedAverage: null,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: null,
        requiredSubjectMin: null,
        weightedFormula: null,
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-droit-2024-alger-lp',
        programId: 'prog-droit-01',
        institutionId: 'inst-univ-alger1',
        bacStreamId: 'lettres_philo',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 10.45,
        cutoffWeightedAverage: null,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 14. ENS KOUBA - PROFESSEUR MATHS (PES) (091)
  {
    id: 'prog-ens-math-01',
    programCode: '091',
    fieldId: 'ENS',
    nameAr: 'أستاذ التعليم الثانوي في الرياضيات (PES - مدرسة الأساتذة بالقبة)',
    nameFr: "Professeur de l'Enseignement Secondaire en Mathématiques (ENS Kouba)",
    specialtyAr: 'تكوين أساتذة الرياضيات للطور الثانوي',
    trainingType: 'teacher_training',
    degreeType: 'شهادة أستاذ التعليم الثانوي (Diplôme de PES - 5 ans)',
    durationYears: 5,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-ens-kouba'),
        registrationScope: 'regional',
        eligibleWilayas: [16, 9, 35, 42, 10, 26, 44, 15, 6, 17, 28],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-ens-m',
        programId: 'prog-ens-math-01',
        bacStreamId: 'math',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 14.00,
        minimumWeightedAverage: 14.00,
        minimumSubjectAverage: null,
        mathematicsMin: 13.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 13.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي وفق الدوائر الجغرافية لمدارس الأساتذة',
        additionalConditions: [
          {
            type: 'medical_interview',
            titleAr: 'مقابلة شفوية وفحص طبي إلزامي',
            descriptionAr: 'يخضع المترشح المقبول مبدئياً لمقابلة شفوية أمام لجنة أساتذة + فحص طبي للتأكد من القدرة على التدريس وسلامة الحواس والنطق.',
          },
          {
            type: 'age_limit',
            titleAr: 'شرط السن القانوني',
            descriptionAr: 'ألا يتجاوز سن المترشح 24 سنة عند تاريخ 31 ديسمبر من سنة البكالوريا.',
          },
        ],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-ens-tm',
        programId: 'prog-ens-math-01',
        bacStreamId: 'technique_math',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 14.50,
        minimumWeightedAverage: 14.50,
        minimumSubjectAverage: null,
        mathematicsMin: 13.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 13.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [
          {
            type: 'medical_interview',
            titleAr: 'مقابلة شفوية وفحص طبي إلزامي',
            descriptionAr: 'يخضع المترشح لمقابلة شفوية وفحص طبي إلزامي.',
          },
        ],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-ens-se',
        programId: 'prog-ens-math-01',
        bacStreamId: 'sciences_exp',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 14.50,
        minimumWeightedAverage: 14.50,
        minimumSubjectAverage: null,
        mathematicsMin: 13.00,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: null,
        requiredSubject: 'math',
        requiredSubjectMin: 13.00,
        weightedFormula: {
          id: 'form-cs-math',
          expressionAr: '((2 × معدل البكالوريا) + علامة الرياضيات) / 3',
          expressionFr: '((2 × Bac) + Math) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'math', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل جهوي',
        additionalConditions: [
          {
            type: 'medical_interview',
            titleAr: 'مقابلة شفوية وفحص طبي إلزامي',
            descriptionAr: 'يخضع المترشح لمقابلة شفوية وفحص طبي إلزامي.',
          },
        ],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-ens-2024-m',
        programId: 'prog-ens-math-01',
        institutionId: 'inst-ens-kouba',
        bacStreamId: 'math',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 15.10,
        cutoffWeightedAverage: 15.42,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },

  // 15. LANGUE ET LITTÉRATURE ANGLAISE (025)
  {
    id: 'prog-anglais-01',
    programCode: '025',
    fieldId: 'LLE',
    nameAr: 'لغة وأدب إنجليزي (ليسانس وماستر LMD)',
    nameFr: 'Langue et Littérature Anglaise (LMD)',
    specialtyAr: 'دراسات أدبية ولغوية إنجليزية',
    trainingType: 'licence',
    degreeType: 'ليسانس أكاديمي (Licence LMD - 3 ans)',
    durationYears: 3,
    academicYear: '2026-2027',
    isActive: true,
    dataQualityStatus: 'verified',
    sourceId: 'src-mesrs-circulaire-2024',
    institutions: [
      {
        institution: getInst('inst-univ-alger2'),
        registrationScope: 'local',
        eligibleWilayas: [16],
      },
      {
        institution: getInst('inst-univ-oran1'),
        registrationScope: 'local',
        eligibleWilayas: [31],
      },
      {
        institution: getInst('inst-univ-constantine3'),
        registrationScope: 'local',
        eligibleWilayas: [25],
      },
    ],
    eligibilityRules: [
      {
        id: 'rule-anglais-le',
        programId: 'prog-anglais-01',
        bacStreamId: 'langues_etrangeres',
        priority: 1,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 10.50,
        minimumWeightedAverage: 10.50,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: 11.00,
        requiredSubject: 'english',
        requiredSubjectMin: 11.00,
        weightedFormula: {
          id: 'form-lle-eng',
          expressionAr: '((2 × معدل البكالوريا) + علامة اللغة الإنجليزية) / 3',
          expressionFr: '((2 × Bac) + Anglais) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'english', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-anglais-lp',
        programId: 'prog-anglais-01',
        bacStreamId: 'lettres_philo',
        priority: 2,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 10.50,
        minimumWeightedAverage: 10.50,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: 11.00,
        requiredSubject: 'english',
        requiredSubjectMin: 11.00,
        weightedFormula: {
          id: 'form-lle-eng',
          expressionAr: '((2 × معدل البكالوريا) + علامة اللغة الإنجليزية) / 3',
          expressionFr: '((2 × Bac) + Anglais) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'english', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
      {
        id: 'rule-anglais-se',
        programId: 'prog-anglais-01',
        bacStreamId: 'sciences_exp',
        priority: 3,
        rankingBasis: 'weighted_average',
        minimumGeneralAverage: 11.00,
        minimumWeightedAverage: 11.00,
        minimumSubjectAverage: null,
        mathematicsMin: null,
        physicsMin: null,
        naturalSciencesMin: null,
        arabicMin: null,
        frenchMin: null,
        englishMin: 11.00,
        requiredSubject: 'english',
        requiredSubjectMin: 11.00,
        weightedFormula: {
          id: 'form-lle-eng',
          expressionAr: '((2 × معدل البكالوريا) + علامة اللغة الإنجليزية) / 3',
          expressionFr: '((2 × Bac) + Anglais) / 3',
          divisor: 3,
          terms: [
            { subject: 'general_average', coefficient: 2 },
            { subject: 'english', coefficient: 1 },
          ],
          sourceId: 'src-mesrs-circulaire-2024',
          verificationStatus: 'VERIFIED',
        },
        geographicCondition: 'تسجيل محلي',
        additionalConditions: [],
        academicYear: '2026-2027',
        sourceId: 'src-mesrs-circulaire-2024',
        dataConfidence: 'HIGH',
        verificationStatus: 'VERIFIED',
      },
    ],
    cutoffs: [
      {
        id: 'cutoff-anglais-2024-le',
        programId: 'prog-anglais-01',
        institutionId: 'inst-univ-alger2',
        bacStreamId: 'langues_etrangeres',
        priority: 1,
        academicYear: '2024-2025',
        cutoffGeneralAverage: 13.40,
        cutoffWeightedAverage: 14.10,
        lastAdmittedRank: null,
        source: 'نتائج التوجيه دورة 2024 - MESRS',
        sourceId: 'src-mesrs-statistiques-2024',
        isOfficial: true,
        verificationStatus: 'VERIFIED',
      },
    ],
  },
];
`;

fs.writeFileSync('src/lib/orientation/data/programs.ts', verifiedProgramsContent, 'utf8');
console.log('Successfully written verified programs.ts');
