/**
 * BAC Mastery — Mathematics Lessons Catalog (Sciences Expérimentales 3AS)
 * Prompt 13: High-Yield, Active, Exam-Oriented Lessons (14-Element Structure)
 * 
 * 10 Skills covered with complete pedagogical loops.
 * Invariant: Content Purity (ZERO user_id).
 */

import { Lesson } from "../types";

export const MATH_LESSONS: Lesson[] = [
  // ==========================================================================
  // LESSON 01: math_derivatives_chain_rule
  // ==========================================================================
  {
    id: "lesson_math_derivatives_chain_rule",
    skillId: "math_derivatives_chain_rule",
    subjectId: "math",
    topicId: "math_topic_functions",
    title_ar: "اشتقاق الدوال المركبة وقاعدة السلسلة",
    title_fr: "Dérivation des fonctions composées et règle de dérivation en chaîne",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من حساب مشتقة أي دالة أسية أو لوغاريتمية مركبة بدقة وسرعة وبدون نسيان مشتقة الدالة الداخلية u'(x).",
    whatYouMustKnow_ar: "مشتقات الدوال المألوفة (e^x, ln(x), x^n) وقواعد العمليات على الدوال المشتقة (المجموع، الجداء، والقسمة).",
    whyThisMatters_ar: "لا يخلو أي موضوع بكالوريا في شعبة العلوم التجريبية من دراسة دالة أسية أو لوغاريتمية. الخطأ في حساب المشتقة يؤدي حتماً إلى جدول تغيرات خاطئ، ورسم بياني غير مطابق، وتعطيل بقية خطوات دراسة المسألة الرئيسية.",
    coreConcept_ar: "مشتقة الدالة المركبة f(u(x)) تساوي مشتقة الدالة الداخلية u'(x) مضروبة في مشتقة الدالة الخارجية محسوبة عند u(x): [f(u)]' = u' * f'(u).",
    simpleExplanation_ar: "تخيل الدالة المركبة كعلبة داخل علبة. لكي تشتق، يجب أن تشتق العلبة الداخلية أولاً وتخرجها كعامل ضرب، ثم تشتق العلبة الخارجية مع ترك ما بداخلها كما هو دون تغيير.",
    workedExample: {
      id: "we_math_chain_01",
      skillId: "math_derivatives_chain_rule",
      problem_ar: "احسب الدالة المشتقة للدالة f المعرفة على R بـ: f(x) = (2x - 3) * e^(-x) + 1",
      howToThink_ar: "الدالة f عبارة عن جداء دالتين u(x) * v(x) مضافاً إليها ثابت. سنطبق قاعدة الجداء (u'v + uv') مع الانتباه الشديد لمشتقة e^(-x) التي تتطلب قاعدة السلسلة: مشتقة -x هي -1.",
      stepByStepSolution_ar: [
        "الخطوة 1: نضع u(x) = 2x - 3 ومنه الدالة المشتقة u'(x) = 2.",
        "الخطوة 2: نضع v(x) = e^(-x) ومنه بتطبيق قاعدة السلسلة v'(x) = (-1) * e^(-x) = -e^(-x).",
        "الخطوة 3: نطبق قاعدة مشتق الجداء: f'(x) = u'(x)*v(x) + u(x)*v'(x) + 0.",
        "الخطوة 4: نعوض العبارات: f'(x) = 2 * e^(-x) + (2x - 3) * (-e^(-x)).",
        "الخطوة 5: نستخرج e^(-x) كعامل مشترك: f'(x) = e^(-x) * [2 - (2x - 3)] = e^(-x) * (2 - 2x + 3) = (5 - 2x) * e^(-x).",
      ],
      finalAnswer_ar: "f'(x) = (5 - 2x) * e^(-x)",
      verificationTip_ar: "بما أن e^(-x) موجب تماماً دوماً على R، فإن إشارة المشتقة هي من إشارة (5 - 2x)، مما يجعل دراسة إشارة f'(x) وتحديد اتجاه التغير في غاية السهولة والوضوح.",
    },
    commonMistakes: [
      {
        id: "cm_math_chain_sign",
        mistake_ar: "نسيان إشارة الناقص عند اشتقاق e^(-x) وكتابة المشتقة e^(-x) بدلاً من -e^(-x).",
        whyItHappens_ar: "الاعتياد على أن مشتقة e^x هي نفسها e^x وإغفال أن مشتقة -x هي -1.",
        correctAction_ar: "ضع دائماً مشتقة الأس بين قوسين أمام الدالة الأسية: [e^u]' = (u') * e^u.",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_math_chain_product",
        mistake_ar: "اشتقاق كل طرف على حدة في الجداء: f'(x) = 2 * (-e^(-x)).",
        whyItHappens_ar: "الخلط بين مشتقة المجموع ومشتقة الجداء تحت ضغط الوقت.",
        correctAction_ar: "تطبيق قانون الجداء الصارم: (u * v)' = u'v + uv'.",
        suspectedErrorType: "methodology_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت اشتقاق f(x) = e^(x^2 - 3x) واستخراج العامل (2x - 3) دون تردد وبدون خطأ في الإشارة في أقل من دقيقة واحدة.",
    quickRecallPrompt_ar: "ما هي مشتقة الدالة g(x) = e^(-3x) على R؟",
    quickRecallAnswer_ar: "g'(x) = -3 * e^(-3x)",
    practiceQuestionIds: ["pq-math-chain-01", "pq-math-chain-02"],
    whatToDoIfYouFail_ar: "إذا أخطأت في الإشارة أو نسيت الدالة المشتقة الداخلية، افتح بطاقة تصحيح الخطأ (Repair Guide) الخاصة بقاعدة السلسلة، وقم بحل 3 مشتقات ميكرو-تدريبية قبل إعادة الاختبار.",
    summaryCard: {
      id: "sc_math_chain",
      keyRule_ar: "مشتقة الدالة الأسية المركبة: [e^(u(x))]' = u'(x) * e^(u(x)).",
      keyFormula_ar: "مشتقة الدالة اللوغاريتمية المركبة: [ln(u(x))]' = u'(x) / u(x).",
      trapToAvoid_ar: "إياك ونسيان مشتقة ما بداخل الأس؛ e^(-x) مشتقتها -e^(-x) وليست e^(-x).",
    },
    retestQuestionId: "rq-math-chain-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 02: math_intermediate_value_method
  // ==========================================================================
  {
    id: "lesson_math_intermediate_value_method",
    skillId: "math_intermediate_value_method",
    subjectId: "math",
    topicId: "math_topic_functions",
    title_ar: "مبرهنة القيم المتوسطة والتمييز المنهجي بين الوجود والوحدانية",
    title_fr: "Théorème des Valeurs Intermédiaires (TVI) : Existence vs Unicité",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تحرير البرهان المنهجي الكامل لمبرهنة القيم المتوسطة باستيفاء كافة المعايير المنهجية النموذجية دون نسيان شرط الاستمرار أو الرتابة التامة.",
    whatYouMustKnow_ar: "مفهوم استمرار دالة على مجال عددي وقراءة جدول التغيرات لتحديد اتجاه التغير (الرتابة).",
    whyThisMatters_ar: "سؤال 'أثبت أن المعادلة f(x) = 0 تقبل حلاً وحيداً ألفا' سؤال شائع ومحوري في البكالوريا الجزائرية. إهمال شرط الرتابة أو الاستمرار في الصياغة يُفقد إجابة التلميذ دقّتها المنهجية المطلوبة.",
    coreConcept_ar: "إذا كانت الدالة f مستمرة ورتيبة تماماً على [a, b] وكان f(a) * f(b) < 0، فإن المعادلة f(x) = 0 تقبل حلاً وحيداً alpha في المجال المفتوح ]a, b[.",
    simpleExplanation_ar: "الاستمرار يضمن أن المنحنى لا ينقطع (وجود حل على الأقل)، والرتابة التامة تضمن أن المنحنى يقطع محور الفواصل مرة واحدة فقط دون تراجع (وحدانية الحل).",
    workedExample: {
      id: "we_math_tvi_01",
      skillId: "math_intermediate_value_method",
      problem_ar: "لتكن الدالة f(x) = x^3 + 2x - 5 المعرفة على R. أثبت أن المعادلة f(x) = 0 تقبل حلاً وحيداً alpha في المجال [1, 2].",
      howToThink_ar: "المطلوب إثبات الوجود والوحدانية. يلزمنا ثلاثة شروط معللة: 1) الاستمرار على المجال، 2) الرتابة التامة (عبر إشارة المشتقة)، 3) اختلاف إشارتي f(1) و f(2).",
      stepByStepSolution_ar: [
        "الخطوة 1: نعلل الاستمرار: الدالة f كثيرة حدود فهي مستمرة على R وبخاصة على المجال [1, 2].",
        "الخطوة 2: ندرس الرتابة: نحسب المشتقة f'(x) = 3x^2 + 2. بما أن x^2 >= 0 فإن f'(x) > 0 تماماً على R، إذن f متزايدة تماماً على [1, 2].",
        "الخطوة 3: نحسب الصورتين: f(1) = 1 + 2 - 5 = -2 < 0، و f(2) = 8 + 4 - 5 = 7 > 0.",
        "الخطوة 4: نتحقق من الشرط الجدائي: f(1) * f(2) = -14 < 0 (الصفر محصور بين f(1) و f(2)).",
        "الخطوة 5: الخلاصة النموذجية: بما أن f مستمرة ومتزايدة تماماً على [1, 2] و f(1)*f(2) < 0، فحسب مبرهنة القيم المتوسطة، المعادلة f(x) = 0 تقبل حلاً وحيداً alpha حيث alpha ينتمي إلى ]1, 2[.",
      ],
      finalAnswer_ar: "المعادلة f(x) = 0 تقبل حلاً وحيداً alpha في المجال ]1, 2[.",
      verificationTip_ar: "تأكد دوماً من كتابة المجال مفتوحاً ]a, b[ للحل alpha إذا كان f(a) != 0 و f(b) != 0 لضمان دقة الصياغة الرياضية.",
    },
    commonMistakes: [
      {
        id: "cm_math_tvi_omit_continuity",
        mistake_ar: "القفز مباشرة لحساب f(a) و f(b) دون ذكر جملة: 'بما أن الدالة f مستمرة على المجال'.",
        whyItHappens_ar: "اعتبار الاستمرار أمراً بديهياً لا يستحق الذكر.",
        correctAction_ar: "البدء دوماً بجملة الاستمرار لأن مبرهنة القيم المتوسطة لا تصح رياضياً بدون استمرار.",
        suspectedErrorType: "methodology_error",
      },
      {
        id: "cm_math_tvi_omit_strict_monotony",
        mistake_ar: "الاستدلال بـ f(a)*f(b) < 0 لوحده لاستنتاج 'حل وحيد' دون إثبات الرتابة التامة.",
        whyItHappens_ar: "الخلط بين مبرهنة الوجود (تحتاج استمرار فقط) ومبرهنة الوجود والوحدانية (تحتاج رتابة تامة).",
        correctAction_ar: "إذا طُلب 'حل وحيد'، يجب التصريح بأن الدالة متزايدة تماماً أو متناقصة تماماً.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت كتابة الخطوات الثلاث (الاستمرار، الرتابة التامة، واختلاف الإشارتين) تلقائياً في أقل من 3 دقائق لأي دالة في البكالوريا.",
    quickRecallPrompt_ar: "ما هو الشرط الإضافي اللازم إثباته في مبرهنة القيم المتوسطة للانتقال من 'وجود حل على الأقل' إلى 'وجود حل وحيد'؟",
    quickRecallAnswer_ar: "شرط الرتابة التامة للدالة (متزايدة تماماً أو متناقصة تماماً) على المجال المعني.",
    practiceQuestionIds: ["pq-math-tvi-01", "pq-math-tvi-02"],
    whatToDoIfYouFail_ar: "راجع القالب الصياغي المنهجي النموذجي والموجود في بطاقة المراجعة، ثم أعد حل تمرين alpha.",
    summaryCard: {
      id: "sc_math_tvi",
      keyRule_ar: "f مستمرة + f(a)*f(b) < 0 => حل على الأقل. إضافة الرتابة التامة => حل وحيد.",
      keyFormula_ar: "f(a) * f(b) < 0  مع  f'(x) لا تغير إشارتها على [a, b].",
      trapToAvoid_ar: "لا تنس ذكر اسم المبرهنة: 'حسب مبرهنة القيم المتوسطة' وإثبات الاستمرار صراحة.",
    },
    retestQuestionId: "rq-math-tvi-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 03: math_asymptotes_limits
  // ==========================================================================
  {
    id: "lesson_math_asymptotes_limits",
    skillId: "math_asymptotes_limits",
    subjectId: "math",
    topicId: "math_topic_functions",
    title_ar: "المستقيمات المقاربة الأفقية، العمودية والمائلة وتفسير النهايات بيانياً",
    title_fr: "Asymptotes horizontales, verticales et obliques et interprétation graphique",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من استخراج معادلات المستقيمات المقاربة الثلاثة بدقة منهجية وتفسير كل نهاية هندسياً في ورقة إجابة البكالوريا.",
    whatYouMustKnow_ar: "حساب النهايات عند أطراف مجالات التعريف وطرق إزالة حالات عدم التعيين الأربع.",
    whyThisMatters_ar: "سؤال 'فسر النتيجة هندسياً' أو 'أثبت أن المنحنى يقبل مستقيماً مقارباً' سؤال منهجي أساسي يمثل عادة من 1 إلى 2 نقطة في الجزء الأول من المسألة.",
    coreConcept_ar: "النهاية المنتهية عند اللانهاية تعطي مقارباً أفقياً (y = b)، والنهاية غير المنتهية عند عدد حقيقي تعطي مقارباً عمودياً (x = a)، ونهاية الفرق [f(x) - (ax+b)] المنعدمة عند اللانهاية تعطي مقارباً مائلاً (y = ax+b).",
    simpleExplanation_ar: "المستقيم المقارب هو خط مستقيم يقترب منه منحنى الدالة باستمرار دون أن يلتقيا في اللانهاية، ويوجه المنحنى في أقصى اليمين أو اليسار أو بالقرب من القيم الممنوعة.",
    workedExample: {
      id: "we_math_asymp_01",
      skillId: "math_asymptotes_limits",
      problem_ar: "لتكن الدالة f(x) = (2x + 1) / (x - 1) المعرفة على R - {1}. احسب نهايات f عند أطراف مجالات التعريف وفسر النتائج بيانياً.",
      howToThink_ar: "نحسب النهاية عند +مالانهاية و -مالانهاية بقاعدة أكبر حد على أكبر حد للحصول على المقارب الأفقي، ثم نحسب النهاية بقيم صغرى وكبرى عند القيمة الممنوعة x = 1 للحصول على المقارب العمودي.",
      stepByStepSolution_ar: [
        "الخطوة 1: عند +مالانهاية: lim (2x+1)/(x-1) = lim (2x/x) = 2.",
        "الخطوة 2: التفسير البياني الأول: المنحنى (Cf) يقبل مستقيماً مقارباً أفقياً معادلته y = 2 بجوار +مالانهاية و -مالانهاية.",
        "الخطوة 3: عند 1 بقيم صغرى: البسط يؤول إلى 3 والمقام يؤول إلى 0 سالبة، إذن النهاية تساوي -مالانهاية.",
        "الخطوة 4: عند 1 بقيم كبرى: البسط يؤول إلى 3 والمقام يؤول إلى 0 موجبة، إذن النهاية تساوي +مالانهاية.",
        "الخطوة 5: التفسير البياني الثاني: المنحنى (Cf) يقبل مستقيماً مقارباً عمودياً موازياً لمحور التراتيب معادلته x = 1.",
      ],
      finalAnswer_ar: "المقارب الأفقي: y = 2 بجوار اللانهاية، والمقارب العمودي: x = 1.",
      verificationTip_ar: "تذكر دائماً: عدد في النهاية يعطي y = L (أفقي)، بينما اللانهاية عند عدد تعطي x = a (عمودي).",
    },
    commonMistakes: [
      {
        id: "cm_math_asymp_xy_confusion",
        mistake_ar: "الخلط بين x و y في معادلة المستقيم المقارب وكتابة x = 2 بدلاً من y = 2 للمقارب الأفقي.",
        whyItHappens_ar: "السرعة وعدم مراجعة اتجاه محور الفواصل والتراتيب.",
        correctAction_ar: "المقارب الأفقي يقطع محور التراتيب فمعادلته y = const، والعمودي يقطع محور الفواصل فمعادلته x = const.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_math_asymp_neighborhood",
        mistake_ar: "إغفال ذكر الجوار (بجوار +مالانهاية أو -مالانهاية) عند التصريح بوجود مستقيم مقارب مائل أو أفقي.",
        whyItHappens_ar: "التركيز فقط على حساب النهاية ونسيان اشتراطات الصياغة النموذجية المعتمدة في تصحيح البكالوريا.",
        correctAction_ar: "اكتب دائماً الصياغة الكاملة: '(Cf) يقبل مستقيماً مقارباً معادلته y = b بجوار (+/- مالانهاية)'.",
        suspectedErrorType: "forgot_information",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت فور رؤية lim [f(x) - (3x - 1)] = 0 عند +مالانهاية أن تصرح مباشرة بأن المستقيم دلتا ذو المعادلة y = 3x - 1 مقارب مائل لـ (Cf).",
    quickRecallPrompt_ar: "إذا كانت نهاية f(x) لما x يؤول إلى 3 بقيم كبرى هي +مالانهاية، فما هو التفسير البياني؟",
    quickRecallAnswer_ar: "المنحنى يقبل مستقيماً مقارباً عمودياً معادلته x = 3.",
    practiceQuestionIds: ["pq-math-asymptotes-01", "pq-math-asymptotes-02"],
    whatToDoIfYouFail_ar: "راجع بطاقة مراجعة المقاربات وتدرب على التمييز البصري بين المقارب الأفقي والعمودي والمائل.",
    summaryCard: {
      id: "sc_math_asymp",
      keyRule_ar: "lim f(x) = b عند اللانهاية <=> مستقيم مقارب أفقي y = b.",
      keyFormula_ar: "lim [f(x) - (ax+b)] = 0 عند اللانهاية <=> مستقيم مقارب مائل y = ax + b.",
      trapToAvoid_ar: "لا تنس كتابة 'بجوار +مالانهاية أو -مالانهاية' عند ذكر المستقيمات المقاربة الأفقية والمائلة.",
    },
    retestQuestionId: "rq-math-asymptotes-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 04: math_tangent_convexity
  // ==========================================================================
  {
    id: "lesson_math_tangent_convexity",
    skillId: "math_tangent_convexity",
    subjectId: "math",
    topicId: "math_topic_functions",
    title_ar: "معادلة المماس ونقاط الانعطاف والوضعية النسبية للمنحنى",
    title_fr: "Équation de tangente, points d'inflexion et position relative",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من كتابة معادلة المماس عند أي فاصلة معطاة، وتحديد نقاط الانعطاف عبر المشتقة الأولى أو الثانية، ودراسة الوضعية النسبية بين المنحنى ومماسه بدقة متناهية.",
    whatYouMustKnow_ar: "قانون المماس y = f'(x_0)(x - x_0) + f(x_0) وحساب المشتقة الثانية f''(x).",
    whyThisMatters_ar: "رسم المماس ونقاط الانعطاف هو الركيزة الأساسية لرسم المنحنى البياني (Cf) بدقة في البكالوريا؛ الخطأ في المماس يشوه المنحنى ويفقدك نقاط الرسم الهندسي.",
    coreConcept_ar: "تنعدم المشتقة الثانية f''(x) مغيرّة إشارتها عند نقطة الانعطاف. وتحدد إشارة الفرق f(x) - y ما إذا كان المنحنى يقع فوق المماس أو تحته.",
    simpleExplanation_ar: "المماس يمس المنحنى عند نقطة، ولكن عند نقطة الانعطاف يخترق المماس المنحنى ويتحول التقعر من محدب إلى مقعر أو العكس.",
    workedExample: {
      id: "we_math_tangent_01",
      skillId: "math_tangent_convexity",
      problem_ar: "لتكن f(x) = x^3 - 3x + 1. 1) اكتب معادلة المماس (T) عند النقطة ذات الفاصلة x_0 = 0. 2) ادرس الوضعية النسبية لـ (Cf) بالنسبة لـ (T). 3) بين أن النقطة A(0, 1) نقطة انعطاف.",
      howToThink_ar: "نحسب f(0) و f'(0) لمعادلة المماس، ثم ندرس إشارة الفرق f(x) - y. ونشتق المشتقة الأولى لنحصل على المشتقة الثانية ونبحث عن انعدامها مع تغير الإشارة.",
      stepByStepSolution_ar: [
        "الخطوة 1: نحسب f(0) = 1، والمشتقة f'(x) = 3x^2 - 3 ومنه f'(0) = -3.",
        "الخطوة 2: نطبق قانون المماس: y = f'(0)(x - 0) + f(0) = -3x + 1.",
        "الخطوة 3: نحسب الفرق: f(x) - y = (x^3 - 3x + 1) - (-3x + 1) = x^3.",
        "الخطوة 4: ندرس إشارة x^3: سالبة لما x < 0 (المنحنى تحت المماس)، وموجبة لما x > 0 (المنحنى فوق المماس)، وتنعدم عند x = 0 حيث يقطع المنحنى المماس.",
        "الخطوة 5: المشتقة الثانية f''(x) = 6x تنعدم عند x = 0 وتغير إشارتها من السالب إلى الموجب، إذن النقطة A(0, 1) نقطة انعطاف للمنحنى (Cf).",
      ],
      finalAnswer_ar: "معادلة المماس: y = -3x + 1، والنقطة (0, 1) نقطة انعطاف يخترق فيها المماس المنحنى.",
      verificationTip_ar: "إذا اخترق المماس المنحنى عند نقطة التماس، فهذه النقطة حتماً نقطة انعطاف دون أدنى شك.",
    },
    commonMistakes: [
      {
        id: "cm_math_tangent_diff_sign",
        mistake_ar: "نسيان نشر إشارة الناقص على حدود معادلة المماس عند حساب الفرق f(x) - y.",
        whyItHappens_ar: "عدم وضع عبارة المماس بين قوسين بعد إشارة الطرح.",
        correctAction_ar: "اكتب دائماً: f(x) - (ax + b) وانشر الناقص بحذر: f(x) - ax - b.",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_math_inflection_no_sign_change",
        mistake_ar: "اعتبار انعدام المشتقة الثانية كافياً لوحده لوجود نقطة انعطاف دون التحقق من تغير الإشارة.",
        whyItHappens_ar: "حفظ غير دقيق للخاصية (مثل الدالة f(x) = x^4 مشتقتها الثانية 12x^2 تنعدم عند 0 ولا تغير إشارتها فلا توجد نقطة انعطاف).",
        correctAction_ar: "تحقق دائماً من أن المشتقة الثانية تنعدم وتغير إشارتها.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت إيجاد معادلة المماس الموازي لمستقيم معلوم بحل المعادلة f'(x) = m وإيجاد فواصل نقاط التماس بدقة.",
    quickRecallPrompt_ar: "متى تكون النقطة (x_0, f(x_0)) نقطة انعطاف للمنحنى البياني؟",
    quickRecallAnswer_ar: "إذا انعدمت المشتقة الثانية f''(x) عند x_0 وغيرت إشارتها، أو انعدمت المشتقة الأولى f'(x) عند x_0 ولم تغير إشارتها.",
    practiceQuestionIds: ["pq-math-tangent-01", "pq-math-tangent-02"],
    whatToDoIfYouFail_ar: "راجع جدول إشارة الفرق f(x) - y وقواعد التقعر والتحدب قبل محاولة حل مسائل البكالوريا السابقة.",
    summaryCard: {
      id: "sc_math_tangent",
      keyRule_ar: "المماس: y = f'(x_0)(x - x_0) + f(x_0).",
      keyFormula_ar: "نقطة الانعطاف: f''(x_0) = 0 مع تغير الإشارة.",
      trapToAvoid_ar: "احذر نسيان الأقواس عند طرح معادلة المماس: D(x) = f(x) - (ax + b).",
    },
    retestQuestionId: "rq-math-tangent-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 05: math_exponential_properties_equations
  // ==========================================================================
  {
    id: "lesson_math_exponential_properties_equations",
    skillId: "math_exponential_properties_equations",
    subjectId: "math",
    topicId: "math_topic_exp_ln",
    title_ar: "خواص الدالة الأسية وحل المعادلات والمتراجحات الأسية بتغيير المتغير",
    title_fr: "Propriétés de l'exponentielle et résolution d'équations par changement de variable",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تبسيط أصعب العبارات الأسية وحل المعادلات والمتراجحات من الدرجة الثانية بالنسبة لـ e^x مع استبعاد الحلول المرفوضة بحزم رياضي.",
    whatYouMustKnow_ar: "خواص القوى الصحيحة وحل معادلات الدرجة الثانية بالمميز دلتا.",
    whyThisMatters_ar: "حل المعادلات الأسية هو المفتاح لتحديد إحداثيات نقاط التقاطع مع المحاور، وحل متراجحات إشارة المشتقة وتعيين الوضع النسبي.",
    coreConcept_ar: "الدالة الأسية e^x موجبة تماماً دوماً على R (e^x > 0). والمعادلة e^u = e^v تكافئ u = v، بينما e^u = A (مع A > 0) تكافئ u = ln(A).",
    simpleExplanation_ar: "بما أن e^x لا يمكن أن تكون سالبة أو صفراً، فإن أي معادلة تؤدي إلى e^x = -2 مثلاً هي معادلة مستحيلة الحل مباشرة.",
    workedExample: {
      id: "we_math_exp_eq_01",
      skillId: "math_exponential_properties_equations",
      problem_ar: "حل في R المعادلة: e^(2x) - 3*e^x - 4 = 0",
      howToThink_ar: "نلاحظ أن e^(2x) هي (e^x)^2. هذه معادلة من الدرجة الثانية بالنسبة لـ e^x. نضع المتغير المساعد X = e^x مع الشرط الصارم X > 0.",
      stepByStepSolution_ar: [
        "الخطوة 1: نضع X = e^x مع اشتراط X > 0 قطعاً.",
        "الخطوة 2: تصبح المعادلة: X^2 - 3X - 4 = 0.",
        "الخطوة 3: نحسب المميز: Δ = (-3)^2 - 4(1)(-4) = 9 + 16 = 25 = 5^2.",
        "الخطوة 4: نستخرج جذري المعادلة: X_1 = (3 - 5)/2 = -1، و X_2 = (3 + 5)/2 = 4.",
        "الخطوة 5: نناقش شرط الموجبية: الحل X_1 = -1 مرفوض لأن e^x > 0 دوماً. الحل X_2 = 4 مقبول: e^x = 4 ومنه x = ln(4) = 2*ln(2).",
      ],
      finalAnswer_ar: "مجموعة الحلول هي: S = {ln(4)} أو S = {2*ln(2)}.",
      verificationTip_ar: "عوض x = ln(4) في المعادلة الأصلية: (4)^2 - 3(4) - 4 = 16 - 12 - 4 = 0. النتيجة صحيحة ومحققة 100%.",
    },
    commonMistakes: [
      {
        id: "cm_math_exp_negative_root",
        mistake_ar: "قبول الحل السالب X = -1 وكتابة x = ln(-1) في ورقة الإجابة.",
        whyItHappens_ar: "نسيان أن اللوغاريتم غير معرف على الأعداد السالبة وأن الدالة الأسية موجبة تماماً دوماً.",
        correctAction_ar: "اكتب فوراً بجانب الحل السالب: 'مرفوض لأن e^x > 0 دوماً لكل x من R'.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_math_exp_power_rule",
        mistake_ar: "الخلط بين e^(2x) و (e^x + 2) أو كتابة e^(x^2) بدلاً من e^(2x).",
        whyItHappens_ar: "عدم التمييز الدقيق بين (e^a)^b = e^(a*b) وبين جمع القوى e^a * e^b = e^(a+b).",
        correctAction_ar: "تذكر أن (e^x)^2 = e^(2x).",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت حل المتراجحة e^(2x) - e^x - 6 <= 0 واستنتاج أن x <= ln(3) في أقل من دقيقتين.",
    quickRecallPrompt_ar: "ما هي حلول المعادلة e^x = -5 في مجموعة الأعداد الحقيقية R؟",
    quickRecallAnswer_ar: "المعادلة مستحيلة الحل في R (مجموعة الحلول خالية ∅) لأن e^x موجب تماماً دوماً لكل x حقيقي.",
    practiceQuestionIds: ["pq-math-exp-eq-01", "pq-math-exp-eq-02"],
    whatToDoIfYouFail_ar: "تدرب على كتابة شرط X > 0 فور وضع تغيير المتغير وقبل حساب المميز دلتا لتفادي فخاخ الأعداد السالبة.",
    summaryCard: {
      id: "sc_math_exp_eq",
      keyRule_ar: "e^x > 0 دوماً على R. و e^a = e^b <=> a = b.",
      keyFormula_ar: "e^(a+b) = e^a * e^b  و  (e^a)^n = e^(n*a).",
      trapToAvoid_ar: "لا تقبل أبداً حلاً سالباً للمتغير X = e^x؛ ارفضه فوراً واشرح السبب.",
    },
    retestQuestionId: "rq-math-exp-eq-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 06: math_logarithm_domain_limits
  // ==========================================================================
  {
    id: "lesson_math_logarithm_domain_limits",
    skillId: "math_logarithm_domain_limits",
    subjectId: "math",
    topicId: "math_topic_exp_ln",
    title_ar: "مجموعة تعريف الدالة اللوغاريتمية وحساب النهايات والشهيرة (التزايد المقارن)",
    title_fr: "Domaine de définition du logarithme, calcul des limites et croissances comparées",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تعيين مجال تعريف أي دالة لوغاريتمية مركبة وحساب نهاياتها عند الأطراف وإزالة حالات عدم التعيين باستعمال التزايد المقارن ببراعة.",
    whatYouMustKnow_ar: "خواص اللوغاريتم النيبيري: ln(a*b) = ln(a) + ln(b)، ln(a/b) = ln(a) - ln(b)، و ln(1) = 0، ln(e) = 1.",
    whyThisMatters_ar: "الخطأ في مجموعة تعريف الدالة اللوغاريتمية ينسف المسألة من بدايتها، ونهايات التزايد المقارن تتكرر سنوياً في بكالوريا العلوم التجريبية.",
    coreConcept_ar: "العبارة ln(u(x)) معرفة إذا وفقط إذا كان u(x) > 0 تماماً. والنهايات الشهيرة عند +مالانهاية هي: lim (ln x / x) = 0 و lim (x * ln x) = 0 عند 0 بقيم كبرى.",
    simpleExplanation_ar: "الدالة اللوغاريتمية تنمو ببطء شديد جداً مقارنة بالدوال القوى، ولذلك عند اللانهاية 'يغلب' x دائماً ويجعل حاصل قسمة ln(x)/x يؤول إلى الصفر.",
    workedExample: {
      id: "we_math_log_01",
      skillId: "math_logarithm_domain_limits",
      problem_ar: "1) عين مجموعة تعريف الدالة f(x) = ln((2x - 4)/(x + 1)). 2) احسب نهاية الدالة g(x) = x - ln(x) عند +مالانهاية.",
      howToThink_ar: "لمجموعة التعريف: ما بداخل اللوغاريتم يجب أن يكون موجباً تماماً والمقام غير معدوم (ندرس إشارة الكسر بجدول إشارة). ولنهاية g(x): لدينا حالة عدم تعيين (+∞ - ∞)، نستخرج x عاملاً مشتركاً لظهور النهاية الشهيرة ln(x)/x.",
      stepByStepSolution_ar: [
        "الخطوة 1: شرط الوجود: (2x - 4)/(x + 1) > 0 مع x != -1.",
        "الخطوة 2: جدول إشارة الكسر: ينعدم البسط عند x = 2 والمقام عند x = -1. الكسر موجب في المجالين: ]-∞, -1[ و ]2, +∞[. إذن D_f = ]-∞, -1[ U ]2, +∞[.",
        "الخطوة 3: لحساب lim g(x) عند +مالانهاية: g(x) = x * [1 - ln(x)/x].",
        "الخطوة 4: نعلم أن lim (ln(x)/x) = 0 عند +مالانهاية (نهاية شهيرة بالتزايد المقارن).",
        "الخطوة 5: إذن ما بين القوسين يؤول إلى [1 - 0] = 1، وبما أن x يؤول إلى +مالانهاية، فإن نهاية الجداء هي: +مالانهاية * 1 = +مالانهاية.",
      ],
      finalAnswer_ar: "مجموعة التعريف: D_f = ]-∞, -1[ U ]2, +∞[ والنهاية: lim g(x) = +مالانهاية.",
      verificationTip_ar: "عند وجود حالة عدم تعيين بين x و ln(x) عند +مالانهاية، فكر فوراً في استخراج x كعامل مشترك لإظهار ln(x)/x.",
    },
    commonMistakes: [
      {
        id: "cm_math_log_domain_split",
        mistake_ar: "كتابة شرط مجموعة تعريف ln(A/B) على شكل: A > 0 و B > 0 فقط وإهمال حالة A < 0 و B < 0.",
        whyItHappens_ar: "نسيان أن حاصل قسمة عددين سالبين هو عدد موجب تماماً ويصلح وضعه داخل اللوغاريتم.",
        correctAction_ar: "ضع جدول إشارة كامل للكسر كاملاً واختر المجالات التي يكون فيها الكسر موجباً تماماً.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_math_log_zero_limit",
        mistake_ar: "اعتبار أن نهاية ln(x)/x عند 0 بقيم كبرى هي 0.",
        whyItHappens_ar: "الخلط بين النهاية عند +مالانهاية (التي تساوي 0) وبين النهاية عند 0 (حيث ln(0+) = -∞ والمقام 0+ فالناتج -∞).",
        correctAction_ar: "طبق النهاية الشهيرة بحذر: lim (ln x / x) = 0 تكون فقط لما x يؤول إلى +مالانهاية.",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت إزالة عدم التعيين في lim (x^2 - ln x) عند +مالانهاية واستخراج العامل المشترك وتبرير الناتج بالتزايد المقارن في أقل من دقيقة.",
    quickRecallPrompt_ar: "ما هي قيمة النهاية الشهيرة lim (x * ln x) لما x يؤول إلى 0 بقيم كبرى؟",
    quickRecallAnswer_ar: "تساوي 0 (نهاية شهيرة بالتزايد المقارن).",
    practiceQuestionIds: ["pq-math-log-limits-01", "pq-math-log-limits-02"],
    whatToDoIfYouFail_ar: "راجع قائمة النهايات الشهيرة الأربع للدالة اللوغاريتمية واكتبها على بطاقة ملخص قبل إعادة المحاولة.",
    summaryCard: {
      id: "sc_math_log_limits",
      keyRule_ar: "ln(u) معرفة <=> u > 0 تماماً. ومشتقتها [ln u]' = u' / u.",
      keyFormula_ar: "lim_{x->+∞} (ln x / x) = 0  و  lim_{x->0^+} (x ln x) = 0.",
      trapToAvoid_ar: "إياك وقسمة ln(a)/ln(b) وكتابتها ln(a - b)؛ الخاصية الصحيحة هي ln(a/b) = ln a - ln b.",
    },
    retestQuestionId: "rq-math-log-limits-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 07: math_induction_reasoning
  // ==========================================================================
  {
    id: "lesson_math_induction_reasoning",
    skillId: "math_induction_reasoning",
    subjectId: "math",
    topicId: "math_topic_sequences",
    title_ar: "الاستدلال بالتراجع: مرحلة التحقق، الفرضية، وإثبات الوراثة",
    title_fr: "Raisonnement par récurrence : initialisation, hérédité et conclusion",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تحرير برهان بالتراجع كامل ودقيق في تمرين المتتاليات وفق الصياغة المنهجية النموذجية المعتمدة.",
    whatYouMustKnow_ar: "مفهوم المتتالية التراجعية u_(n+1) = f(u_n) والتعويض بدلالة n.",
    whyThisMatters_ar: "البرهان بالتراجع هو السؤال الأول الحتمي في تمرين المتتاليات في كل دورات البكالوريا (مثل إثبات أن 0 < u_n < 2). صياغته المنهجية هي مفتاح بقية التمرين.",
    coreConcept_ar: "البرهان بالتراجع يعتمد على خطوتين متكاملتين: 1) التحقق من صحة الخاصية عند الرتبة الأولى n_0، 2) إثبات أن صحة الخاصية عند رتبة كيفية n تستلزم صحتها عند الرتبة الموالية n+1.",
    simpleExplanation_ar: "مثل قطع الدومينو المتراصة: إذا سقطت القطعة الأولى (التحقق)، وكان سقوط أي قطعة يسقط القطعة التي تليها حتماً (الوراثة)، فإن جميع قطع الدومينو ستسقط بالضرورة.",
    workedExample: {
      id: "we_math_ind_01",
      skillId: "math_induction_reasoning",
      problem_ar: "لتكن المتتالية (u_n) المعرفة بـ: u_0 = 1 و u_(n+1) = (1/2) * u_n + 1 لكل n طبيعي. برهن بالتراجع أنه من أجل كل عدد طبيعي n: u_n < 2.",
      howToThink_ar: "نسمي الخاصية P(n): 'u_n < 2'. نتحقق عند n=0، ثم نفرض صحة P(n) وننطلق منها بالبناء الجبري أو بالدالة المرفقة للوصول إلى u_(n+1) < 2.",
      stepByStepSolution_ar: [
        "الخطوة 1: نسمي الخاصية P(n): 'u_n < 2' من أجل كل n ينتمي إلى N.",
        "الخطوة 2: مرحلة التحقق (الابتداء): من أجل n = 0 لدينا u_0 = 1 وبما أن 1 < 2 فإن الخاصية P(0) محققة.",
        "الخطوة 3: مرحلة الوراثة: ليكن n عدداً طبيعياً كيفياً. نفرض أن الخاصية P(n) صحيحة (أي u_n < 2) ونبرهن صحة الخاصية P(n+1) (أي نبرهن أن u_(n+1) < 2).",
        "الخطوة 4: الانطلاق من الفرضية: لدينا بالفرض u_n < 2. نضرب الطرفين في 1/2 (عدد موجب تماماً): (1/2)*u_n < 1. نضيف 1 إلى الطرفين: (1/2)*u_n + 1 < 2. أي أن u_(n+1) < 2، وبالتالي P(n+1) صحيحة.",
        "الخطوة 5: الخلاصة: حسب مبدأ الاستدلال بالتراجع، فإنه من أجل كل عدد طبيعي n: u_n < 2.",
      ],
      finalAnswer_ar: "الخاصية u_n < 2 صحيحة من أجل كل عدد طبيعي n.",
      verificationTip_ar: "احرص على كتابة الجملة المنهجية بدقة: 'نفرض صحة P(n) ونبرهن صحة P(n+1)' ولا تكتب أبداً 'نفرض أن P(n+1) صحيحة'.",
    },
    commonMistakes: [
      {
        id: "cm_math_ind_circular_reasoning",
        mistake_ar: "الانطلاق من المطلوب u_(n+1) < 2 ومحاولة تبسيطه للوصول إلى شيء بديهي.",
        whyItHappens_ar: "عدم إدراك أن الانطلاق من النتيجة يعتبر استدلالاً دائرياً باطلاً في سلم التنقيط.",
        correctAction_ar: "انطلق دائماً من الفرضية u_n < 2 وابنِ عبارة u_(n+1) خطوة بخطوة بالعمليات المتراجحة.",
        suspectedErrorType: "methodology_error",
      },
      {
        id: "cm_math_ind_omit_conclusion",
        mistake_ar: "التوقف فور الوصول إلى u_(n+1) < 2 دون كتابة الخاتمة المنهجية.",
        whyItHappens_ar: "التسرع بعد الانتهاء من العمليات الحسابية.",
        correctAction_ar: "اختم دوماً بجملة: 'وحسب مبدأ الاستدلال بالتراجع، الخاصية P(n) محققة من أجل كل n'.",
        suspectedErrorType: "forgot_information",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت إثبات متراجحة حصر للمتتالية بالتراجع باستعمال اتجاه تغير الدالة المرفقة f المتزايدة تماماً دون خطأ.",
    quickRecallPrompt_ar: "ما هي المراحل الثلاث الأساسية بالترتيب في الاستدلال بالتراجع؟",
    quickRecallAnswer_ar: "1) مرحلة الابتداء (التحقق عند الرتبة الأولى)، 2) مرحلة الوراثة (فرض P(n) وإثبات P(n+1))، 3) الاستنتاج والخلاصة.",
    practiceQuestionIds: ["pq-math-induction-01", "pq-math-induction-02"],
    whatToDoIfYouFail_ar: "تدرب على بناء عبارة u_(n+1) بالضرب والجمع خطوة بخطوة أو بتطبيق الدالة f إذا كانت متزايدة تماماً.",
    summaryCard: {
      id: "sc_math_induction",
      keyRule_ar: "الاستدلال بالتراجع: تحقق عند n_0 + وراثة (P(n) => P(n+1)) + خلاصة.",
      keyFormula_ar: "انطلق من: u_n < L ، اضرب في a وأضف b للوصول إلى u_(n+1) < L.",
      trapToAvoid_ar: "إياك والانطلاق من P(n+1)؛ الانطلاق يجب أن يكون حصرياً من فرضية التراجع P(n).",
    },
    retestQuestionId: "rq-math-induction-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 08: math_sequence_reasoning
  // ==========================================================================
  {
    id: "lesson_math_sequence_reasoning",
    skillId: "math_sequence_reasoning",
    subjectId: "math",
    topicId: "math_topic_sequences",
    title_ar: "دراسة اتجاه تغير المتتاليات العددية والتقارب بمبرهنة الرتابة والمحدودية",
    title_fr: "Sens de variation des suites numériques et convergence (théorème de la limite monotone)",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من دراسة إشارة الفرق u_(n+1) - u_n وتحديد رتابة المتتالية، وتطبيق مبرهنة التقارب الشهيرة (كل متتالية متزايدة ومحدودة من الأعلى هي متقاربة).",
    whatYouMustKnow_ar: "طريقة حساب الفرق u_(n+1) - u_n وتبسيطه، ومفهوم المتتالية المحدودة من الأعلى أو من الأسفل.",
    whyThisMatters_ar: "مبرهنة التقارب هي الجسر الرابط بين المتتاليات والنهايات في البكالوريا؛ إجابتها المنهجية تتطلب خطوات واضحة ومحددة تعزز إجابتك النموذجية.",
    coreConcept_ar: "تكون المتتالية (u_n) متزايدة إذا كان u_(n+1) - u_n >= 0، وتكون متناقصة إذا كان u_(n+1) - u_n <= 0. وكل متتالية متزايدة ومحدودة من الأعلى (أو متناقصة ومحدودة من الأسفل) هي متتالية متقاربة نحو نهاية حقيقية L.",
    simpleExplanation_ar: "إذا كنت تصعد درجات سلم (متزايدة) وكان هناك سقف يمنعك من تجاوزه (محدودة من الأعلى)، فلا بد أن تقترب خطواتك تدريجياً من حد معين ولا تتجاوزه أبداً.",
    workedExample: {
      id: "we_math_seq_01",
      skillId: "math_sequence_reasoning",
      problem_ar: "لتكن المتتالية (u_n) حيث u_n < 3 لكل n، و u_(n+1) - u_n = (1/4)*(3 - u_n). 1) بين اتجاه تغير (u_n). 2) هل المتتالية (u_n) متقاربة؟ برر إجابتك.",
      howToThink_ar: "لدراسة اتجاه التغير ندرس إشارة عبارة الفرق المعطاة. وبما أن لدينا حصر u_n < 3 فإن (3 - u_n) موجبة. وللتقارب نربط بين الرتابة والمحدودية.",
      stepByStepSolution_ar: [
        "الخطوة 1: لدينا u_n < 3 من أجل كل n، مما يستلزم أن 3 - u_n > 0 تماماً.",
        "الخطوة 2: نضرب في 1/4 الموجب: u_(n+1) - u_n = (1/4)*(3 - u_n) > 0 تماماً.",
        "الخطوة 3: بما أن u_(n+1) - u_n > 0 فإن المتتالية (u_n) متزايدة تماماً على N.",
        "الخطوة 4: نطبق مبرهنة التقارب: بما أن المتتالية (u_n) متزايدة تماماً ومحدودة من الأعلى بالعدد 3، فإنها متتالية متقاربة نحو عدد حقيقي L.",
      ],
      finalAnswer_ar: "المتتالية (u_n) متزايدة تماماً ومتقاربة نحو نهاية حقيقية L.",
      verificationTip_ar: "انتبه: محدوديتها بالعدد 3 لا يعني بالضرورة أن نهايتها هي 3؛ مبرهنة التقارب تثبت وجود النهاية L فقط، وحساب L يتم بحل المعادلة f(L) = L.",
    },
    commonMistakes: [
      {
        id: "cm_math_seq_convergence_confusion",
        mistake_ar: "كتابة أن المتتالية 'متناقصة ومحدودة من الأعلى إذن متقاربة'.",
        whyItHappens_ar: "الخلط بين شروط التقارب بالرتابة.",
        correctAction_ar: "احفظ الزوجين بدقة: (متزايدة + محدودة من الأعلى) أو (متناقصة + محدودة من الأسفل).",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_math_seq_algebra_diff",
        mistake_ar: "الخطأ في توحيد المقامات عند حساب الفرق u_(n+1) - u_n.",
        whyItHappens_ar: "التسرع وعدم وضع أقواس حول عبارة u_n قبل طرحها.",
        correctAction_ar: "ضع u_n بين قوسين إجباريين: u_(n+1) - (u_n) ووحد المقامات بحذر.",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت فور إثبات أن المتتالية متناقصة ولها حد سفلي أن تصيغ نص مبرهنة التقارب كاملاً في ورقة الإجابة في 30 ثانية.",
    quickRecallPrompt_ar: "أكمل نص المبرهنة: كل متتالية عددية متناقصة ومحدودة من ........... هي متتالية متقاربة.",
    quickRecallAnswer_ar: "الأسفل (minorée).",
    practiceQuestionIds: ["pq-math-seq-01", "pq-math-seq-02"],
    whatToDoIfYouFail_ar: "راجع علامات الترتيب وتوحيد المقامات في الفرق u_(n+1) - u_n وراجع مبرهنة المتتالية الرتيبة.",
    summaryCard: {
      id: "sc_math_sequence",
      keyRule_ar: "u_(n+1) - u_n > 0 => متزايدة. و u_(n+1) - u_n < 0 => متناقصة.",
      keyFormula_ar: "متزايدة + محدودة من الأعلى => متقاربة. متناقصة + محدودة من الأسفل => متقاربة.",
      trapToAvoid_ar: "المتتالية المتزايدة يجب أن تكون محدودة من الأعلى لتتقارب، والمحدودية من الأسفل لا تكفي.",
    },
    retestQuestionId: "rq-math-seq-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 09: math_arithmetic_geometric_auxiliary
  // ==========================================================================
  {
    id: "lesson_math_arithmetic_geometric_auxiliary",
    skillId: "math_arithmetic_geometric_auxiliary",
    subjectId: "math",
    topicId: "math_topic_sequences",
    title_ar: "المتتاليات المساعدة الحسابية والهندسية وكتابة عبارة الحد العام والمجاميع",
    title_fr: "Suites auxiliaires arithmétiques et géométriques, terme général et calcul de sommes",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من إثبات أن المتتالية المساعدة v_n هندسية بتعيين أساسها q وحدها الأول، وكتابة عبارة الحد العام لـ v_n ثم استنتاج u_n وحساب المجاميع والجداءات بدقة تامة.",
    whatYouMustKnow_ar: "تعريف المتتالية الهندسية: v_(n+1) = q * v_n، وقانون الحد العام v_n = v_0 * q^n، وقانون مجموع حدود متتابعة.",
    whyThisMatters_ar: "هذا الجزء هو صلب تمرين المتتاليات في البكالوريا ويمثل الخطوة المحورية في الربط بين المتتالية المعطاة وحساب الحدود والمجاميع.",
    coreConcept_ar: "لإثبات أن (v_n) هندسية، ننطلق من v_(n+1)، نعوض u_(n+1) بعبارتها، ونبسط حتى نستخرج عاملاً مشتركاً q يترك لنا عبارة v_n الأصلية: v_(n+1) = q * v_n.",
    simpleExplanation_ar: "المتتالية الأصلية u_n معقدة وليست هندسية، ولكن بإدخال المتتالية المساعدة v_n = u_n - alpha نحوّلها إلى هندسية بسيطة يسهل حساب حدها العام ومجموعها، ثم نعود لعكس العلاقة واستخراج u_n.",
    workedExample: {
      id: "we_math_geom_01",
      skillId: "math_arithmetic_geometric_auxiliary",
      problem_ar: "لتكن u_(n+1) = 3*u_n - 4 مع u_0 = 3. ونعرف المتتالية (v_n) بـ: v_n = u_n - 2. 1) أثبت أن (v_n) متتالية هندسية يطلب تعيين أساسها وحدها الأول. 2) اكتب عبارة v_n ثم u_n بدلالة n.",
      howToThink_ar: "نحسب v_(n+1) = u_(n+1) - 2، نعوض عبارة u_(n+1)، ثم نستخرج العامل المشترك 3 لنحصل على 3*(u_n - 2) التي هي بالضبط 3*v_n.",
      stepByStepSolution_ar: [
        "الخطوة 1: ننطلق من تعريف v_(n+1): v_(n+1) = u_(n+1) - 2.",
        "الخطوة 2: نعوض u_(n+1) بعبارتها: v_(n+1) = (3*u_n - 4) - 2 = 3*u_n - 6.",
        "الخطوة 3: نستخرج 3 كعامل مشترك: v_(n+1) = 3*(u_n - 2) = 3 * v_n.",
        "الخطوة 4: الخلاصة: المتتالية (v_n) هندسية أساسها q = 3 وحدها الأول v_0 = u_0 - 2 = 3 - 2 = 1.",
        "الخطوة 5: عبارة الحد العام: v_n = v_0 * q^n = 1 * 3^n = 3^n. ومنه نستنتج u_n: بما أن v_n = u_n - 2، فإن u_n = v_n + 2 = 3^n + 2.",
      ],
      finalAnswer_ar: "المتتالية (v_n) هندسية أساسها q = 3، و v_n = 3^n، ومنه u_n = 3^n + 2.",
      verificationTip_ar: "تحقق دائماً بحساب الحد التالي: u_1 = 3*(3) - 4 = 5. وبالعبارة العامة المستنتجة: u_1 = 3^1 + 2 = 5. النتيجة متطابقة تماماً.",
    },
    commonMistakes: [
      {
        id: "cm_math_geom_power_offset",
        mistake_ar: "كتابة عبارة الحد العام v_n = v_1 * q^n بدلاً من v_1 * q^(n-1) عند انطلاق المتتالية من الحد الأول v_1.",
        whyItHappens_ar: "حفظ الصيغة المنطلقة من v_0 وتطبيقها آلياً دون الانتباه للحد الأول.",
        correctAction_ar: "طبق القانون العام الصارم: v_n = v_p * q^(n-p) حيث v_p هو الحد الأول.",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_math_geom_sum_formula",
        mistake_ar: "الخطأ في عدد الحدود في قانون المجموع: عدد الحدود = (دليل النهاية - دليل البداية + 1).",
        whyItHappens_ar: "نسيان إضافة 1 وحساب n بدلاً من n+1 عند الجمع من 0 إلى n.",
        correctAction_ar: "احفظ دوماً: عدد حدود المجموع من v_0 إلى v_n هو (n - 0 + 1) = n + 1 حداً.",
        suspectedErrorType: "forgot_information",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت حساب المجموع S_n = v_0 + v_1 + ... + v_n واستنتاج المجموع T_n = u_0 + u_1 + ... + u_n بفصل الثوابت في أقل من 3 دقائق.",
    quickRecallPrompt_ar: "ما هو قانون مجموع n+1 حداً الأولى لمتتالية هندسية أساسها q != 1 وحدها الأول v_0؟",
    quickRecallAnswer_ar: "S = v_0 * (1 - q^(n+1)) / (1 - q)",
    practiceQuestionIds: ["pq-math-geom-aux-01", "pq-math-geom-aux-02"],
    whatToDoIfYouFail_ar: "تدرب على استخراج العامل المشترك عند حساب v_(n+1) ومراجعة قوانين المجاميع الهندسية في بطاقة المراجعة.",
    summaryCard: {
      id: "sc_math_geom_aux",
      keyRule_ar: "إثبات هندسية: v_(n+1) = q * v_n. الحد العام: v_n = v_0 * q^n.",
      keyFormula_ar: "مجموع هندسية: S = الحد الأول * (1 - q^(عدد الحدود)) / (1 - q).",
      trapToAvoid_ar: "لا تنس إضافة 1 عند حساب عدد الحدود: عدد الحدود = دليل النهاية - دليل البداية + 1.",
    },
    retestQuestionId: "rq-math-geom-aux-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 10: math_conditional_probability_tree
  // ==========================================================================
  {
    id: "lesson_math_conditional_probability_tree",
    skillId: "math_conditional_probability_tree",
    subjectId: "math",
    topicId: "math_topic_probability",
    title_ar: "الاحتمالات الشرطية وشجرة الاحتمالات وقانون الاحتمال الكلي ودستور بايز",
    title_fr: "Probabilités conditionnelles, arbre pondéré, formule des probabilités totales et formule de Bayes",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من إنشاء شجرة احتمالات متوازنة، وتطبيق قانون الاحتمال الكلي لحساب احتمال حادثة مجهولة، وحساب الاحتمال العكسي P_B(A) باستعمال دستور بايز بدقة مطلقة.",
    whatYouMustKnow_ar: "قواعد الاحتمال الأساسية، تقاطع الحوادث A ∩ B، وخواص شجرة الاحتمالات (مجموع احتمالات الفروع الخارجة من نفس العقدة يساوي 1).",
    whyThisMatters_ar: "مسائل الاحتمالات في بكالوريا العلوم التجريبية تعتمد بنسبة تتجاوز 90% على شجرة الاحتمالات والاحتمال الكلي؛ أي خطأ في فرع ينعكس على حساب الأمل الرياضي للمتغير العشوائي.",
    coreConcept_ar: "احتمال تقاطع حادثتين هو جداء الاحتمالات على طول المسار: P(A ∩ B) = P(A) * P_A(B). وقانون الاحتمال الكلي يجمع احتمالات المسارات المؤدية إلى نفس الحادثة.",
    simpleExplanation_ar: "تخيل شجرة الاحتمالات كشبكة طرق: كل فرع له احتمال، ولكي تصل إلى نهاية مسار معين تضرب احتمالات الطرق التي مررت بها، ولكي تجمع احتمال وصول عدة طرق تجمع نواتجها.",
    workedExample: {
      id: "we_math_prob_01",
      skillId: "math_conditional_probability_tree",
      problem_ar: "في ورشة تصنع مصابيح: الآلة M1 تنتج 60% من المصابيح ونسبة العيب فيها 2%. الآلة M2 تنتج 40% ونسبة العيب فيها 5%. نختار مصباحاً عشوائياً. 1) شكل شجرة الاحتمالات. 2) احسب احتمال أن يكون المصباح معيباً P(D). 3) إذا كان المصباح معيباً، ما احتمال أنه صُنع بالآلة M1؟",
      howToThink_ar: "نحدد الحوادث: M1 و M2 يشكلان تجزئة لفضاء العينة. D هو العيب. نطبق قانون الاحتمال الكلي لحساب P(D)، ثم نطبق تعريف الاحتمال الشرطي العكسي P(M1/D) = P(M1 ∩ D) / P(D).",
      stepByStepSolution_ar: [
        "الخطوة 1: المعطيات: P(M1) = 0.60 و P(M2) = 0.40. احتمالات العيب الشرطية: P_{M1}(D) = 0.02 و P_{M2}(D) = 0.05.",
        "الخطوة 2: نحسب تقاطع كل فرع مع العيب D: P(M1 ∩ D) = P(M1) * P_{M1}(D) = 0.60 * 0.02 = 0.012.",
        "الخطوة 3: نحسب التقاطع الثاني: P(M2 ∩ D) = P(M2) * P_{M2}(D) = 0.40 * 0.05 = 0.020.",
        "الخطوة 4: نطبق قانون الاحتمال الكلي: P(D) = P(M1 ∩ D) + P(M2 ∩ D) = 0.012 + 0.020 = 0.032 (أي 3.2%).",
        "الخطوة 5: نحسب الاحتمال الشرطي العكسي (دستور بايز): P_D(M1) = P(M1 ∩ D) / P(D) = 0.012 / 0.032 = 12 / 32 = 3 / 8 = 0.375.",
      ],
      finalAnswer_ar: "احتمال العيب الكلي P(D) = 0.032، واحتمال كونه من M1 علماً أنه معيب هو 3/8 (أو 37.5%).",
      verificationTip_ar: "تأكد دوماً من أن مجموع فروع كل عقدة يساوي 1: P(D) + P(D_bar) = 1، وأن الاحتمال الناتج محصور دوماً في المجال [0, 1].",
    },
    commonMistakes: [
      {
        id: "cm_math_prob_condition_order",
        mistake_ar: "الخلط بين P_B(A) و P_A(B) عند قراءة نص المسألة.",
        whyItHappens_ar: "عدم الانتباه لصياغة 'علماً أن' أو 'إذا كان'؛ الحادثة التي تلي 'علماً أن' هي الشرط وتوضع في المقام كدليل سفلي.",
        correctAction_ar: "المعلوم يوضع في الأسفل: P_{المعلوم}(المطلوب) = P(المطلوب ∩ المعلوم) / P(المعلوم).",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_math_prob_percent_decimal",
        mistake_ar: "الخطأ في تحويل النسب المئوية مثل كتابة 2% على شكل 0.2 بدلاً من 0.02.",
        whyItHappens_ar: "السرعة في الحساب الذهني دون استعمال الآلة الحاسبة.",
        correctAction_ar: "اقسم النسبة دوماً على 100: 2% = 2/100 = 0.02.",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت استنتاج قانون الاحتمال لمتغير عشوائي X مرتبط بتكلفة العيوب وحساب أمله الرياضي E(X) بنجاح.",
    quickRecallPrompt_ar: "اكتب قانون الاحتمال الكلي لحادثة B بالنسبة لتجزئة مكونة من حادثتين A و A_bar.",
    quickRecallAnswer_ar: "P(B) = P(A ∩ B) + P(A_bar ∩ B) = P(A)*P_A(B) + P(A_bar)*P_{A_bar}(B)",
    practiceQuestionIds: ["pq-math-prob-tree-01", "pq-math-prob-tree-02"],
    whatToDoIfYouFail_ar: "أعد رسم شجرة الاحتمالات بفرعين رئيسيين وفرعين ثانويين وتأكد من كتابة الاحتمالات الشرطية على الفروع الثانوية.",
    summaryCard: {
      id: "sc_math_prob_tree",
      keyRule_ar: "التقاطع: P(A ∩ B) = P(A) * P_A(B). الاحتمال الشرطي: P_B(A) = P(A ∩ B) / P(B).",
      keyFormula_ar: "الاحتمال الكلي: P(B) = Σ P(A_i ∩ B) = Σ P(A_i) * P_{A_i}(B).",
      trapToAvoid_ar: "انتبه لما يلي عبارة 'علماً أن'؛ فهذا هو الشرط الذي يوضع في مقام الكسر.",
    },
    retestQuestionId: "rq-math-prob-tree-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
