/**
 * BAC Mastery — Physics-Chemistry Lessons Catalog (Sciences Expérimentales 3AS)
 * Prompt 13: High-Yield, Active, Exam-Oriented Lessons (14-Element Structure)
 * 
 * 14 Skills covered with complete pedagogical loops.
 * Invariant: Content Purity (ZERO user_id).
 */

import { Lesson } from "../types";

export const PHYSICS_LESSONS: Lesson[] = [
  // ==========================================================================
  // LESSON 11: physics_reaction_rate_monitoring
  // ==========================================================================
  {
    id: "lesson_physics_reaction_rate_monitoring",
    skillId: "physics_reaction_rate_monitoring",
    subjectId: "physics",
    topicId: "physics_topic_kinetics",
    title_ar: "المتابعة الزمنية لتحول كيميائي: السرعة الحجمية للتفاعل وزمن نصف التفاعل t_{1/2}",
    title_fr: "Suivi temporel d'une réaction chimique : vitesse volumique et temps de demi-réaction",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من استخراج السرعة الحجمية للتفاعل v_vol بيانياً من ميل مماس المنحنى x(t) أو منحنيات النواتج والمتفاعلات، وتحديد زمن نصف التفاعل t_{1/2} بدقة مطلقة.",
    whatYouMustKnow_ar: "جدول تقدم التفاعل الكيميائي، والتمييز بين كمية المادة n(t) والتقدم x(t)، وقانون السرعة الحجمية v = (1/V_tot) * (dx/dt).",
    whyThisMatters_ar: "حساب السرعة وتحديد زمن نصف التفاعل سؤال محوري في تمرين الكيمياء الأول للبكالوريا؛ نسيان القسمة على الحجم الكلي V_tot يفقد إجابتك الدقة الفيزيائية والمنهجية المطلوبة.",
    coreConcept_ar: "السرعة الحجمية للتفاعل تساوي ميل مماس منحنى التقدم x(t) مقسوماً على الحجم الكلي للمزيج التفاعلي V_tot. وزمن نصف التفاعل t_{1/2} هو المدة اللازمة لبلوغ التقدم نصف قيمته النهائية x_f/2.",
    simpleExplanation_ar: "الميل يمثل سرعة التغير اللحظية لكمية المادة. ولكن بما أن التفاعل يحدث داخل حجم سائل، فنحن نقسم على الحجم الكلي حتى لا تتأثر القيمة بمدى تخفيف المحلول.",
    workedExample: {
      id: "we_phys_kinetics_01",
      skillId: "physics_reaction_rate_monitoring",
      problem_ar: "في تحول كيميائي تام حجمه V_tot = 100 mL، يمثل المنحنى تطور التقدم x(t) بالميلي مول. يقطع مماس المنحنى عند اللحظة t = 0 النقطتين (0, 0) و (10 min, 4 mmol). احسب السرعة الحجمية الابتدائية للتفاعل v_vol(0).",
      howToThink_ar: "نحسب ميل المماس a = Δx / Δt أولاً مع تحويل الميلي مول إلى مول والدقيقة إلى ثانية (أو تركها بـ min^-1 إذا لم يُشترط SI)، ثم نقسم الميل على الحجم الكلي المحول إلى اللتر V_tot = 0.1 L.",
      stepByStepSolution_ar: [
        "الخطوة 1: نحدد إحداثيات نقطتين من المماس: (t_1 = 0 min, x_1 = 0 mmol) و (t_2 = 10 min, x_2 = 4 mmol).",
        "الخطوة 2: نحسب ميل المماس: a = dx/dt = (4 - 0) / (10 - 0) = 0.4 mmol/min.",
        "الخطوة 3: نحول المقادير إلى الوحدات المتناسقة: a = 0.4 * 10^(-3) mol/min، والحجم الكلي V_tot = 100 mL = 0.100 L.",
        "الخطوة 4: نطبق قانون السرعة الحجمية: v_vol = (1 / V_tot) * (dx / dt).",
        "الخطوة 5: نحسب النتيجة: v_vol(0) = (0.4 * 10^(-3) mol/min) / 0.100 L = 4 * 10^(-3) mol / (L * min).",
      ],
      finalAnswer_ar: "v_vol(0) = 4.0 * 10^(-3) mol·L^(-1)·min^(-1)",
      verificationTip_ar: "تحقق دوماً من تناقص سرعة التفاعل مع مرور الزمن بسبب تناقص التراكيز المولية للمتفاعلات (تناقص التصادمات الفعالة).",
    },
    commonMistakes: [
      {
        id: "cm_phys_kinetics_vtot_omit",
        mistake_ar: "حساب ميل المماس واعتباره هو السرعة الحجمية مباشرة دون القسمة على V_tot.",
        whyItHappens_ar: "الخلط بين سرعة التفاعل v = dx/dt وبين السرعة الحجمية v_vol = (1/V_tot)*dx/dt.",
        correctAction_ar: "تحقق دوماً من نص السؤال: إذا طُلب 'السرعة الحجمية' فاقسم حتماً على V_tot.",
        suspectedErrorType: "forgot_information",
      },
      {
        id: "cm_phys_kinetics_unit_volume",
        mistake_ar: "ترك الحجم بالمليلتر (100) عند حساب السرعة الحجمية مما يجعل النتيجة خاطئة بعامل 1000.",
        whyItHappens_ar: "السرعة في التعويض العددي دون فحص الوحدات.",
        correctAction_ar: "حول الحجم دوماً إلى اللتر: V(L) = V(mL) * 10^(-3).",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت إيجاد العلاقة بين سرعة التفاعل وسرعة اختفاء أحد المتفاعلات أو تشكل أحد النواتج عبر المعاملات الستوكيومترية في دقيقة واحدة.",
    quickRecallPrompt_ar: "ما هو التعريف النظري لزمن نصف التفاعل t_{1/2}؟",
    quickRecallAnswer_ar: "هو المدة الزمنية اللازمة لبلوغ تقدم التفاعل نصف قيمته النهائية (x(t_{1/2}) = x_f / 2).",
    practiceQuestionIds: ["pq-phys-kinetics-01", "pq-phys-kinetics-02"],
    whatToDoIfYouFail_ar: "راجع بطاقة تصحيح السرعة الحجمية وتدرب على قراءة الميل ونقاط المماس بدقة على ورقة مليمترية.",
    summaryCard: {
      id: "sc_phys_kinetics",
      keyRule_ar: "v_vol = (1/V_tot) * (dx/dt). عند t_{1/2}: x(t_{1/2}) = x_f / 2.",
      keyFormula_ar: "ميل المماس = Δx / Δt. والسرعة الحجمية = الميل / V_tot.",
      trapToAvoid_ar: "إياك ونسيان تحويل V_tot إلى اللتر (L) وقسمة الميل عليه.",
    },
    retestQuestionId: "rq-phys-kinetics-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 12: physics_redox_titration
  // ==========================================================================
  {
    id: "lesson_physics_redox_titration",
    skillId: "physics_redox_titration",
    subjectId: "physics",
    topicId: "physics_topic_kinetics",
    title_ar: "المعايرة اللونية للأكسدة والإرجاع: نقطة التكافؤ والعلاقة الستوكيومترية",
    title_fr: "Titrage d'oxydoréduction : point d'équivalence et relation stœchiométrique",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من كتابة معادلة تفاعل الأكسدة والإرجاع انطلاقاً من الثنائيتين (Ox/Red)، وتطبيق العلاقة الستوكيومترية عند التكافؤ لحساب التركيز المجهول بنسبة خطأ 0%.",
    whatYouMustKnow_ar: "مفهوم المؤكسد والمرجع، وكتابة المعادلات النصفية الإلكترونية وموازنتها بالشوارد H+ وجزيئات H2O.",
    whyThisMatters_ar: "المعايرة اللونية هي إحدى الطريقتين الكيميائيتين الأساسيتين في الوحدة الأولى وتتكرر في البكالوريا مع شروط إنجازها وخصائص تفاعل المعايرة.",
    coreConcept_ar: "عند نقطة التكافؤ يكون المزيج التفاعلي في شروط ستوكيومترية؛ أي تختفي المتفاعلات كلياً بنفس النسبة: n_1 / a = n_2 / b، حيث a و b هما المعاملان الستوكيومتريان.",
    simpleExplanation_ar: "التكافؤ هو اللحظة الدقيقة التي ينتهي فيها المحلول المعايَر تماماً بفضل المحلول المعايِر المضاف من السحاحة، وتُعرف بتغير مفاجئ ومستقر للون المزيج.",
    workedExample: {
      id: "we_phys_titration_01",
      skillId: "physics_redox_titration",
      problem_ar: "نعاير حجماً V_1 = 20 mL من محلول كبريتات الحديد الثنائي (Fe^{2+}) تركيزه C_1 مجهول، بواسطة محلول برمنغنات البوتاسيوم (K^+ + MnO_4^-) تركيزه C_2 = 0.02 mol/L في وسط حمضي. حجم التكافؤ المسجل هو V_E = 12 mL. معطى الثنائيتان: (Fe^{3+}/Fe^{2+}) و (MnO_4^-/Mn^{2+}). احسب C_1.",
      howToThink_ar: "نكتب المعادلتين النصفيتين ثم معادلة الأكسدة والإرجاع الإجمالية لمعرفة المعاملات الستوكيومترية. عند التكافؤ نطبق العلاقة: n(Fe^{2+}) / 5 = n(MnO_4^-) / 1.",
      stepByStepSolution_ar: [
        "الخطوة 1: المعادلة النصفية للأكسدة: Fe^{2+} = Fe^{3+} + e^- (تضرب في 5).",
        "الخطوة 2: المعادلة النصفية للإرجاع: MnO_4^- + 8H^+ + 5e^- = Mn^{2+} + 4H_2O.",
        "الخطوة 3: معادلة تفاعل المعايرة: 5Fe^{2+} + MnO_4^- + 8H^+ -> 5Fe^{3+} + Mn^{2+} + 4H_2O.",
        "الخطوة 4: عند التكافؤ يكون المزيج ستوكيومترياً: n(Fe^{2+}) / 5 = n(MnO_4^-) / 1 أي C_1 * V_1 / 5 = C_2 * V_E / 1.",
        "الخطوة 5: نعزل المجهول C_1: C_1 = 5 * C_2 * V_E / V_1 = 5 * (0.02) * (12) / 20 = 5 * 0.02 * 0.6 = 0.06 mol/L.",
      ],
      finalAnswer_ar: "C_1 = 0.06 mol/L (أو 6.0 * 10^(-2) mol/L)",
      verificationTip_ar: "تذكر الخصائص الثلاث الإجبارية لتفاعل المعايرة في البكالوريا: سريع، تام، وفريد.",
    },
    commonMistakes: [
      {
        id: "cm_phys_titration_coeff_omit",
        mistake_ar: "كتابة C_1 * V_1 = C_2 * V_E مباشرة وإهمال المعامل الستوكيومتري 5 للحديد الثنائي.",
        whyItHappens_ar: "الاعتياد على المعايرة حمض-أساس أحادية التكافؤ وتعميمها خطأ على تفاعلات الأكسدة والإرجاع.",
        correctAction_ar: "اكتب المعادلة الإجمالية أولاً وتأكد دوماً من قسمة كمية مادة كل متفاعل على معامله الستوكيومتري.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_titration_acid_role",
        mistake_ar: "اعتبار حمض الكبريت المضاف متفاعلاً رئيسياً يدخل في الحساب الستوكيومتري الأساسي.",
        whyItHappens_ar: "عدم إدراك أن الوسط الحمضي دوره فقط توفير شوارد H+ اللازمة لعمل مؤكسد البرمنغنات.",
        correctAction_ar: "شوارد H+ والماء تؤخذ بوفـرة ولا تؤثر على نقطة التكافؤ بين Fe^{2+} و MnO_4^-.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت التعرف على كاشف اللون ونقطة التكافؤ بمجرد ثبات اللون الوردي للبرمنغنات وكتابة القانون الستوكيومتري مباشرة.",
    quickRecallPrompt_ar: "اذكر الخصائص الثلاث الأساسية لتفاعل المعايرة الكيميائية.",
    quickRecallAnswer_ar: "تفاعل سريع (quasi-instantané)، تام (total)، وفريد (unique).",
    practiceQuestionIds: ["pq-phys-titration-01", "pq-phys-titration-02"],
    whatToDoIfYouFail_ar: "تدرب على موازنة الثنائيات الأكسدة-إرجاع الشهيرة (البرمنغنات، ثنائي اليود، الماء الأكسجيني، الحديد الثنائي) قبل تكرار الاختبار.",
    summaryCard: {
      id: "sc_phys_titration",
      keyRule_ar: "عند التكافؤ: n_1 / a = n_2 / b  (شروط ستوكيومترية واختفاء تام للمتفاعلين).",
      keyFormula_ar: "C_1 * V_1 / a = C_2 * V_E / b.",
      trapToAvoid_ar: "لا تنس المعاملات الستوكيومترية في بسط ومقام علاقة التكافؤ.",
    },
    retestQuestionId: "rq-phys-titration-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 13: physics_rc_time_constant
  // ==========================================================================
  {
    id: "lesson_physics_rc_time_constant",
    skillId: "physics_rc_time_constant",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    title_ar: "ثابت الزمن tau لدارة RC: الدلالة الفيزيائية، الاستخراج البياني، والتحليل البعدي",
    title_fr: "Constante de temps tau du dipôle RC : signification, détermination graphique et analyse dimensionnelle",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من إيجاد ثابت الزمن tau حسابياً وبيانياً بطريقتين (المماس وطريقة 63%)، وإثبات تجانسه مع الزمن بالتحليل البعدي بدقة 100%.",
    whatYouMustKnow_ar: "قانون أوم للمقاومة (uR = R*i)، والعلاقة بين الشحنة والتوتر (q = C*uC)، وشدة التيار (i = dq/dt).",
    whyThisMatters_ar: "سؤال تحديد tau والتحليل البعدي يتكرر بنسبة تتجاوز 80% في مواضيع البكالوريا الخاصة بالظواهر الكهربائية، ومنه يتم حساب سعة المكثفة C أو المقاومة R.",
    coreConcept_ar: "ثابت الزمن tau = R * C يمثل المدة الزمنية اللازمة لبلوغ توتر المكثفة 63% من قيمته العظمى E أثناء الشحن، ويمثل بيانيا نقطة تقاطع مماس المنحنى عند المبدأ مع الخط المقارب uC = E.",
    simpleExplanation_ar: "ثابت الزمن هو مقياس لسرعة استجابة الدارة الكهربائية. كلما كان tau صغيراً، شحنت المكثفة بسرعة أكبر، وكلما كان كبيراً، استغرقت الدارة وقتاً أطول للوصول إلى النظام الدائم.",
    workedExample: {
      id: "we_physics_rc_01",
      skillId: "physics_rc_time_constant",
      problem_ar: "دارة كهربائية تحتوي على مولد توتره E = 6 V، وناقل أومي مقاومته R = 10 kOhm، ومكثفة سعتها C مجهولة. يقطع مماس منحنى شحن المكثفة uC(t) عند t=0 المستقيم المقارب uC = 6 V عند اللحظة t = 20 ms. 1) عين قيمة tau. 2) احسب سعة المكثفة C. 3) بين بالتحليل البعدي أن لـ tau بعد زمن.",
      howToThink_ar: "بيانياً: فاصلة نقطة تقاطع المماس عند المبدأ مع المقارب هي بالضبط tau. ثم نطبق C = tau / R مع تحويل kOhm إلى Ohm و ms إلى s. وللتحليل البعدي نستخدم قانون أوم والعلاقة q = C*u = i*t.",
      stepByStepSolution_ar: [
        "الخطوة 1: بيانياً: يقطع مماس المبدأ الخط المقارب عند t = 20 ms، إذن ثابت الزمن هو tau = 20 ms = 20 * 10^(-3) s = 0.02 s.",
        "الخطوة 2: حساب السعة C: لدينا tau = R * C ومنه C = tau / R = (20 * 10^(-3) s) / (10 * 10^3 Ohm) = 2 * 10^(-6) F = 2 microFarad.",
        "الخطوة 3: التحليل البعدي: لدينا [tau] = [R] * [C].",
        "الخطوة 4: من قانون أوم: [R] = [U] / [I]. ومن العلاقة q = I * t = C * U نجد: [C] = [I] * [T] / [U].",
        "الخطوة 5: بالتعويض: [tau] = ([U] / [I]) * ([I] * [T] / [U]) = [T]. ومنه لثابت الزمن tau بعد زمن ووحدته في النظام الدولي هي الثانية (s).",
      ],
      finalAnswer_ar: "tau = 20 ms، و C = 2 microFarad، و [tau] = [T] متجانس مع الزمن.",
      verificationTip_ar: "تحقق دائماً من حساب uC عند اللحظة tau: uC(tau) = 0.63 * 6 = 3.78 V، يجب أن تتطابق مع القراءة البيانية المقابلة لـ 20 ms.",
    },
    commonMistakes: [
      {
        id: "cm_physics_rc_unit_conversion",
        mistake_ar: "عدم تحويل 10 kOhm إلى 10^4 Ohm أو ترك 20 ms دون ضربها في 10^-3 عند حساب C.",
        whyItHappens_ar: "نسيان البادئات الفيزيائية (kilo = 10^3, milli = 10^-3, micro = 10^-6).",
        correctAction_ar: "حول كل المقادير فوراً إلى الوحدات الدولية الأساسية (s, Ohm, F) قبل إجراء الحساب.",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_physics_rc_steady_state",
        mistake_ar: "الاعتقاد بأن شحن المكثفة يكتمل عند اللحظة t = tau بدلاً من 5*tau.",
        whyItHappens_ar: "سوء فهم معنى ثابت الزمن؛ عند tau تشحن المكثفة بنسبة 63% فقط، والنظام الدائم يبدأ عند 5*tau.",
        correctAction_ar: "تذكر: مدة الشحن الكلي تقريباً هي 5*tau (تبلغ 99% من E).",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت كتابة برهان التحليل البعدي لثابت الزمن tau = RC كاملاً في أقل من دقيقتين دون النظر إلى الكراس.",
    quickRecallPrompt_ar: "ما هي النسبة المئوية لشحن المكثفة عند اللحظة t = tau، وما هي مدة النظام الانتقالي تقريباً؟",
    quickRecallAnswer_ar: "النسبة هي 63% (أي 0.63 E)، ومدة النظام الانتقالي هي 5*tau تقريباً.",
    practiceQuestionIds: ["pq-phys-rc-01", "pq-phys-rc-02"],
    whatToDoIfYouFail_ar: "افتح دليل إصلاح أخطاء دارة RC وتدرب على جدول التحويلات وقواعد التحليل البعدي.",
    summaryCard: {
      id: "sc_physics_rc",
      keyRule_ar: "ثابت الزمن: tau = R * C. بيانيا: فاصلة تقاطع مماس المبدأ مع المقارب الأفقي.",
      keyFormula_ar: "[tau] = [R] * [C] = ([U]/[I]) * ([I][T]/[U]) = [T] (الثانية s).",
      trapToAvoid_ar: "لا تنس تحويل الكيلوأوم kOhm بضربه في 10^3 والميلي ثانية ms بضربها في 10^-3.",
    },
    retestQuestionId: "rq-phys-rc-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 14: physics_rc_differential_equation
  // ==========================================================================
  {
    id: "lesson_physics_rc_differential_equation",
    skillId: "physics_rc_differential_equation",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    title_ar: "المعادلات التفاضلية لدارة RC (شحن وتفريغ) وتعيين الثوابت A و alpha",
    title_fr: "Équations différentielles du dipôle RC (charge et décharge) et identification des constantes",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تطبيق قانون جمع التوترات لتأسيس المعادلة التفاضلية لـ uC(t) أو q(t) أو i(t)، والتحقق من الحل الأسي وتعيين الثوابت A و alpha بدقة رياضية لا تشوبها شائبة.",
    whatYouMustKnow_ar: "قانون جمع التوترات، والعلاقة i = dq/dt = C * duC/dt، وقواعد اشتقاق الدالة الأسية.",
    whyThisMatters_ar: "سؤال كتابة المعادلة التفاضلية والتحقق من حلها وتعيين الثوابت من الأسئلة الأساسية الشائعة في مواضيع الكهرباء في البكالوريا.",
    coreConcept_ar: "بتطبيق قانون جمع التوترات: u_R + u_C = E. بتعويض u_R = R*i = R*C*(duC/dt)، نجد: duC/dt + (1/RC)*uC = E/RC.",
    simpleExplanation_ar: "المعادلة التفاضلية هي علاقة تربط المقدار المتغير (التوتر uC) بمشتقته الزمنية. حلها يبين لنا كيف ينتقل التوتر تدريجياً وبسلاسة من الصفر إلى القيمة العظمى E.",
    workedExample: {
      id: "we_phys_rc_diff_01",
      skillId: "physics_rc_differential_equation",
      problem_ar: "في دارة شحن مكثفة: 1) اكتب المعادلة التفاضلية للتوتر uC(t). 2) يقبل حلها الشكل: uC(t) = A * (1 - e^(-t / tau)). عين عبارتي الثابتين A و tau بدلالة مميزات الدارة.",
      howToThink_ar: "نطبق قانون جمع التوترات ونعوض i = C*duC/dt. ثم نشتق الحل المعطى ونعوضه هو ومشقته في المعادلة التفاضلية ونطابق لإيجاد الثوابت.",
      stepByStepSolution_ar: [
        "الخطوة 1: بتطبيق قانون جمع التوترات أثناء الشحن: u_R(t) + u_C(t) = E.",
        "الخطوة 2: لدينا u_R(t) = R * i(t) و i(t) = C * (duC/dt)، إذن: R*C*(duC/dt) + u_C(t) = E.",
        "الخطوة 3: نقسم على RC: duC/dt + (1/RC)*uC = E / RC (وهي المعادلة التفاضلية).",
        "الخطوة 4: نشتق الحل المعطى: uC(t) = A - A*e^(-t/tau) ومنه duC/dt = (A/tau)*e^(-t/tau).",
        "الخطوة 5: نعوض في المعادلة: (A/tau)*e^(-t/tau) + (1/RC)*[A - A*e^(-t/tau)] = E/RC. نجمع الحدود الأسية: e^(-t/tau) * [A/tau - A/RC] + [A/RC - E/RC] = 0. لكي تتحقق المساواة في كل لحظة t، يجب: A/tau - A/RC = 0 أي tau = RC، و A/RC - E/RC = 0 أي A = E.",
      ],
      finalAnswer_ar: "المعادلة التفاضلية: duC/dt + (1/RC)*uC = E/RC، والثوابت: A = E و tau = RC.",
      verificationTip_ar: "تحقق بالشروط الابتدائية: عند t = 0 المكثفة فارغة uC(0) = E*(1 - e^0) = 0 V. وعند t -> ∞ تصبح مشحونة كلياً uC(∞) = E*(1 - 0) = E. الحل متوافق تماماً.",
    },
    commonMistakes: [
      {
        id: "cm_phys_rc_diff_discharge_E",
        mistake_ar: "وضع E في الطرف الثاني أثناء تفريغ المكثفة وكتابة u_R + u_C = E بدلاً من u_R + u_C = 0.",
        whyItHappens_ar: "عدم الانتباه لوضعية البادلة (شحن أم تفريغ) وغياب المولد في دارة التفريغ.",
        correctAction_ar: "في التفريغ لا يوجد مولد في الدارة، إذن المجموع يساوي الصفر دائماً: u_R + u_C = 0.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_rc_diff_derivative_sign",
        mistake_ar: "الخطأ في اشتقاق الحل الأسي ونسيان إشارة الناقص مما يجعل المطابقة مستحيلة.",
        whyItHappens_ar: "اشتقاق -e^(-t/tau) كـ -e^(-t/tau) بدلاً من +(1/tau)*e^(-t/tau).",
        correctAction_ar: "مشتقة -e^(-alpha*t) هي +alpha*e^(-alpha*t).",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت كتابة المعادلة التفاضلية بدلالة الشحنة q(t) أو شدة التيار i(t) في التفريغ واستخراج حلها في أقل من 3 دقائق.",
    quickRecallPrompt_ar: "ما هي المعادلة التفاضلية لتفريغ مكثفة بدلالة التوتر uC(t)؟",
    quickRecallAnswer_ar: "duC/dt + (1/RC)*uC = 0",
    practiceQuestionIds: ["pq-phys-rc-diff-01", "pq-phys-rc-diff-02"],
    whatToDoIfYouFail_ar: "تدرب على تطبيق قانون جمع التوترات واشتقاق الدوال الأسية خطوة بخطوة في مسودة مخصصة قبل الاختبار.",
    summaryCard: {
      id: "sc_phys_rc_diff",
      keyRule_ar: "شحن: u_R + u_C = E => duC/dt + uC/RC = E/RC. تفريغ: u_R + u_C = 0 => duC/dt + uC/RC = 0.",
      keyFormula_ar: "حل الشحن: uC(t) = E*(1 - e^(-t/RC)). حل التفريغ: uC(t) = E*e^(-t/RC).",
      trapToAvoid_ar: "انتبه لحالة التفريغ؛ لا يوجد مولد في الدارة، والطرف الثاني للمعادلة يساوي الصفر حتماً.",
    },
    retestQuestionId: "rq-phys-rc-diff-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 15: physics_rl_circuit_response
  // ==========================================================================
  {
    id: "lesson_physics_rl_circuit_response",
    skillId: "physics_rl_circuit_response",
    subjectId: "physics",
    topicId: "physics_topic_rc_rl",
    title_ar: "دارة الوشيعة RL: التحريض الذاتي، المعادلة التفاضلية، وسلوك الوشيعة في النظامين",
    title_fr: "Dipôle RL : auto-induction, équation différentielle et comportement de la bobine",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من كتابة عبارة توتر الوشيعة u_b = L*(di/dt) + r*i، وتأسيس المعادلة التفاضلية لشدة التيار i(t)، وتحديد شدة التيار الأعظمية I_0 وثابت الزمن tau = L / (R + r) بيانياً وحسابياً.",
    whatYouMustKnow_ar: "قانون أوم لتوتر الوشيعة ذات المقاومة الداخلية r، وظاهرة التحريض الكهرومغناطيسي الذاتي التي تمانع تغيرات شدة التيار.",
    whyThisMatters_ar: "الوشيعة تختلف جوهرياً عن المكثفة؛ فهم سلوكها عند اللحظة t=0 (دارة مفتوحة تمنع مرور التيار فوراً) وفي النظام الدائم (ناقل أومي عادي) يمنحك فهم فيزيائي عميق لأسئلة البكالوريا.",
    coreConcept_ar: "الوشيعة تمانع تأسيس التيار اللحظي بسبب قوة محركة كهربائية متحرضة ذاتية e = -L*(di/dt). في النظام الدائم يصبح di/dt = 0 وتتصرف الوشيعة كمقاومة صرفة u_b = r*I_0 مع I_0 = E / (R + r).",
    simpleExplanation_ar: "الوشيعة مثل مروحة ثقيلة: تحتاج وقتاً لتدور وتصل لسرعتها القصوى (تأخير تأسيس التيار)، وإذا أوقفت تشغيلها تستمر في الدوران قليلاً (تأخير انقطاع التيار).",
    workedExample: {
      id: "we_phys_rl_01",
      skillId: "physics_rl_circuit_response",
      problem_ar: "دارة RL تحتوي على مولد E = 12 V، ناقل أومي R = 40 Ohm، ووشيعة ذاتيتها L ومقاومتها r = 8 Ohm. نغلق القاطعة عند t=0. 1) احسب شدة التيار في النظام الدائم I_0. 2) إذا كان ثابت الزمن المقاس هو tau = 5 ms، احسب ذاتية الوشيعة L.",
      howToThink_ar: "في النظام الدائم تصبح شدة التيار ثابتة إذن di/dt = 0، وبالتالي u_b = r*I_0، ونطبق قانون جمع التوترات: R*I_0 + r*I_0 = E. ولحساب الذاتية نطبق tau = L / R_tot.",
      stepByStepSolution_ar: [
        "الخطوة 1: المقاومة الكلية للدارة هي: R_tot = R + r = 40 + 8 = 48 Ohm.",
        "الخطوة 2: في النظام الدائم التيار ثابت di/dt = 0، إذن بتطبيق قانون جمع التوترات: u_R + u_b = E أي R*I_0 + r*I_0 = E.",
        "الخطوة 3: شدة التيار الأعظمية: I_0 = E / (R + r) = 12 V / 48 Ohm = 0.25 A = 250 mA.",
        "الخطوة 4: عبارة ثابت الزمن لدارة RL هي: tau = L / R_tot = L / (R + r).",
        "الخطوة 5: نعزل الذاتية L: L = tau * (R + r) = (5 * 10^(-3) s) * 48 Ohm = 0.24 H = 240 mH.",
      ],
      finalAnswer_ar: "I_0 = 0.25 A، وذاتية الوشيعة L = 0.24 H.",
      verificationTip_ar: "تحقق من التحليل البعدي لـ tau في دارة RL: [L/R] = ([U][T]/[I]) / ([U]/[I]) = [T] (الثانية s).",
    },
    commonMistakes: [
      {
        id: "cm_phys_rl_omit_internal_r",
        mistake_ar: "نسيان مقاومة الوشيعة r وكتابة I_0 = E/R وثابت الزمن tau = L/R.",
        whyItHappens_ar: "الافتراض الخاطئ بأن الوشيعة صرفة (مثالية) دائماً رغم ذكر r في المعطيات.",
        correctAction_ar: "تأكد من نص التمرين: إذا كانت الوشيعة حقيقية (L, r) فاستعمل دوماً المقاومة الكلية (R + r).",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_phys_rl_tau_inversion",
        mistake_ar: "الخلط بين ثابت زمن دارة RC (وهو الضرب R*C) وثابت زمن دارة RL وكتابة tau = R/L بدلاً من L/R.",
        whyItHappens_ar: "عدم تذكر التحليل البعدي لـ L و R.",
        correctAction_ar: "تذكر: الذاتية L في البسط والمقاومة في المقام: tau = L / R_tot.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت استنتاج المقاومة الداخلية r للوشيعة بيانياً من قيمة التوتر بين طرفي الوشيعة في النظام الدائم u_b(∞) = r*I_0.",
    quickRecallPrompt_ar: "ما هو تصرف الوشيعة الحقيقية (L, r) في اللحظة t = 0 وفي النظام الدائم t -> ∞؟",
    quickRecallAnswer_ar: "عند t=0 تتصرف كدارة مفتوحة (i=0 وتوترها أعظمي E). وفي النظام الدائم تتصرف كناقل أومي مقاومته r (حيث u_b = r*I_0).",
    practiceQuestionIds: ["pq-phys-rl-response-01", "pq-phys-rl-response-02"],
    whatToDoIfYouFail_ar: "راجع قانون جمع التوترات لدارة RL وقوانين الطاقة الكهرومغناطيسية المخزنة في الوشيعة E_L = (1/2)*L*i^2.",
    summaryCard: {
      id: "sc_phys_rl",
      keyRule_ar: "توتر الوشيعة: u_b = L*(di/dt) + r*i. في النظام الدائم: u_b = r*I_0 مع I_0 = E/(R+r).",
      keyFormula_ar: "ثابت الزمن لدارة RL: tau = L / (R + r).",
      trapToAvoid_ar: "احذر نسيان المقاومة الداخلية r للوشيعة؛ يجب جمعها مع المقاومة الخارجية R.",
    },
    retestQuestionId: "rq-phys-rl-response-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 16: physics_nuclear_decay_law
  // ==========================================================================
  {
    id: "lesson_physics_nuclear_decay_law",
    skillId: "physics_nuclear_decay_law",
    subjectId: "physics",
    topicId: "physics_topic_nuclear",
    title_ar: "قانون التناقص الإشعاعي، النشاط الإشعاعي A(t)، والربط بين lambda وزمن نصف العمر t_{1/2}",
    title_fr: "Loi de décroissance radioactive, activité A(t) et temps de demi-vie t_{1/2}",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تطبيق قانون التناقص الإشعاعي N(t) = N_0 * e^(-lambda*t)، واستغلال منحنيات النشاط الإشعاعي A(t) والمنحنيات الخطية ln(N) أو ln(A) لحساب عمر عينة مشعة (التأريخ).",
    whatYouMustKnow_ar: "قوانين الانحفاظ لصودي (انحفاظ العدد الكتلي A والعدد الشحني Z)، وتفككات ألفا وبيتا ناقص وبيتا زائد والإشعاع غاما.",
    whyThisMatters_ar: "حساب ثابت التفكك lambda وزمن نصف العمر t_{1/2} واستعمالهما في التأريخ هو التطبيق العملي الأبرز في مسألة الفيزياء النووية بالبكالوريا.",
    coreConcept_ar: "عدد الأنوية المتبقية يتناقص أسياً: N(t) = N_0 * e^(-lambda*t). والعلاقة الأساسية بين ثابت النشاط الإشعاعي lambda وزمن نصف العمر هي: lambda = ln(2) / t_{1/2}.",
    simpleExplanation_ar: "زمن نصف العمر هو الوقت الذي تحتاجه نصف الأنوية المشعة بالضبط لتتفكك وتتحول إلى أنوية أخرى أكثر استقراراً، وهو ثابت فيزيائي مميز لكل نظير ولا يتأثر بالحرارة أو الضغط.",
    workedExample: {
      id: "we_phys_nuclear_decay_01",
      skillId: "physics_nuclear_decay_law",
      problem_ar: "عينة مشعة من اليود 131 زمن نصف عمرها t_{1/2} = 8 jours. تحتوي العينة في اللحظة t=0 على N_0 = 1.0 * 10^15 نويدة مشعة. 1) احسب ثابت النشاط lambda بـ s^(-1). 2) احسب النشاط الإشعاعي الابتدائي A_0 بالبيكربل (Bq). 3) ما هو عدد الأنوية المتبقية بعد مرور 24 يوماً؟",
      howToThink_ar: "نحول t_{1/2} من الأيام إلى الثواني لحساب lambda بوحدة SI. ثم نطبق A_0 = lambda * N_0. وبعد 24 يوماً نلاحظ أنها تمثل 3*t_{1/2}، مما يسهل الحساب المباشر N = N_0 / 2^3.",
      stepByStepSolution_ar: [
        "الخطوة 1: تحويل t_{1/2} إلى الثواني: t_{1/2} = 8 * 24 * 3600 s = 691200 s = 6.912 * 10^5 s.",
        "الخطوة 2: حساب ثابت النشاط الإشعاعي: lambda = ln(2) / t_{1/2} = 0.693 / (6.912 * 10^5 s) = 1.00 * 10^(-6) s^(-1).",
        "الخطوة 3: حساب النشاط الابتدائي A_0: A_0 = lambda * N_0 = (1.00 * 10^(-6) s^(-1)) * (1.0 * 10^15) = 1.0 * 10^9 Bq = 1.0 GBq.",
        "الخطوة 4: حساب عدد الأنوية عند t = 24 jours: نلاحظ أن t = 24 / 8 = 3 * t_{1/2}.",
        "الخطوة 5: بعد مرور 3 أزمنة نصف عمر يتنصف المقدار 3 مرات: N = N_0 / (2^3) = N_0 / 8 = (1.0 * 10^15) / 8 = 1.25 * 10^14 نويدة.",
      ],
      finalAnswer_ar: "lambda = 1.0 * 10^(-6) s^(-1)، A_0 = 1.0 * 10^9 Bq، و N(24 j) = 1.25 * 10^14 نويدة.",
      verificationTip_ar: "تأكد دوماً: وحدة البيكريل (Bq) تعني تفككاً واحداً في الثانية، لذا يجب إلزامياً أن يكون lambda معبراً عنه بـ s^(-1) عند حساب A = lambda * N.",
    },
    commonMistakes: [
      {
        id: "cm_phys_nuclear_bq_unit",
        mistake_ar: "حساب النشاط الإشعاعي A بضرب N في قيمة lambda المحسوبة باليوم^-1 أو السنة^-1 دون التحويل للثانية.",
        whyItHappens_ar: "نسيان أن البيكريل Bq متجانس مع s^(-1) حصرياً في النظام الدولي.",
        correctAction_ar: "حول دائماً t_{1/2} إلى الثانية (s) قبل حساب النشاط الإشعاعي A بالبيكربل Bq.",
        suspectedErrorType: "calculation_error",
      },
      {
        id: "cm_phys_nuclear_remaining_vs_decayed",
        mistake_ar: "الخلط بين عدد الأنوية المتبقية N(t) وعدد الأنوية المتفككة N_d(t) = N_0 - N(t).",
        whyItHappens_ar: "قراءة غير دقيقة لنص السؤال في البكالوريا.",
        correctAction_ar: "قانون التناقص N(t) يعطي المتبقي؛ ولحساب المتفكك اطرح من العدد الابتدائي: N_d = N_0 * (1 - e^(-lambda*t)).",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت استخراج عمر عينة خشب قديم (تأريخ بالكربون 14) بحل المعادلة A(t)/A_0 = e^(-lambda*t) وإيجاد t بالسنوات في دقيقتين.",
    quickRecallPrompt_ar: "ما هي العلاقة بين ثابت التفكك lambda وزمن نصف العمر t_{1/2}؟ وما هي العلاقة بين النشاط A وعدد الأنوية N؟",
    quickRecallAnswer_ar: "lambda = ln(2) / t_{1/2} ، و A(t) = lambda * N(t).",
    practiceQuestionIds: ["pq-phys-decay-01", "pq-phys-decay-02"],
    whatToDoIfYouFail_ar: "راجع تحويلات وحدات الزمن (سنة إلى يوم إلى ثانية) وراجع خواص الدالة اللوغاريتمية في حل معادلات التأريخ.",
    summaryCard: {
      id: "sc_phys_decay",
      keyRule_ar: "N(t) = N_0 * e^(-lambda*t). النشاط الإشعاعي: A(t) = lambda * N(t).",
      keyFormula_ar: "lambda = ln(2) / t_{1/2}. وعند t = n * t_{1/2} يكون N = N_0 / 2^n.",
      trapToAvoid_ar: "لحساب A بالبيكريل (Bq)، يجب أن يكون lambda مقلوب ثانية s^(-1) حصراً.",
    },
    retestQuestionId: "rq-phys-decay-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 17: physics_mass_defect_binding_energy
  // ==========================================================================
  {
    id: "lesson_physics_mass_defect_binding_energy",
    skillId: "physics_mass_defect_binding_energy",
    subjectId: "physics",
    topicId: "physics_topic_nuclear",
    title_ar: "النقص الكتلي، طاقة الربط النووي E_l، ومقارنة الاستقرار عبر E_l / A ومخطط أستون",
    title_fr: "Défaut de masse, énergie de liaison E_l, stabilité par nucléon et courbe d'Aston",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من حساب النقص الكتلي للنواة بالوحدة الكتلة الذرية (u)، وحساب طاقة الربط E_l بالميغا إلكترون فولط (MeV)، ومقارنة استقرار نواتين بالاعتماد على طاقة الربط لكل نوية E_l / A.",
    whatYouMustKnow_ar: "تركيب النواة (Z بروتون و N = A - Z نوترون)، ومكافئ الطاقة للكتلة الذرية: 1 u = 931.5 MeV/c^2.",
    whyThisMatters_ar: "تحديد النواة الأكثر استقراراً وحساب الحصيلة الطاقوية لتفاعل انشطار أو اندماج نووي من الأسئلة المنهجية المباشرة الشائعة في تمارين النووي في البكالوريا.",
    coreConcept_ar: "كتلة النواة المشكلة أقل دوماً من مجموع كتل مكوناتها وهي متفرقة: Delta_m = [Z*m_p + (A-Z)*m_n] - m_noyau > 0. هذا النقص الكتلي يتحول إلى طاقة ربط: E_l = Delta_m * c^2. والنواة الأكثر استقراراً هي التي تملك أكبر طاقة ربط لكل نوية E_l / A.",
    simpleExplanation_ar: "عندما تتجمع البروتونات والنيوترونات لتشكيل نواة، تضحي بجزء ضئيل من كتلتها لتتحول إلى طاقة تماسك جبارة تحمي النواة من التفكك.",
    workedExample: {
      id: "we_phys_mass_defect_01",
      skillId: "physics_mass_defect_binding_energy",
      problem_ar: "معطيات نواة الهيليوم ^4_2He: m(He) = 4.00150 u، كتلة البروتون m_p = 1.00728 u، كتلة النيوترون m_n = 1.00866 u. 1) احسب النقص الكتلي Delta_m بالوحدة u. 2) احسب طاقة الربط E_l بـ MeV. 3) احسب طاقة الربط لكل نوية E_l / A.",
      howToThink_ar: "الهيليوم 4 يتكون من Z = 2 بروتون و N = 4 - 2 = 2 نيوترون. نحسب مجموع كتل المكونات ونطرح كتلة النواة، ثم نضرب مباشرة في 931.5 MeV للحصول على E_l دون تحويل للكلغ.",
      stepByStepSolution_ar: [
        "الخطوة 1: مكونات النواة: Z = 2 بروتون، و N = 4 - 2 = 2 نيوترون.",
        "الخطوة 2: مجموع كتل النويات منفصلة: 2*m_p + 2*m_n = 2*(1.00728) + 2*(1.00866) = 2.01456 + 2.01732 = 4.03188 u.",
        "الخطوة 3: حساب النقص الكتلي: Delta_m = (2*m_p + 2*m_n) - m(He) = 4.03188 - 4.00150 = 0.03038 u.",
        "الخطوة 4: حساب طاقة الربط النووي: E_l = Delta_m * 931.5 MeV = 0.03038 * 931.5 = 28.299 MeV.",
        "الخطوة 5: طاقة الربط لكل نوية: E_l / A = 28.299 MeV / 4 = 7.075 MeV/nucléon.",
      ],
      finalAnswer_ar: "Delta_m = 0.03038 u، E_l = 28.30 MeV، و E_l/A = 7.07 MeV/نوية.",
      verificationTip_ar: "إذا أعطيت الكتل بـ u، فاضرب النقص الكتلي مباشرة في 931.5 للحصول على MeV؛ لا تحول إلى kg إلا إذا طُلب حساب الطاقة بالجول (J) باستخدام c = 3*10^8 m/s.",
    },
    commonMistakes: [
      {
        id: "cm_phys_stability_total_energy",
        mistake_ar: "الحكم على استقرار النواة بطاقة الربط الكلية E_l بدلاً من طاقة الربط لكل نوية E_l / A.",
        whyItHappens_ar: "افتراض أن الطاقة الكبرى تعني استقراراً أكبر، في حين أن نواة اليورانيوم مثلاً تملك E_l ضخمة لكنها غير مستقرة لأن E_l/A أصغر من الحديد 56.",
        correctAction_ar: "المعيار الحصري للاستقرار النووي هو القيمة الأكبر لـ E_l / A وليس E_l الكلية.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_mass_defect_sign",
        mistake_ar: "طرح مجموع كتل النويات من كتلة النواة والحصول على نقص كتلي سالب.",
        whyItHappens_ar: "الخلط بين النقص الكتلي للنواة Delta_m (الموجب دوماً) وبين تغير الكتلة في التفاعل النووي Delta_m_reaction.",
        correctAction_ar: "النقص الكتلي للنواة موجب دوماً: كتل المكونات المنفصلة (الأثقل) ناقص كتلة النواة.",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت مقارنة نواتين مثل Fe-56 و U-235 وتبرير سبب ميل الأنوية الثقيلة للانشطار والأنوية الخفيفة للاندماج استناداً إلى مخطط أستون.",
    quickRecallPrompt_ar: "ما هو الشرط الفيزيائي الدقيق لتكون نواة X أكثر استقراراً من نواة Y؟",
    quickRecallAnswer_ar: "أن تكون طاقة الربط لكل نوية للنواة X أكبر من طاقة الربط لكل نوية للنواة Y: [E_l / A](X) > [E_l / A](Y).",
    practiceQuestionIds: ["pq-phys-mass-defect-01", "pq-phys-mass-defect-02"],
    whatToDoIfYouFail_ar: "تدرب على حساب الفروق الكتلية بدقة 5 أرقام بعد الفاصلة واستعمال معامل التحويل 931.5 MeV/u.",
    summaryCard: {
      id: "sc_phys_mass_defect",
      keyRule_ar: "النقص الكتلي: Delta_m = [Z*m_p + (A-Z)*m_n] - m_nuc > 0. طاقة الربط: E_l = Delta_m * c^2.",
      keyFormula_ar: "E_l (MeV) = Delta_m (u) * 931.5 MeV/u. الاستقرار يُقاس حصراً بـ E_l / A.",
      trapToAvoid_ar: "إياك والمقارنة بـ E_l؛ النواة الأكثر استقراراً هي صاحبة أكبر قيمة لـ E_l / A.",
    },
    retestQuestionId: "rq-phys-mass-defect-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 18: physics_newton_second_law
  // ==========================================================================
  {
    id: "lesson_physics_newton_second_law",
    skillId: "physics_newton_second_law",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    title_ar: "القانون الثاني لنيوتن وإسقاط القوى على المستوي المائل والأفقي",
    title_fr: "Deuxième loi de Newton et projections des forces sur plan incliné",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تطبيق القانون الثاني لنيوتن بمنهجية رسمية كاملة (الجملة، المرجع، إحصاء القوى، الرسم، والإسقاط الدقيق لمركبات الثقل P_x و P_y) لحساب التسارع وقوة الاحتكاك.",
    whatYouMustKnow_ar: "الشعاعية والمثلثات (sin و cos للزاوية alpha)، والقوى الميكانيكية المألوفة (الثقل P، رد الفعل R، قوة الجر F، وقوة الاحتكاك f).",
    whyThisMatters_ar: "حركة الأجسام على المستوي المائل أو الأفقي مسألة حتمية في ميكانيك البكالوريا؛ الخطأ في إسقاط مركبة الثقل يقلب معادلة التسارع ويلغي علامة الحسابات اللاحقة.",
    coreConcept_ar: "في معلم غاليلي مرتبط بسطح الأرض، مجموع القوى الخارجية المؤثرة على جملة مادية يساوي جداء كتلتها في شعاع تسارع مركز عطالتها: Σ F_ext = m * a.",
    simpleExplanation_ar: "القانون يربط بين الأسباب (القوى المؤثرة) والنتيجة (التسارع والتغير في السرعة). ولكي نتمكن من الحساب، نسقط العلاقة الشعاعية على محاور الحركة.",
    workedExample: {
      id: "we_phys_newton_01",
      skillId: "physics_newton_second_law",
      problem_ar: "ينزلق جسم كتلته m = 500 g على مستوٍ مائل بزاوية alpha = 30° بالنسبة للأفق بدون سرعة ابتدائية تحت تأثير ثقله فقط وقوة احتكاك ثابتة f = 1 N. نعتبر g = 9.8 m/s^2. 1) بتطبيق القانون الثاني لنيوتن، جد عبارة التسارع a بدلالة المقادير المعطاة. 2) احسب قيمة التسارع a وطبيعة الحركة.",
      howToThink_ar: "نحدد الجملة والمرجع بدقة، ونحصي القوى (الثقل P ورد الفعل R المعامد للسطح والاحتكاك f المعاكس لجهة الحركة). نوجه المحور Ox نحو الأسفل في جهة الحركة، ونسقط عليه.",
      stepByStepSolution_ar: [
        "الخطوة 1: الجملة المدروسة: الجسم الصلب (S). المرجع: سطحي أرضي نعتبره غاليلياً.",
        "الخطوة 2: القوى الخارجية: الثقل P، رد فعل السطح R، وقوة الاحتكاك f المعاكسة للحركة.",
        "الخطوة 3: تطبيق القانون الثاني لنيوتن: P + R + f = m * a (علاقة شعاعية).",
        "الخطوة 4: الإسقاط على محور الحركة Ox الموجه نحو أسفل المستوي: مسقط الثقل هو +P*sin(alpha)، مسقط R منعدم، ومسقط f هو -f. إذن: P*sin(alpha) - f = m * a.",
        "الخطوة 5: نعزل التسارع ونعوض P = m*g: a = g*sin(alpha) - f/m = 9.8 * sin(30°) - 1.0 / 0.500 = 9.8 * 0.5 - 2.0 = 4.9 - 2.0 = 2.9 m/s^2.",
      ],
      finalAnswer_ar: "عبارة التسارع: a = g*sin(alpha) - f/m، وقيمته: a = 2.9 m/s^2 (حركة مستقيمة متسارعة بانتظام لأن المسار مستقيم و a > 0 ثابت).",
      verificationTip_ar: "تذكر دائماً: على المستوي المائل بزاوية alpha مع الأفق، مركبة الثقل الموازية للسطح Ox تأخذ دوماً sin(alpha) لأنها المقابل للزاوية في المثلث القائم.",
    },
    commonMistakes: [
      {
        id: "cm_phys_newton_trig_confusion",
        mistake_ar: "استعمال cos(alpha) بدلاً من sin(alpha) لمركبة الثقل الموازية للمستوي المائل.",
        whyItHappens_ar: "الاعتياد على أن محور الفواصل يأخذ التجيب (cos) دون رسم مثلث القوى.",
        correctAction_ar: "ارسم زاوية الميل alpha بدقة؛ الضلع الموازي للسطح هو المقابل للزاوية alpha إذن P_x = P * sin(alpha).",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_newton_omit_reference",
        mistake_ar: "إهمال كتابة الجملة الميكانيكية والمرجع الغاليلي والانطلاق فوراً في كتابة P + R = ma.",
        whyItHappens_ar: "التسرع الرياضي وإهمال الشروط المنهجية الفيزيائية في سلم التنقيط.",
        correctAction_ar: "ابدأ دوماً بسطرين إجباريين: 1) الجملة، 2) المرجع المختار وفرضيته الغاليلية.",
        suspectedErrorType: "methodology_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت كتابة الإسقاط على المحور العمودي Oy واستنتاج عبارة رد الفعل R = m*g*cos(alpha) دون أي تردد.",
    quickRecallPrompt_ar: "ما هي مركبة الثقل P الموازية للمستوي المائل بزاوية alpha مع الأفق، وما هي المركبة العمودية عليه؟",
    quickRecallAnswer_ar: "المركبة الموازية: P_x = m*g*sin(alpha). المركبة العمودية: P_y = m*g*cos(alpha).",
    practiceQuestionIds: ["pq-phys-newton-01", "pq-phys-newton-02"],
    whatToDoIfYouFail_ar: "أعد رسم المستوي المائل ومثلث القوى للثقل P مع محوري الإسقاط وتأكد من تحديد الزاوية alpha بالتماثل والتعامد.",
    summaryCard: {
      id: "sc_phys_newton",
      keyRule_ar: "Σ F_ext = m * a. على مستوٍ مائل: P_x = m*g*sin(alpha) و P_y = m*g*cos(alpha).",
      keyFormula_ar: "محور الحركة: m*g*sin(alpha) - f = m*a => a = g*sin(alpha) - f/m.",
      trapToAvoid_ar: "احذر الخلط بين sin و cos؛ المركبة الموازية للسطح المائل تأخذ sin(alpha).",
    },
    retestQuestionId: "rq-phys-newton-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 19: physics_satellite_kepler
  // ==========================================================================
  {
    id: "lesson_physics_satellite_kepler",
    skillId: "physics_satellite_kepler",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    title_ar: "حركة الأقمار الاصطناعية والكواكب: معلم فريني، السرعة المدارية، وقوانين كبلر",
    title_fr: "Mouvement des satellites et planètes : repère de Frenet, vitesse orbitale et lois de Kepler",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تطبيق قانون الجذب العام في معلم فريني لإثبات دائرية الحركة وانتظامها، واستخراج عبارتي السرعة المدارية v والدور T، وإثبات القانون الثالث لكبلر T^2 / r^3 = ثابت.",
    whatYouMustKnow_ar: "قانون التجاذب الكوني لنيوتن F = G*M*m/r^2، ومعلم فريني ومركبتا التسارع (a_t = dv/dt و a_n = v^2/r).",
    whyThisMatters_ar: "تمرين الأقمار الاصطناعية من التمارين المألوفة والمتكررة؛ خطوات برهانه ثابتة ومحددة وتساعد المتدرب عليها على صياغة برهان نموذجي متكامل.",
    coreConcept_ar: "قوة الجذب المركزي ناظمية محضة موجهة نحو مركز الكوكب: F = m * a_n = G*M*m/r^2. ومسقطها على المماس منعدم (a_t = 0 مما يثبت أن السرعة v ثابتة والحركة دائرية منتظمة).",
    simpleExplanation_ar: "القمر الاصطناعي في حالة سقوط حر دائم نحو الأرض، لكن سرعته الأفقية كافية لكي ينحني مساره بنفس انحناء سطح الأرض فلا يصطدم بها أبداً.",
    workedExample: {
      id: "we_phys_kepler_01",
      skillId: "physics_satellite_kepler",
      problem_ar: "قمر اصطناعي كتلته m يدور في مسار دائري نصف قطره r حول الأرض التي كتلتها M_T. 1) بين أن حركة القمر دائرية منتظمة في المرجع الجيومركزي. 2) جد عبارة السرعة المدارية v بدلالة G و M_T و r. 3) جد عبارة الدور T وأثبت القانون الثالث لكبلر.",
      howToThink_ar: "نطبق القانون الثاني لنيوتن مع قوة الجذب العام في معلم فريني. نثبت a_t = 0 لانتظام الحركة، ثم نساوي a_n بـ v^2/r لإيجاد v. ونعوض v في علاقة الدور T = 2*pi*r / v.",
      stepByStepSolution_ar: [
        "الخطوة 1: الجملة: القمر الاصطناعي. المرجع: الجيومركزي (مركزي أرضي) نعتبره غاليلياً. القوة الوحيدة: قوة الجذب العام F_{T/S} = G*M_T*m / r^2 موجهة نحو مركز الأرض وفق الناظم n.",
        "الخطوة 2: بتطبيق القانون الثاني لنيوتن: F = m*a. بالإسقاط على المماس t: F_t = 0 إذن m*a_t = 0 أي dv/dt = 0 فالسرعة v ثابتة، والحركة دائرية منتظمة.",
        "الخطوة 3: بالإسقاط على الناظم n: G*M_T*m / r^2 = m * a_n = m * (v^2 / r).",
        "الخطوة 4: باختزال الكتلة m ونصف القطر r: v^2 = G*M_T / r ومنه السرعة المدارية: v = sqrt(G*M_T / r).",
        "الخطوة 5: عبارة الدور: T = 2*pi*r / v = 2*pi*r / sqrt(G*M_T / r) = 2*pi * sqrt(r^3 / (G*M_T)). بتربيع الطرفين: T^2 = 4*pi^2 * r^3 / (G*M_T) ومنه: T^2 / r^3 = 4*pi^2 / (G*M_T) = ثابت (وهو القانون الثالث لكبلر).",
      ],
      finalAnswer_ar: "v = sqrt(G*M_T / r) و T^2 / r^3 = 4*pi^2 / (G*M_T) = ثابت مستقل عن كتلة القمر m.",
      verificationTip_ar: "تأكد دوماً: نصف القطر r يمثل البعد عن مركز الأرض r = R_T + h وليس الارتفاع h فقط. انتبه لجمع نصف قطر الأرض R_T وتحويله إلى الأمتار.",
    },
    commonMistakes: [
      {
        id: "cm_phys_kepler_altitude_radius",
        mistake_ar: "التعويض بالارتفاع h مباشرة في قانون الجذب والسرعة بدلاً من البعد عن المركز r = R_T + h.",
        whyItHappens_ar: "الخلط بين ارتفاع القمر عن السطح وبين نصف قطر المدار الدائري.",
        correctAction_ar: "اكتب دائماً: r = R_T + h وحول كليهما إلى المتر (m).",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_kepler_mass_satellite",
        mistake_ar: "الاعتقاد بأن سرعة القمر أو دوره يعتمدان على كتلته m.",
        whyItHappens_ar: "نسيان أن كتلة القمر تختزل في القانون الثاني لنيوتن.",
        correctAction_ar: "سرعة ودور القمر مستقلان تماماً عن كتلته m ويعتمدان فقط على كتلة الكوكب المركزي M_T والبعد r.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت تعريف القمر الاصطناعي الجيومستقر بدقة واشتقاق شروطه الثلاثة (يدور في اتجاه دوران الأرض، دوره 24 ساعة، ويقع في مستوي خط الاستواء).",
    quickRecallPrompt_ar: "ما هي عبارة السرعة المدارية v لقمر اصطناعي حول الأرض؟ وما هي الشروط الثلاثة للقمر الجيومستقر؟",
    quickRecallAnswer_ar: "v = sqrt(G*M_T / r). الشروط: 1) مداره في مستوي خط الاستواء، 2) جهة دورانه هي نفس جهة دوران الأرض، 3) دوره T يساوي دور دوران الأرض حول نفسها (T = 24 h).",
    practiceQuestionIds: ["pq-phys-kepler-01", "pq-phys-kepler-02"],
    whatToDoIfYouFail_ar: "راجع معلم فريني والعلاقة بين السرعة والدور والقانون الثالث لكبلر في بطاقة المراجعة.",
    summaryCard: {
      id: "sc_phys_kepler",
      keyRule_ar: "v = sqrt(G*M/r). الدور: T = 2*pi*sqrt(r^3 / G*M).",
      keyFormula_ar: "القانون الثالث لكبلر: T^2 / r^3 = 4*pi^2 / (G*M). البعد المداري: r = R_T + h.",
      trapToAvoid_ar: "احذر نسيان جمع نصف قطر الأرض: r = R_T + h مع تحويل الكيلومتر إلى متر بضربه في 10^3.",
    },
    retestQuestionId: "rq-phys-kepler-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 20: physics_acid_base_ph_ka
  // ==========================================================================
  {
    id: "lesson_physics_acid_base_ph_ka",
    skillId: "physics_acid_base_ph_ka",
    subjectId: "physics",
    topicId: "physics_topic_acid_base",
    title_ar: "تفاعلات حمض-أساس: الـ pH، ثابت الحموضة K_a، نسبة التقدم النهائي tau_f، ومخطط الصفة الغالبة",
    title_fr: "Réactions acide-base : pH, constante d'acidité K_a, taux d'avancement final tau_f et diagramme de prédominance",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من التمييز بين الحمض القوي والحمض الضعيف عبر نسبة التقدم النهائي tau_f، وحساب ثابت الحموضة K_a و pK_a، وإنشاء مخطط الصفة الغالبة للثنائية بدقة تامة.",
    whatYouMustKnow_ar: "تعريف الـ pH = -log[H3O+]، والجداء الشاردي للماء K_e = [H3O+]*[OH-] = 10^(-14) عند 25°C.",
    whyThisMatters_ar: "وحدة الأحماض والأسس ركيزة أساسية في الجزء الكيميائي من البكالوريا؛ ربط pH المحلول بثابت الحموضة K_a يمنحك فهم المنحنيات البيانية للمعايرة pH-مترية.",
    coreConcept_ar: "يكون التحول تاماً (حمض قوي) إذا كان tau_f = x_f / x_max = 1. ويكون غير تام (حمض ضعيف في حالة توازن) إذا كان tau_f < 1. وترتبط نسبة الصفة الغالبة بالعلاقة: pH = pK_a + log([Base] / [Acide]).",
    simpleExplanation_ar: "الحمض القوي يتشرد كلياً في الماء، بينما الحمض الضعيف يتشرد جزئياً فقط وتنشأ حالة توازن حركي بين الجزيئات السليمة وشوارد الهيدرونيوم الناتجة.",
    workedExample: {
      id: "we_phys_acid_base_01",
      skillId: "physics_acid_base_ph_ka",
      problem_ar: "نحضر محلولاً مائياً لحمض الميثانويك HCOOH تركيزه المولي C = 0.10 mol/L، نقيس pH المحلول فنجد pH = 2.4 عند 25°C. 1) احسب تركيز شوارد الهيدرونيوم [H3O+]. 2) احسب نسبة التقدم النهائي tau_f وماذا تستنتج؟ 3) احسب ثابت الحموضة K_a للثنائية.",
      howToThink_ar: "نحسب [H3O+] من علاقة 10^(-pH). ثم نحسب x_f = [H3O+]*V و x_max = C*V ومنه tau_f = [H3O+]/C. ونعوض في عبارة K_a = [H3O+]^2 / (C - [H3O+]).",
      stepByStepSolution_ar: [
        "الخطوة 1: تركيز شوارد الهيدرونيوم: [H3O+] = 10^(-pH) = 10^(-2.4) = 3.98 * 10^(-3) mol/L.",
        "الخطوة 2: التقدم الأعظمي x_max = C * V، والتقدم النهائي x_f = [H3O+] * V.",
        "الخطوة 3: نسبة التقدم النهائي: tau_f = x_f / x_max = [H3O+] / C = (3.98 * 10^(-3)) / 0.10 = 0.0398 = 3.98%.",
        "الخطوة 4: الاستنتاج: بما أن tau_f < 1 (أي 4% فقط تفكك)، فإن انحلال حمض الميثانويك في الماء غير تام، وحمض HCOOH هو حمض ضعيف.",
        "الخطوة 5: حساب K_a: تركيز الحمض المتبقي عند التوازن هو [HCOOH] = C - [H3O+]. عبارة K_a = [H3O+] * [HCOO^-] / [HCOOH] = [H3O+]^2 / (C - [H3O+]) = (3.98 * 10^(-3))^2 / (0.10 - 0.00398) = 1.58 * 10^(-5) / 0.096 = 1.65 * 10^(-4).",
      ],
      finalAnswer_ar: "tau_f = 4.0% (حمض ضعيف)، و K_a = 1.65 * 10^(-4) (ومنه pK_a = -log(K_a) = 3.78).",
      verificationTip_ar: "تأكد من خاصية الصفة الغالبة: إذا كان pH < pK_a فإن الصفة الحمضية هي الغالبة، وإذا كان pH > pK_a فإن الصفة الأساسية هي الغالبة، وعند pH = pK_a يتساوى التركيزان.",
    },
    commonMistakes: [
      {
        id: "cm_phys_acid_base_tau_f_percent",
        mistake_ar: "كتابة tau_f = 0.04 واعتباره حمضاً قوياً لعدم الانتباه أنه يمثل 4% فقط وليس 1.",
        whyItHappens_ar: "الخلط بين 1 كقيمة عددية عظمى لـ tau_f وبين 100%.",
        correctAction_ar: "الحمض القوي يحقق tau_f = 1 (أو 100%). أي قيمة أصغر من 1 تدل حتماً على حمض ضعيف.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_acid_base_ka_water",
        mistake_ar: "إدخال تركيز الماء [H2O] في عبارة كسر ثابت التوازن K_a.",
        whyItHappens_ar: "التعويض الحرفي لجميع عناصر معادلة التفاعل في كسر التوازن.",
        correctAction_ar: "الماء مذيب كيميائي يؤخذ تركيزه اصطلاحاً مساوياً لـ 1 في عبارة كسر التوازن ولا يكتب.",
        suspectedErrorType: "forgot_information",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت رسم محور الـ pH وتحديد مجالات غلبة الحمض والأساس لنقطة نصف التكافؤ (حيث pH = pK_a) في أقل من دقيقة.",
    quickRecallPrompt_ar: "ما هي العلاقة الرياضية التي تربط بين pH المحلول وثابت pK_a وتراكيز الثنائية (حمض/أساس)؟",
    quickRecallAnswer_ar: "pH = pK_a + log([الأساس المرفق] / [الحمض])",
    practiceQuestionIds: ["pq-phys-ph-ka-01", "pq-phys-ph-ka-02"],
    whatToDoIfYouFail_ar: "تدرب على جدول تقدم التفاعل لتفكك حمض في الماء وتطبيق قوانين اللوغاريتم في حسابات الـ pH.",
    summaryCard: {
      id: "sc_phys_acid_base",
      keyRule_ar: "tau_f = [H3O+]/C. إذا tau_f = 1 فالحمض قوي، وإذا tau_f < 1 فالحمض ضعيف.",
      keyFormula_ar: "pH = pK_a + log([Base]/[Acide]). K_a = [H3O+]^2 / (C - [H3O+]).",
      trapToAvoid_ar: "لا تنس: الماء مذيب وتركيزه لا يدخل في عبارة ثابت التوازن K_a.",
    },
    retestQuestionId: "rq-phys-ph-ka-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 21: physics_esterification_equilibrium
  // ==========================================================================
  {
    id: "lesson_physics_esterification_equilibrium",
    skillId: "physics_esterification_equilibrium",
    subjectId: "physics",
    topicId: "physics_topic_esterification",
    title_ar: "تفاعلات الأسترة والإماهة: الخصائص، المردود، صنف الكحول، وتأثير العوامل الحركية",
    title_fr: "Estérification et hydrolyse : caractéristiques, rendement selon la classe d'alcool et facteurs cinétiques",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تسمية الإسترات وكتابة معادلة الأسترة والإماهة، وحساب المردود r انطلاقاً من المزيج الابتدائي، وتحديد صنف الكحول (أولي 67%، ثانوي 60%، ثالثي 5-10%)، واقتراح طرق تحسين المردود والسرعة.",
    whatYouMustKnow_ar: "الصيغ نصف المفصلة للأحماض الكربوكسيلية والكحولات، والمجموعات الوظيفية المميزة (الكربوكسيل -COOH والهيدروكسيل -OH والإستر -COO-).",
    whyThisMatters_ar: "الأسترة هي وحدة الكيمياء العضوية الختامية في البكالوريا؛ أسئلتها حول خصائص التفاعل ومردوده وطرق تسريعه وتحسينه أسئلة نظرية وحسابية متكررة جداً.",
    coreConcept_ar: "تفاعل الأسترة عكوس ومحدود بحالة توازن حركي (حمض + كحول <=> إستر + ماء). مردوده لمزيج متساوي المولات يعتمد حصرياً على صنف الكحول: أولي (67%)، ثانوي (60%)، ثالثي (5% إلى 10%). وثابت التوازن K لمزيج كحول أولي متساوي المولات هو K = 4.",
    simpleExplanation_ar: "التفاعل بطيء وعكوس: عندما يتشكل الإستر والماء يعودان ليتفاعلا معاً في الاتجاه المعاكس (إماهة)، فيتوقف التفاعل قبل استهلاك المتفاعلات عند الوصول إلى التوازن.",
    workedExample: {
      id: "we_phys_ester_01",
      skillId: "physics_esterification_equilibrium",
      problem_ar: "نمزج n_0 = 1 mol من حمض الإيثانويك مع n_0 = 1 mol من كحول مجهول R-OH وبضع قطرات من حمض الكبريت المركز. عند بلوغ حالة التوازن الكيميائي نجد أن كمية مادة الإستر المتشكلة هي n_ester = 0.67 mol. 1) اذكر خصائص تفاعل الأسترة. 2) احسب مردود التفاعل r واستنتج صنف الكحول المستعمل. 3) احسب ثابت التوازن K.",
      howToThink_ar: "نحدد الخصائص الثلاث (بطيء، عكوس، لا حراري). ونحسب المردود r = (x_f / x_max) * 100%. وبما أن r = 67% نستنتج مباشرة أنه كحول أولي. ثم نطبق K = (x_f)^2 / (n_0 - x_f)^2.",
      stepByStepSolution_ar: [
        "الخطوة 1: خصائص تفاعل الأسترة: تفاعل بطيء (lent)، عكوس ومحدود (réversible et limité)، ولا حراري (athermique أي لا ينشر ولا يمتص حرارة).",
        "الخطوة 2: التقدم الأعظمي في مزيج متساوي المولات هو x_max = 1.0 mol، والتقدم النهائي المسجل عند التوازن هو x_f = 0.67 mol.",
        "الخطوة 3: حساب المردود: r = (x_f / x_max) * 100% = (0.67 / 1.0) * 100% = 67%.",
        "الخطوة 4: صنف الكحول: بما أن المزيج الابتدائي متساوي المولات والمردود يساوي 67%، فإن الكحول المستعمل هو كحول أولي (alcool primaire).",
        "الخطوة 5: حساب ثابت التوازن K: عند التوازن n(ester) = n(eau) = x_f = 0.67 mol، و n(acide) = n(alcool) = 1 - 0.67 = 0.33 mol. عبارة K = [ester]*[eau] / ([acide]*[alcool]) = (x_f)^2 / (n_0 - x_f)^2 = (0.67)^2 / (0.33)^2 = 0.4489 / 0.1089 = 4.12 ≈ 4.",
      ],
      finalAnswer_ar: "المردود r = 67%، الكحول أولي، وثابت التوازن K ≈ 4 (بدون وحدة).",
      verificationTip_ar: "ملاحظة جوهرية: في تفاعل الأسترة يدخل الماء في عبارة ثابت التوازن K ولا يعتبر مذيباً بوفـرة لأنه ناتج كيميائي مرافق للإستر بكمية محدودة.",
    },
    commonMistakes: [
      {
        id: "cm_phys_ester_water_equilibrium",
        mistake_ar: "حذف الماء من عبارة ثابت التوازن K للأسترة باعتباره مذيباً كما في تفاعلات الأحماض والأسس.",
        whyItHappens_ar: "الخلط بين المحاليل المائية الممددة وبين تفاعل الأسترة الذي يتم دون ماء مذيب ويكون فيه الماء ناتجاً مكافئاً للإستر.",
        correctAction_ar: "في تفاعل الأسترة، يجب إلزامياً كتابة تركيز أو كمية مادة الماء في بسط ثابت التوازن K: K = (n_ester * n_eau) / (n_acide * n_alcool).",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_ester_catalyst_yield",
        mistake_ar: "الاعتقاد بأن إضافة وسيط (مثل حمض الكبريت المركز) أو التسخين يرفع مردود التفاعل r.",
        whyItHappens_ar: "الخلط بين تسريع التفاعل (العوامل الحركية) وبين إزاحة حالة التوازن (تحسين المردود).",
        correctAction_ar: "الوسيط ودرجة الحرارة يسرعان التفاعل فقط دون تغيير المردود النهائي إطلاقاً. لتحسين المردود نستعمل متفاعل بوفرة أو نسحب أحد النواتج بالتقطير.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت ذكر طريقتين لتحسين مردود الأسترة (استعمال أحد المتفاعلين بوفرة، أو سحب الماء أو الإستر المتشكل أثناء التفاعل، أو استعمال كلور الحمض بدلاً من الحمض الكربوكسيلي للوصول إلى تفاعل تام وسريع 100%).",
    quickRecallPrompt_ar: "ما هي قيم مردود الأسترة لمزيج متساوي المولات حسب أصناف الكحول الثلاثة؟",
    quickRecallAnswer_ar: "كحول أولي: 67% ، كحول ثانوي: 60% ، كحول ثالثي: من 5% إلى 10%.",
    practiceQuestionIds: ["pq-phys-ester-01", "pq-phys-ester-02"],
    whatToDoIfYouFail_ar: "راجع تسمية الإسترات وتصنيف الكحولات وقانون ثابت التوازن K للأسترة في بطاقة المراجعة.",
    summaryCard: {
      id: "sc_phys_ester",
      keyRule_ar: "خصائص الأسترة: بطيء، عكوس، ولا حراري. المردود: أولي 67%، ثانوي 60%، ثالثي 5-10%.",
      keyFormula_ar: "ثابت التوازن: K = (n_ester * n_eau) / (n_acide * n_alcool) = 4 (للكحول الأولي).",
      trapToAvoid_ar: "الوسيط والتسخين يسرعان التفاعل فقط ولا يغيران المردود أو ثابت التوازن K أبداً.",
    },
    retestQuestionId: "rq-phys-ester-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 22: phys_rlc_electrical_oscillations
  // ==========================================================================
  {
    id: "lesson_phys_rlc_electrical_oscillations",
    skillId: "phys_rlc_electrical_oscillations",
    subjectId: "physics",
    topicId: "physics_topic_circuits",
    title_ar: "الاهتزازات الكهربائية الحرة: دارة RLC والتفريغ المتخامد وغير المتخامد",
    title_fr: "Oscillations électriques libres : circuit RLC, régimes d'amortissement et période propre T0",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من إقامة المعادلة التفاضلية لتوتر المكثفة u_C(t) في دارة RLC المتسلسلة، وتفسير أصل التخامد الطاقوي بمفعول جول، وحساب الدور الذاتي T_0 = 2π√(LC) للدارة المثالية LC، والتمييز بين الأنظمة الاهتزازية الثلاثة بيانيا.",
    whatYouMustKnow_ar: "قانون جمع التوترات، عبارة توتر الوشيعة u_b = L(di/dt) + ri، علاقة التيار بالمكثفة i = C(du_C/dt)، وعبارة الطاقة المخزنة في المكثفة والوشيعة.",
    whyThisMatters_ar: "دراسة الاهتزازات الكهربائية دارة RLC تتيح فهم التبادل الطاقوي بين المكثفة والوشيعة وحساب شبه الدور والدور الذاتي، وهي محور مرجعي يربط بين الكهرباء والاهتزازات الميكانيكية في امتحان البكالوريا.",
    coreConcept_ar: "تتحول الطاقة دورياً بين شكل كهربائي في المكثفة وشكل مغناطيسي في الوشيعة. في غياب المقاومة (R_total = 0)، تكون الحركة جيبية نقية غير متخامدة بدور ذاتي T_0 = 2π√(LC). وبوجود المقاومة، تتبدد الطاقة تدريجياً بمفعول جول مما يسبب تخامد السعة (نظام شبه دوري أو حرج أو لا دوري).",
    simpleExplanation_ar: "تخيل المكثفة المشحونة كخزان ماء مرتفع والوشيعة كمضخة ذات عطالة؛ عندما تفرغ المكثفة في الوشيعة ينشأ تيار، وعندما تفرغ المكثفة تماماً تمنع الوشيعة التيار من التوقف فتعيد شحن المكثفة بقطبية معكوسة، وتتكرر العملية دورياً.",
    workedExample: {
      id: "we_phys_rlc_01",
      skillId: "phys_rlc_electrical_oscillations",
      problem_ar: "دارة RLC متسلسلة تحتوي على مكثفة سعتها C = 10 μF ووشيعة ذاتيتها L = 0.1 H ومقاومتها الداخلية مهملة (r = 0). بافتراض المقاومة الكلية للدارة منعدمة (دارة LC مثالية)، احسب الدور الذاتي T_0 للاهتزازات الكهربائية الحرة. (خذ π² ≈ 10 و π ≈ 3.14)",
      howToThink_ar: "نحول سعة المكثفة إلى الفاراد (F) والذاتية إلى الهنري (H)، ثم نطبق عبارة الدور الذاتي لدارة طومسون LC: T_0 = 2π√(LC).",
      stepByStepSolution_ar: [
        "الخطوة 1: نحدد المعطيات ونحولها إلى الوحدات الدولية (SI): C = 10 μF = 10 × 10^(-6) F = 10^(-5) F، و L = 0.1 H = 10^(-1) H.",
        "الخطوة 2: نحسب جداء LC: LC = 10^(-1) × 10^(-5) = 10^(-6) s².",
        "الخطوة 3: نحسب الجذر التربيعي للجداء: √(LC) = √(10^(-6)) = 10^(-3) s.",
        "الخطوة 4: نطبق قانون الدور الذاتي: T_0 = 2π√(LC) = 2π × 10^(-3) s.",
        "الخطوة 5: نعوض قيمة π بالتقريب: T_0 ≈ 2 × 3.14 × 10^(-3) = 6.28 × 10^(-3) s = 6.28 ms.",
      ],
      finalAnswer_ar: "T_0 = 6.28 × 10^(-3) s (أي 6.28 ms)",
      verificationTip_ar: "تحقق بالتحليل البعدي: [LC] = [T]²، وبالتالي [√(LC)] = [T] بالثانية.",
    },
    commonMistakes: [
      {
        id: "cm_phys_rlc_period_formula",
        mistake_ar: "كتابة الدور الذاتي T_0 = 2π/(LC) أو T_0 = 2π√(L/C) بدلاً من 2π√(LC).",
        whyItHappens_ar: "الخلط مع عبارة ثابت الزمن للوشيعة τ = L/R أو النبض الذاتي ω₀ = 1/√(LC).",
        correctAction_ar: "احفظ قانون طومسون: الدور يتناسب طردياً مع جذر كل من الذاتية والسعة T_0 = 2π√(LC).",
        suspectedErrorType: "forgot_information",
      },
      {
        id: "cm_phys_rlc_pseudo_vs_proper",
        mistake_ar: "اعتبار شبه الدور T مساوياً للدور الذاتي T_0 في كل الحالات.",
        whyItHappens_ar: "إهمال أثر المقاومة في إنقاص تواتر الاهتزاز؛ فالتساوي T ≈ T_0 لا يصح إلا إذا كانت المقاومة ضعيفة جداً.",
        correctAction_ar: "صرح دوماً بأن T ≈ T_0 فقط في حالة التخامد الضعيف (R_total مهملة أو صغيرة جداً).",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت كتابة المعادلة التفاضلية لـ u_C(t) في دارة RLC واشتقاق عبارة T_0 في دقيقتين.",
    quickRecallPrompt_ar: "ما هي عبارة الدور الذاتي T_0 لدارة LC مثالية وماذا يحدث له إذا ضاعفنا كلاً من L و C أربع مرات؟",
    quickRecallAnswer_ar: "T_0 = 2π√(LC)؛ إذا ضاعفنا L و C أربع مرات فإن T_0 يتضاعف 4 مرات لأن √(4×4) = 4.",
    practiceQuestionIds: ["pq-phys-rlc-oscillations-01"],
    whatToDoIfYouFail_ar: "راجع درس تفريغ المكثفة في الوشيعة وقوانين الطاقة الكلية في دارة RLC.",
    summaryCard: {
      id: "sc_phys_rlc",
      keyRule_ar: "دارة LC مثالية: اهتزازات جيبية غير متخامدة وطاقة كلية محفوظة E_T = (1/2)Cu_C² + (1/2)Li² = ثابت.",
      keyFormula_ar: "الدور الذاتي: T_0 = 2π√(LC) ، المعادلة التفاضلية: d²u_C/dt² + (1/LC)u_C = 0.",
      trapToAvoid_ar: "الضياع بمفعول جول في المقاومة R_T يسبب تخامداً أسياً لسعة الاهتزازات (نظام شبه دوري).",
    },
    retestQuestionId: "rq-phys-rlc-oscillations-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 23: phys_mechanical_oscillations_spring
  // ==========================================================================
  {
    id: "lesson_phys_mechanical_oscillations_spring",
    skillId: "phys_mechanical_oscillations_spring",
    subjectId: "physics",
    topicId: "physics_topic_mechanics",
    title_ar: "الاهتزازات الميكانيكية: النواس المرن وتطبيق القانون الثاني لنيوتن",
    title_fr: "Oscillations mécaniques : pendule élastique horizontal, équation différentielle et période propre",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من تطبيق القانون الثاني لنيوتن لإقامة المعادلة التفاضلية لاهتزازات النواس المرن الأفقي، واستنتاج النبض الذاتي ω₀ والدور الذاتي T_0 = 2π√(m/k)، وتحليل انحفاظ وتحولات الطاقة الميكانيكية.",
    whatYouMustKnow_ar: "القانون الثاني لنيوتن ΣF⃗ = m·a⃗، عبارة قوة التوتر للنابض T⃗ = -kx·i⃗، وتعريف طاقة الوضع المرونية E_pe = (1/2)kx² والطاقة الحركية E_c = (1/2)mv².",
    whyThisMatters_ar: "النواس المرن هو النموذج الأساسي للاهتزازات الميكانيكية في بكالوريا العلوم التجريبية؛ يتطلب دقة في الإسقاط والإشارات وفهماً عميقاً للتبادل بين الطاقة الحركية وطاقة المرونة.",
    coreConcept_ar: "قوة توتر النابض T⃗ = -k·x·i⃗ قوة إرجاع تعاكس دائماً إزاحة الجسم عن موضع التوازن. في غياب الاحتكاك، تكون المعادلة التفاضلية: d²x/dt² + (k/m)x = 0، وحلها جيبي x(t) = X_max · cos(ω₀t + φ) بدور ذاتي T_0 = 2π√(m/k)، وتكون الطاقة الميكانيكية الكلية محفوظة: E = E_c + E_pe = (1/2)k X_max².",
    simpleExplanation_ar: "عند شد النابض، نخزن فيه طاقة كامنة مرونية. عند تركه، تتحول إلى طاقة حركية وتبلغ ذروتها عند موضع التوازن (x=0) بينما تنعدم الطاقة الكامنة، ثم يستمر الجسم بحكم العطالة فيضغط النابض وتنعكس الدورة.",
    workedExample: {
      id: "we_phys_mech_spring_01",
      skillId: "phys_mechanical_oscillations_spring",
      problem_ar: "جسم صلب كتلته m = 0.25 kg مثبت بنهاية نابض أفقي ثابت مرونته k = 100 N/m ومهمل الكتلة. نهمل جميع قوى الاحتكاك ونزيح الجسم عن موضع توازنه بسعة X_max = 4 cm ثم نتركه بدون سرعة ابتدائية. 1) احسب الدور الذاتي T_0 لاهتزازات الجملة (خذ π² ≈ 10 و π ≈ 3.14). 2) احسب الطاقة الميكانيكية الكلية للجملة.",
      howToThink_ar: "نطبق عبارة الدور الذاتي للنواس المرن T_0 = 2π√(m/k). ولحساب الطاقة الميكانيكية نحول السعة إلى المتر X_max = 0.04 m ونطبق E = (1/2)k X_max².",
      stepByStepSolution_ar: [
        "الخطوة 1: نحدد النسبة m/k: m/k = 0.25 / 100 = 0.0025 = 25 × 10^(-4) kg/(N/m) = s².",
        "الخطوة 2: نحسب الجذر التربيعي: √(m/k) = √(25 × 10^(-4)) = 5 × 10^(-2) = 0.05 s.",
        "الخطوة 3: نحسب الدور الذاتي: T_0 = 2π√(m/k) = 2π × 0.05 = 0.1π ≈ 0.1 × 3.14 = 0.314 s.",
        "الخطوة 4: نحول السعة إلى المتر: X_max = 4 cm = 0.04 m = 4 × 10^(-2) m.",
        "الخطوة 5: نحسب الطاقة الميكانيكية الكلية: E = (1/2) · k · X_max² = (1/2) × 100 × (0.04)² = 50 × 0.0016 = 0.08 J.",
      ],
      finalAnswer_ar: "الدور الذاتي T_0 = 0.314 s ، والطاقة الميكانيكية E = 0.08 J (أي 80 mJ).",
      verificationTip_ar: "تحقق من أن وحدة ثابت المرونة k هي N/m = kg·s^(-2)، فيكون بعد m/k هو s² وبعد الجذر هو الثانية s.",
    },
    commonMistakes: [
      {
        id: "cm_phys_mech_sign_spring",
        mistake_ar: "إغفال إشارة الناقص في قوة الإرجاع وكتابة T = +kx في المعادلة التفاضلية.",
        whyItHappens_ar: "نسيان أن متجهة قوة توتر النابض تكون موجهة دوماً عكس متجهة الموضع x⃗ نحو مركز التوازن.",
        correctAction_ar: "اكتب دوماً T_x = -kx عندما يكون المحور موجباً في جهة الاستطالة، فتكون المعادلة: m(d²x/dt²) + kx = 0.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_mech_energy_units",
        mistake_ar: "تعويض السعة X_max بالسنتيمتر (4 cm) مباشرة في قانون الطاقة E = (1/2)kx² مما يضخم النتيجة 10000 مرة.",
        whyItHappens_ar: "إهمال التحويل إلى وحدة النظام الدولي (المتر).",
        correctAction_ar: "حول السعة دوماً إلى المتر: X_max(m) = X_max(cm) × 10^(-2).",
        suspectedErrorType: "calculation_error",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت رسم المنحنيات البيانية لـ E_c(t) و E_pe(t) وبيان أن دور تبادل الطاقة هو T_0 / 2.",
    quickRecallPrompt_ar: "أين تنعدم طاقة الوضع المرونية في النواس المرن وأين تبلغ قيمتها العظمى؟",
    quickRecallAnswer_ar: "تنعدم عند موضع التوازن x = 0 ، وتبلغ قيمتها العظمى عند الموضعين الحديين x = +X_max و x = -X_max.",
    practiceQuestionIds: ["pq-phys-mech-spring-01"],
    whatToDoIfYouFail_ar: "راجع إسقاط القوى في معلم فريني وعلى المحور الأفقي وقوانين انحفاظ الطاقة الميكانيكية.",
    summaryCard: {
      id: "sc_phys_mech_spring",
      keyRule_ar: "قوة الإرجاع: T⃗ = -k·x·i⃗ تعاكس جهة الحركة والإزاحة دوماً، وتضمن حركة جيبية دورية.",
      keyFormula_ar: "الدور الذاتي: T_0 = 2π√(m/k) ، المعادلة التفاضلية: d²x/dt² + (k/m)x = 0 ، الطاقة: E = (1/2)k X_max².",
      trapToAvoid_ar: "دور تبادل الطاقة (الحركية والمرونية) يساوي نصف دور الاهتزازات: T_E = T_0 / 2.",
    },
    retestQuestionId: "rq-phys-mech-spring-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },

  // ==========================================================================
  // LESSON 24: phys_esterification_hydrolysis_equilibrium
  // ==========================================================================
  {
    id: "lesson_phys_esterification_hydrolysis_equilibrium",
    skillId: "phys_esterification_hydrolysis_equilibrium",
    subjectId: "physics",
    topicId: "physics_topic_esterification",
    title_ar: "الكيمياء العضوية: تفاعلات الأسترة والإماهة، المردود ومراقبة السرعة",
    title_fr: "Chimie organique : estérification et hydrolyse, constante K et dérivés d'acides",
    targetCapability_ar: "بعد نهاية هذا الدرس، ستتمكن من كتابة معادلة تفاعل الأسترة والإماهة، وتحديد كميات المادة عند حالة التوازن الكيميائي وحساب كسر التفاعل وثابت التوازن K، والتمييز بين العوامل الحركية المؤثرة على السرعة وطرق تحسين المردود باستعمال مشتقات الأحماض الكربوكسيلية (كلور الأسيل).",
    whatYouMustKnow_ar: "الصيغ العامة للأحماض الكربوكسيلية R-COOH والكحولات R'-OH والإسترات R-COO-R'، وجدول التقدم لحساب كميات المادة عند التوازن.",
    whyThisMatters_ar: "تفاعلات الأسترة تمثل التطبيق النموذجي لحالة التوازن الكيميائي الديناميكي في الكيمياء العضوية؛ التفريق بين تسريع التفاعل (وساطة/حرارة) وإزاحة التوازن (مردود تام بكلور الأسيل) هو ركيزة أساسية للعلامة الكاملة في بكالوريا العلوم التجريبية.",
    coreConcept_ar: "الأسترة تفاعل بطيء، عكوس، ولا حراري. ثابت التوازن K لمزيج متساوي المولات يعبر عنه بـ K = (n_ester · n_eau) / (n_acide · n_alcool) حيث يدخل الماء كناتج أساسي. العوامل الحركية (التسخين والوساطة الحمضية H₂SO₄) تسرع بلوغ التوازن فقط دون تغيير المردود، بينما استبدال الحمض بكلور الأسيل (R-COCl) يجعل التفاعل تاماً (مردود 100%) وسريعاً ونواشراً للحرارة.",
    simpleExplanation_ar: "التسخين يزيد سرعة الجزيئات فتصل لحالة التوازن أسرع كمن يركض نحو خط النهاية، بينما استعمال كلور الأسيل ينقل خط النهاية نفسه إلى 100% لأن التفاعل يصبح غير عكوس.",
    workedExample: {
      id: "we_phys_ester_hydrolysis_01",
      skillId: "phys_esterification_hydrolysis_equilibrium",
      problem_ar: "نمزج 1 mol من حمض الإيثانويك CH₃COOH مع 1 mol من الميثانول CH₃OH (كحول أولي). عند بلوغ حالة التوازن الكيميائي، نجد أن كمية مادة الإستر المتشكل هي n_ester = 0.67 mol. 1) اكتب معادلة تفاعل الأسترة مع تسمية الإستر المتشكل. 2) أنشئ جدول التقدم واحسب كميات مادة جميع الأنواع عند التوازن. 3) احسب كسر التفاعل عند التوازن (ثابت التوازن K).",
      howToThink_ar: "نكتب التفاعل R-COOH + R'-OH ⇌ R-COO-R' + H₂O. نسمي الإستر: إيثانوات الميثيل. عند التوازن كميات النواتج x_f وكميات المتفاعلات 1 - x_f. ثم نطبق K = (x_f)² / (1 - x_f)².",
      stepByStepSolution_ar: [
        "الخطوة 1: معادلة تفاعل الأسترة: CH₃COOH + CH₃OH ⇌ CH₃COO-CH₃ + H₂O. الإستر الناتج هو: إيثانوات الميثيل (éthanoate de méthyle).",
        "الخطوة 2: جدول التقدم لمزيج متساوي المولات (n₀ = 1 mol):",
        "  - n(إستر) = x_f = 0.67 mol.",
        "  - n(ماء) = x_f = 0.67 mol.",
        "  - n(حمض) = n₀ - x_f = 1 - 0.67 = 0.33 mol.",
        "  - n(كحول) = n₀ - x_f = 1 - 0.67 = 0.33 mol.",
        "الخطوة 3: عبارة ثابت التوازن K: K = ([إستر] · [ماء]) / ([حمض] · [كحول]) = (n_ester · n_eau) / (n_acide · n_alcool) (تختزل الحجوم V).",
        "الخطوة 4: التعويض العددي: K = (0.67 × 0.67) / (0.33 × 0.33) = (0.67 / 0.33)² = (2.03)² ≈ 4.12.",
      ],
      finalAnswer_ar: "معادلة الأسترة: CH₃COOH + CH₃OH ⇌ CH₃COOCH₃ + H₂O (إيثانوات الميثيل)، وثابت التوازن K ≈ 4.12.",
      verificationTip_ar: "قيمة K تقارب 4 وهي القيمة النظرية المميزة لتفاعل الأسترة انطلاقاً من كحول أولي.",
    },
    commonMistakes: [
      {
        id: "cm_phys_ester_hydrolysis_catalyst",
        mistake_ar: "الاعتقاد بأن إضافة قطرات من حمض الكبريت المركز تزيد من كمية الإستر المتشكل عند التوازن.",
        whyItHappens_ar: "الخلط بين زيادة سرعة التفاعل (دور الوسيط) وزيادة المردود (الحالة النهائية).",
        correctAction_ar: "الوسيط يسرع الوصول إلى التوازن فقط ولا يؤثر أبداً على التركيب النهائي للمزيج التفاعلي أو ثابت التوازن K.",
        suspectedErrorType: "misunderstood_concept",
      },
      {
        id: "cm_phys_ester_water_omission",
        mistake_ar: "حذف الماء من عبارة K باعتباره مذيباً كما في المحاليل المائية.",
        whyItHappens_ar: "التعود على تفاعلات الأحماض والأسس حيث يكون الماء بوفـرة فلا يكتب في عبارة K_a.",
        correctAction_ar: "في الأسترة، لا يوجد ماء في البداية، والماء المتشكل ناتج مكافئ للإستر ويجب كتابة تركيزه في البسط.",
        suspectedErrorType: "misunderstood_concept",
      },
    ],
    howToKnowYouUnderstood_ar: "إذا استطعت اقتراح 3 طرق مختلفة لزيادة مردود الإستر (استعمال متفاعل بوفرة، سحب الماء، أو استبدال الحمض بكلور الأسيل).",
    quickRecallPrompt_ar: "ما هي مميزات تفاعل كحول مع كلور الأسيل مقارنة بتفاعله مع حمض كربوكسيلي؟",
    quickRecallAnswer_ar: "تفاعل تام (مردود 100%)، سريع، ناشر للحرارة، وغير عكوس، وينتج عنه كلور الهيدروجين HCl بدلاً من الماء.",
    practiceQuestionIds: ["pq-phys-ester-hydrolysis-01"],
    whatToDoIfYouFail_ar: "راجع تسمية مشتقات الأحماض (كلور الأسيل، أنهيدريد الحمض) وقوانين التوازن الكيميائي في الكيمياء العضوية.",
    summaryCard: {
      id: "sc_phys_ester_hydrolysis",
      keyRule_ar: "الأسترة تفاعل متوازن محدود بـ K؛ رفع المردود يتطلب إزاحة التوازن (وفرة متفاعل أو نزع ناتج)، أو استعمال كلور الأسيل لتفاعل تام 100%.",
      keyFormula_ar: "ثابت التوازن: K = (n_ester · n_eau) / (n_acide · n_alcool) ≈ 4 (كحول أولي).",
      trapToAvoid_ar: "حمض الكبريت المركز H₂SO₄ وسيط يسرع التفاعل فقط ولا يغير المردود النهائي إطلاقاً.",
    },
    retestQuestionId: "rq-phys-ester-hydrolysis-01",
    estimatedMinutes: 15,
    sourceId: "src-bac-mastery-pedagogy",
    sourceType: "original_bac_mastery",
    rightsStatus: "original",
    verificationStatus: "verified",
    academicYear: "2024-2025",
    isActive: true,
  },
];
